### ISSUE TITLE
Provide a way to import encrypted backups from old version

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#1]

**Comment by mymindstorm** [comment]
This should be as simple as giving users instructions on the wiki to paste into notepad and saving the file correctly. Other than that the line in storage.ts blocking imports of encrypted secrets should be removed.

**Comment by Sneezry** [comment]
If we remove that line, we have to handle the situation that the current passphrass cannot decrypt the encrypted backup

**Comment by Sneezry** [comment]
Maybe the easiest way is to provide a standalone tool to decrypt backup and save it as a JSON file

**Comment by mymindstorm** [comment]
Or request the password on import before inserting it into storage.
