### ISSUE TITLE
Importing backups in firefox doesn't work

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#10]
When the file select dialog comes up, it closes the popup and stops processing js.

**Comment by mymindstorm** [comment]
@Sneezry the best way to handle this would be to use backround.ts, right?

**Comment by mymindstorm** [comment]
Or wait I could just add entry.ts to the background?

**Comment by Sneezry** [comment]
Does Firefox close popup when system file dialog shows?

**Comment by mymindstorm** [comment]
Annoyingly, yes. I'm not sure I can keep it from closing from what I see on MDN.

**Comment by Sneezry** [comment]
Seems an old bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1292701

background won't help, because if popup closed, we would never receive the file. I have no idea about the workaround about `noautohide` mentioned in that ticket, is it a possible solution in our extension?

**Comment by mymindstorm** [comment]
It just has to get the data to storage.ts, which is already loaded in the background so it should be possible to make this work. It closes too fast to make a drag and drop picker work.

As a last resort I could try to either:
- Open a new window to something that handles the files
- [Implement a settings page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Implement_a_settings_page) just for the firefox version

**Comment by mymindstorm** [comment]
`noautohide` is something from the legacy addons system https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Attribute/panel.noautohide

**Comment by mymindstorm** [comment]
Another bug to keep an eye on: https://bugzilla.mozilla.org/show_bug.cgi?id=1366330
