### ISSUE TITLE
Some are encrypted, some are invalid and other are solved

### ISSUE THREAD

**Issue by qx2** [Authenticator-Extension/Authenticator#101]
after last nights update this is how my data looks now. I use both mac and windows extension in chrome only.
<img width="614" alt="after latest update" src="https://user-images.githubusercontent.com/2142235/37860675-bf53ff88-2ee7-11e8-901d-945c2fc04089.png">

**Comment by Sneezry** [comment]
Can you see a resolved TeamViewer entry?

**Comment by Brianetta** [comment]
I had some that remained `Encrypted`. I restored from backup.

**Comment by qx2** [comment]
none of the team viewer entries are resolved. I did try to restore from backup, same problem. I even tried deleting all entries and starting from scratch, because i have all my keys saved but anything i re-add still behaves the same way, either encrypted or invalid. How would I start over from scratch? do I have to uninstall the extension from all machines and start over. Or go into every machine and delete every entry? I don't mind do it once just not sure that will work.

**Comment by Sneezry** [comment]
@qx2 If you have all data backup, you can reinstall the extension safely. Is your backup encrypted?

**Comment by Sneezry** [comment]
@Brianetta is your backup encrypted?

**Comment by Brianetta** [comment]
No. I have never taken an encrypted backup, in case I need to restore to different product.

**Comment by Sneezry** [comment]
@qx2 is there any space in the secret of TeamViewer?

**Comment by SuperValue** [comment]
I'm having some problems too with this new version.  After I type in the password, only some things are unencrypted.  I actually reinstalled the extension, re-added everything from scratch, and re-encrypted using "Security".  Then after I enter the password, it only decrypts a single entry.    

So everything seems OK except when I try to use "Security".  If i leave it unecrypted, its fine.

**Comment by Sneezry** [comment]
@SuperValue Does your secret contain spaces? This is a known issue, and will be fixed in v5.0.9

**Comment by SuperValue** [comment]
Ah, yes i see now.  The only one that Decrypted correctly had no spaces.  I usually just cut and paste from the web page with the secret.

**Comment by Sneezry** [comment]
Then it seems this issue is duplicate with https://github.com/Authenticator-Extension/Authenticator/issues/103. I will close this issue.
