### ISSUE TITLE
Chrome instability

### ISSUE THREAD

**Issue by 1951FDG** [Authenticator-Extension/Authenticator#1010]
### Describe the issue

Previously it would crash for Chrome versions a while ago, current versions it seem to be crashing silently while trying to copy a code, as in you try to copy code it fails, it kinda stops reacting, you go back to interface and copy again and now copy works.

### Browser

Chrome

### Browser Version

Version 109.0.5414.119 (Official Build) (arm64)

### Extension Version

109.0.5414.119

**Comment by Sneezry** [comment]
Is there any permission popup on the top left corner of your screen?

**Comment by 1951FDG** [comment]
Nope, permissions seems to be fine, no permission popup visible.

**Comment by mymindstorm** [comment]
Please follow [these steps](https://authenticator.cc/docs/en/debug-info). Reproduce the issue to make sure that the messages that we are looking for show up before you copy from the console.
