### ISSUE TITLE
extention show white screen

### ISSUE THREAD

**Issue by grobusus** [Authenticator-Extension/Authenticator#1013]
### Describe the issue

App won't start, shows white screen. I would be extremely grateful for any help or suggestion how to fix that
![image](https://user-images.githubusercontent.com/125675835/219693267-f852f626-d9ab-4604-b592-183568984818.png)

### Browser

Other

### Browser Version

12.03

### Extension Version

6.3.4

**Comment by mymindstorm** [comment]
Please follow [these steps](https://authenticator.cc/docs/en/debug-info).

**Comment by grobusus** [comment]
Thanks for the given answer, i cant start it. When i Go to about:debugging is said that version of browser does not match the versions of the workers. i note that when i start torbrouwser it shown version 12.0.3 

![image](https://user-images.githubusercontent.com/125675835/219788022-bc79338f-55f7-4db9-9660-5103cbf509bc.png)

**Comment by mymindstorm** [comment]
If you press inspect it should give us what we need. Although, tor is probably incompatible with our extension. I would recommend using Firefox directly instead.

**Comment by grobusus** [comment]
![image](https://user-images.githubusercontent.com/125675835/220026457-bf98d77d-f752-4d33-8767-4f11d4051827.png)
![image](https://user-images.githubusercontent.com/125675835/220026650-d8771625-475d-4fda-9719-63405cf445ed.png)
The application worked properly, I used the torus without complaints for around six months, hope we can fix it i has important 2fa here (

**Comment by Sneezry** [comment]
Please switch to Console tab to show error details

**Comment by grobusus** [comment]
![image](https://user-images.githubusercontent.com/125675835/220146849-5c870242-9e8d-4aae-a448-8a7325ee6978.png)

**Comment by mymindstorm** [comment]
You need to open the console, then reproduce the white screen, then send us the picture of that. There should be some text that appears showing the error in the console.

On Feb 20, 2023, at 9:30 AM, grobusus ***@***.***> wrote:

﻿

[image]<https://user-images.githubusercontent.com/125675835/220146849-5c870242-9e8d-4aae-a448-8a7325ee6978.png>

**Comment by Sneezry** [comment]
I noticed the console is for the generated background page. I suggest switching to the popup page to see more errors if there is still nothing when the issue presents. I find a discussion about inspecting the popup page in Mozilla's official forum: https://discourse.mozilla.org/t/how-can-i-inspect-the-popup-of-an-addon/34134/2

**Comment by mymindstorm** [comment]
@Sneezry in Firefox, it will show console for all pages when using the debugging inspector.

**Comment by grobusus** [comment]
Ok i open cansole then extention is what i see 
![image](https://user-images.githubusercontent.com/125675835/220660802-460e30a3-bf1d-4a2a-a3ba-3b8b6de3bbd5.png)

**Comment by mymindstorm** [comment]
Authenticator does not work because of an incompatibility between Firefox and Tor. Please use Firefox or Chromium instead of Tor.


-------- Original message --------
From: grobusus ***@***.***>
Date: 2/22/23 8:59 AM (GMT-06:00)
To: Authenticator-Extension/Authenticator ***@***.***>
Cc: Brendan Early ***@***.***>, Comment ***@***.***>
Subject: Re: [Authenticator-Extension/Authenticator] extention show white screen (Issue #1013)


Ok i open cansole then extention is what i see
[image]<https://user-images.githubusercontent.com/125675835/220660802-460e30a3-bf1d-4a2a-a3ba-3b8b6de3bbd5.png>

**Comment by grobusus** [comment]
Was used him for a long time in tor browser. btw i has important 2fa here from trade accounts so ilooking forward to solve problem cant just a switch browser. may is posible to rollback version of tor or enething else ?

**Comment by grobusus** [comment]
Сan it be possible to pack the extension as is along with the keys and install it in firefox?
I saw that installing an extension from a file is possible, can I get the desired file from the installed extension? sorry if i'm asking stupid things
