### ISSUE TITLE
Need to decrypt before restoring backup

### ISSUE THREAD

**Issue by Brianetta** [Authenticator-Extension/Authenticator#102]
When restoring a backup due to a forgotten master password, Authenticator refuses to allow this, and simply says, "You must provide correct password to import backups."

The work-around is to delete Authenticator from Chrome and reinstall it, so this is a relatively minor usability issue.

**Comment by Sneezry** [comment]
If we cannot decrypt all secrets with one password, we do not know with which password to encrypt imported data, so we simply refuse to import data if there is any secret cannot be decrypted with current password.

Maybe we need provide a way to make all secrets encrypted with a same password. I opened an issue to track this problem days ago: https://github.com/Authenticator-Extension/Authenticator/issues/79

So I will mark this issue as duplicate and close it. If you have different idea, please let me know, and I will reopen it if necessary.
