### ISSUE TITLE
Sort not working properly

### ISSUE THREAD

**Issue by adman2002** [Authenticator-Extension/Authenticator#1032]
### Describe the issue

Every time I try to sort non pinned, the sorting does not work as expected. For example, I will try and sort in a certain order, and as soon as I move something from the middle to the top, the top one moves to a seemingly random spot on the list, when it should be second.

### Browser

Chrome

### Browser Version

111.0.5563.65

### Extension Version

6.3.3

**Comment by Sneezry** [comment]
It's swap instead of sort
