### ISSUE TITLE
disableBackup doesn't work

### ISSUE THREAD

**Issue by RedDeer3** [Authenticator-Extension/Authenticator#1048]
### Describe the issue

Hello,

we are deploying this in an enterprise and using the policies outlined [here](https://authenticator.cc/docs/en/policy-config)

Edge has been configured here: Policies\Microsoft\Edge\3rdparty\extensions\ocglkepbibnalbgmbachknglpdipeoio\policy

The policies below are enabled:

Working:
passwordPolicy
passwordPolicyHint
enforcePassword
disableExport

Not Working
disableBackup

Set as "disableBackup"="1"

Policies are set with [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\ocglkepbibnalbgmbachknglpdipeoio\policy]

Thanks

### Browser

Edge

### Browser Version

Version 113.0.1774.3

### Extension Version

6.3.3.3

**Comment by Sneezry** [comment]
Hi RedDeer3, I have a quick test and everything works on my side:

Without disableBackup:

![image](https://github.com/Authenticator-Extension/Authenticator/assets/1621293/4cc15ef1-abd6-4262-a2bd-e66ca05b0eaa)

With disableBackup:

![image](https://github.com/Authenticator-Extension/Authenticator/assets/1621293/664580a9-b1bd-4067-ae20-5607cf0e0e39)

After setting disableBackup to 1, all backup download buttons are gone

**Comment by Sneezry** [comment]
@RedDeer3 thanks for the feedback! I can repro this issue on my side. A fix is on the way.

**Comment by Sneezry** [comment]
We've got a solution for the issue: a fixed release for it can be found at https://github.com/Authenticator-Extension/Authenticator/releases/tag/v6.3.5. However, there's a slight hiccup: Microsoft currently doesn't accept any MV2 extension packages for Edge, which means we're unable to release the fix to the Edge store just yet. We're working on the MV3, but it's still a work in progress. In the meantime, we've already rolled out the fixed version to CWS where it's currently undergoing review, without being automatically rejected for MV2 reasons.

If you're looking for immediate solutions, there are two viable options you can explore: Firstly, you can create your own package and distribute it to your employees if you want to bypass the Edge Store. Alternatively, patiently wait for the fixed version to be released on CWS and install the Chrome version in Edge as soon as it becomes available (see https://support.microsoft.com/en-us/microsoft-edge/add-turn-off-or-remove-extensions-in-microsoft-edge-9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026#ID0EDL).

We can't currently provide a target date for the MV3 version release for Edge, but it's worth knowing that you may wait for it. 

@mymindstorm consider the release of v6.3.5 for Firefox users and check if Mozilla isn't enforcing similar policies to Microsoft in respect of MV2 packages.

**Comment by RedDeer3** [comment]
Thanks for getting back to me so quickly with a solution. You've given a
couple of options which will work for us, I suspect we'll hold for the CWS
release if this isn't too far away.

Nice one 👍

**Comment by mymindstorm** [comment]
Firefox does not have v3 support yet, so I will push this later today.

**Comment by mymindstorm** [comment]
Firefox update awaiting review from Mozilla. It should be auto-approved within the next 24 hrs.

**Comment by Sneezry** [comment]
@RedDeer3 the fixed version 6.3.5 has been available in CWS: https://chrome.google.com/webstore/detail/authenticator/bhghoamapcdpbohphigoooaddinpkbai

**Comment by RedDeer3** [comment]
Excellent thanks for the rapid turnaround

**Comment by Sneezry** [comment]
I am closing this issue. However, if the issue still persists or if you have any other questions, please don't hesitate to open a new one.
