### ISSUE TITLE
Unable to decrypt all entries using new password encryption feature

### ISSUE THREAD

**Issue by garrington** [Authenticator-Extension/Authenticator#107]
One of the entries in my authenticator will not decrypt.  Enabling password encryption broke the apple script I am using to automate my VPN connections and I cannot disable it because I cannot decrypt this entry.  I also tried removing the entry and it will not remove from my authenticator.  No errors indicated when trying to remove, it simply will not go away.

Version is 5.0.8
Browser: Chrome
OS: MacOS Sierra 10.12.6

**Comment by Sneezry** [comment]
Open popup page, right click and select inspect, switch to console tab, run code below:

```
chrome.storage.sync.get(d=>console.log(JSON.stringify(d,null,2)))
```

You can see all your data, backup it. (**Danger! Ensure you have backup all data. This action cannot be undone**) Reinstall the extension, open import page (settings -> Export / Import -> Import Backup), switch to Import Text Backup tab, paste the backup into the text area, check Encrypted if your backup is encrypted and input password, then click Import Text Backup button.

**Comment by garrington** [comment]
That resolved my issue.  Thanks!
