### ISSUE TITLE
Preferences doesn't get saved on firefox private mode

### ISSUE THREAD

**Issue by syrupderg** [Authenticator-Extension/Authenticator#1085]
### Describe the issue

If i make any changes to preferences it doesn't gets saved on firefox but this doesn't occur on other browsers. 

### Browser

Firefox

### Browser Version

115.0.2

### Extension Version

6.3.5

**Comment by Sneezry** [comment]
That behavior is intentional and part of the browser's design. Private mode ensures that your browsing activity does not leave any traces behind. Any data, such as cookies, local storage or browsing history, that is saved during Private mode will automatically be removed once the window is closed.

**Comment by syrupderg** [comment]
> That behavior is intentional and part of the browser's design. Private mode ensures that your browsing activity does not leave any traces behind. Any data, such as cookies, local storage or browsing history, that is saved during Private mode will automatically be removed once the window is closed.

This bug doesnt happens on brave or any other browser i tried with. ublock still keeps the preferences i do but authenticator doesnt on firefox. this might be different on other operating systems, im using endeavour os (arch).

**Comment by mymindstorm** [comment]
Do you have Firefox set to clear browsing data on close? There is a bug in Firefox which causes this to happen if that setting is enabled.
