### ISSUE TITLE
button "Download backup copy"

### ISSUE THREAD

**Issue by 32xxl** [Authenticator-Extension/Authenticator#110]
Hi,

My Authenticator was updated to v 5.0.8 in my Google Chrome 65.0.3325.181 (64 bit)

After that, in menu Options->Export/Import button "Download backup copy"  not works. 

Any solutions? 

Thank you

**Comment by mymindstorm** [comment]
We have a fix made for the export button and will release with update soon, for now you will need to right click the "Download Backup File" button and click "Save as...". See #99
