### ISSUE TITLE
Make browser account sync optional

### ISSUE THREAD

**Issue by olfek** [Authenticator-Extension/Authenticator#1110]
### Describe the issue

Some people, like myself for example, may not want to sync data with the browser account.

### Browser

Firefox

### Browser Version

117.0.1 (64-bit)

### Extension Version

6.3.5

**Comment by mymindstorm** [comment]
Switch storage to local in settings and it will not sync.

**Comment by olfek** [comment]
@mymindstorm is it local by default?

**Comment by olfek** [comment]
just checked, doesn't look like it, I think browser sync should be off by default
