### ISSUE TITLE
Search bur missing

### ISSUE THREAD

**Issue by PedroPTavaresJr** [Authenticator-Extension/Authenticator#1150]
#### Description
The search bar is not being displayed after activating the "Smart Filter" option.

#### How o repilcate:
1- Go to Settings and deactivate Smart Filter
1.1-As expected the search bar will be hidden on the authentications page
2- Go back to Preferences and reactivate Smart Filter
2.1- The search bar will not be available on the autehntications page.
![Screenshot 2024-01-30 100711](https://github.com/Authenticator-Extension/Authenticator/assets/42211176/e331c536-9b4f-4fdb-8d48-c2be7579162d)
![Screenshot 2024-01-30 100828](https://github.com/Authenticator-Extension/Authenticator/assets/42211176/0b7a80ab-c64d-4a7c-a043-6de942bca4a0)

### Browser

Chrome

### Browser Version

Version 121.0.6167.86 (Official Build) (64-bit)

### Extension Version

6.3.5

**Comment by mymindstorm** [comment]
Search bar automatically shows if you have a certain number of accounts. You can manually make it show by pressing `/` on your keyboard.
