### ISSUE TITLE
Importation from Google Authenticator Android App

### ISSUE THREAD

**Issue by rcoscali** [Authenticator-Extension/Authenticator#116]
Hi some time ago (november 2017) I asked about importation format. I finally had time for coding this and it runs ok. It allows to extract entries from the android App DB and provide them in several format (in browser allowing to scan with your extension, in a json file using the import format you provided, but also in terminal, png, svg etc). Of course it require having rooted phone for getting the db file, hence this script is mainly for developpers. I started modifying the Google App code for sending the JSON to chrome (as phone2chrome and chrome2phone old apps use to do it). It could be easier to use for standard users. However thanks for the format ;-)

https://github.com/rcoscali/googleauth_db2qr

**Comment by Sneezry** [comment]
Nice work!

**Comment by Sneezry** [comment]
@mymindstorm Can we add this to our wiki?

**Comment by mymindstorm** [comment]
Sure

@rcoscali does running `googleauth_db2qr google-authenticator2.db` generate the JSON file or does it need any additional arguments?

**Comment by mymindstorm** [comment]
@rcoscali I can't root my phone to test the commands needed to generate the JSON file, so if you could answer my previous question that would really be appreciated.
