### ISSUE TITLE
Where are the data files stored if not in Extensions folder?

### ISSUE THREAD

**Issue by jamiekarvans** [Authenticator-Extension/Authenticator#1160]
### Describe the issue

hey i have no access to the extension for some reason it crashes in just 1 second when i open it, but all my keys are there but i don't get the time to backup the codes from the extension app,
i've tried to copy the files from the Local Extension folder in chrome to another system but it's blank and codes don't show up
so if the files are not stored in folder where are they?

### Browser

Chrome

### Browser Version

latest

### Extension Version

latest

**Comment by Sneezry** [comment]
It should be in %UserProfile%\Local Settings\Application Data\Google\Chrome\User Data\Default for Windows. However, it's out of our support scope. Take actions at your own risk.

**Comment by jamiekarvans** [comment]
I have already explained, those files do not recover and there is no keys
stored in them
And by moving the files to another system it does not show the codes,
infact it's empty
So the actual files are stored somewhere else.

**Comment by Sneezry** [comment]
They are stored in Database with encryption with your Windows credential. You cannot copy the data to another machine to restore data. It's Chrome's behavior, not the extension's. Please contact Google for further support. To the Authenticator extension, we only support to recover data from exported backup files from the extension.
