### ISSUE TITLE
I lost 2FA authenticator data when my pc got hacked and browser got crashed after hacking so i lost authenticator extension

### ISSUE THREAD

**Issue by Gajanandmotors** [Authenticator-Extension/Authenticator#1162]
### Describe the issue

Kindly help me to recover our facebook account as my pc got hacked and it all corrupted my browser and i lost my extension, kindly help me to recover my account, I have installed authenticator extension for facebook login but after that i was not able to login without verification code, facebook support are helpless so anyone from the authenticator.cc team member able to help, it would be great help,

### Browser

Chrome

### Browser Version

122.0.6261.95

### Extension Version

6.3.6

**Comment by keytrap-x86** [comment]
You should be able to recover your account with your phone number.

**Comment by mymindstorm** [comment]
https://authenticator.cc/docs/en/lost-codes
