### ISSUE TITLE
Which data are collected when using Authenticator.cc

### ISSUE THREAD

**Issue by aliceengrand** [Authenticator-Extension/Authenticator#1164]
### Discussed in https://github.com/Authenticator-Extension/Authenticator/discussions/1163

<div type='discussions-op-text'>

<sup>Originally posted by **aliceengrand** February 29, 2024</sup>
Hi, 
Do you have any idea of which information the Authenticator.cc can grab from us when using his extension ? Is it the visited website ? Is it our username to login (actually this is our email address) ? Other ?
Many thanks,
Alice</div>

**Comment by Sneezry** [comment]
We have moved this issue to discussion. Please see https://github.com/Authenticator-Extension/Authenticator/discussions/1163
