### ISSUE TITLE
Unrecognized QR code when scanning

### ISSUE THREAD

**Issue by multiwebinc** [Authenticator-Extension/Authenticator#118]
I used https://github.com/Bacon/BaconQrCode to generate QR codes for my app. Here is an example output:

![qr-bug](https://user-images.githubusercontent.com/901732/38602308-9d811622-3d27-11e8-9a09-aacaa07df014.png)

Authenticator says "Unrecognized QR code." when I try to scan it, however using Google Authenticator app to scan the code works fine. I can also decode it using https://zxing.org/w/decode.jspx and it says the parsed result is:

```
otpauth://totp/Google%3Aexample%40gmail.com?secret=qjv3en5jjjhgq4pk3m6e576ymwuc5d4x&issuer=Google
```

This looks valid to me.

In fact, when I take the above URL and put it into https://www.qr-code-generator.com/ and then scan the output QR code with Authenticator, it works! There's something about the above QR code that's not working with Authenticator for some reason.

**Comment by mymindstorm** [comment]
Text is valid, it seems to be either a problem with jsqrcode (what we use to scan QR codes) or with BaconQrCode. The only decoder I can get to work is zxing's. It looks like the code you generated is using weird encoding which is tripping up the decoder. Try generating with ISO 8859-1 and see if that works better.

**Comment by multiwebinc** [comment]
@mymindstorm Thank you for looking into this. Manually setting to "ISO-8859-1" works and I'm able to scan it with this extension. However, I was actually encoding with utf-8 (which is the default for antonioribeiro/google2fa-laravel for some reason). I'm not sure how you determined the encoding above. So it could be a problem with the BaconQrCode not correctly rendering if it uses utf-8 encoding.

**Comment by mymindstorm** [comment]
ISO-8859-1 is the encoding originally used in the QR spec, I thought it would be supported by decoder by default and used it narrow down the problem. The code above has its ECI mode set to 7 (for ISO 8859-5 apparently) which makes the reader freak out and throw an error since it doesn't seem to support that. If you can find a way to just make BaconQrCode stop setting the ECI data it should be able to process it just fine. 

[Here ](https://strokescribe.com/en/ECI.html)is the table I found on ECI codes for reference (shouldn't UTF-8 should be 26?)

https://github.com/LazarSoft/jsqrcode/issues/33 has a workaround that we can try, I'll test that later and see if it works

**Comment by multiwebinc** [comment]
Are you sure the ECI mode is set to 7? According to https://online-barcode-reader.inliteresearch.com/, the above QR code uses UTF-8 character set, which also coincides with what was requested during QR generation, not ECI mode 7 (which would be ISO/IEC 8859-5).

Also, looking at the [code for BaconQrCode](https://github.com/Bacon/BaconQrCode/blob/master/src/BaconQrCode/Common/CharacterSetEci.php) it looks like they have taken these various encodings into account, so it would seem likely that the error is *not* with that package but instead with jsqrcode. Unfortunately it looks like jsqrcode is no longer being maintained.

**Comment by mymindstorm** [comment]
[This reader](http://qrlogo.kaarposoft.dk/qrdecode.html) and the error I'm getting from jsqrcode, `
Invalid mode: 7 in (block:0 bit:3)`, seem to say that it's in ECI mode 7. According to the code you have it should be 26, so jsqrcode may just be reading the ECI data wrong.

That patch I found seems to work just fine. It should work with 5.0.10
