### ISSUE TITLE
authenticator.cc extension deployment

### ISSUE THREAD

**Issue by chetan8181** [Authenticator-Extension/Authenticator#1189]
I am trying to deploy authenticator.cc extension silently using google admin console but once installation done remotely it will automatically open chrome issue warning page. https://authenticator.cc/docs/en/chrome-issues is there any way we can stop this redirection upon installation?

**Comment by Sneezry** [comment]
Set `disableInstallHelp` to `true`.

See https://authenticator.cc/docs/en/policy-config

**Comment by drolleman-applyboard** [comment]
I deployed and configured the authenticator.cc myself in the Google admin console and disableInstallHelp policy is the only one that seems to be tripping me up.
Its set to true but it will still redirect once installed.

Other policies work fine. I'm probably using most of them.

**Comment by mymindstorm** [comment]
Could you send a screenshot of `chrome://policy` on a configured device?

**Comment by drolleman-applyboard** [comment]
I have included the screenshot.
![Screenshot 2024-05-14 142246](https://github.com/Authenticator-Extension/Authenticator/assets/65169934/40b2bf8d-5ba5-4b4b-87c1-5d2726941162)

**Comment by Sneezry** [comment]
does this help? https://github.com/Authenticator-Extension/Authenticator/issues/1015#issuecomment-1439809591

**Comment by drolleman-applyboard** [comment]
@Sneezry I'll do some testing and get back to you.
The other Boolean attributes appears to be working. I will change the disableInstallHelp to 1/0 and validate the results.
Below is the policy for extension
```
{
    "enforcePassword": {
        "Value": true
    },
    "disableExport": {
        "Value": true
    },
    "disableBackup": {
        "Value": true
    },
    "enforceAutolock": {
        "Value": 15
    },
    "passwordPolicy": {
        "Value": "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*(_|[^\\w])).{8,20}$"
    },
    "passwordPolicyHint": {
        "Value": "Your Password does not meet requirements"
    },
    "disableInstallHelp": {
        "Value": true
    },
    "feedbackURL": {
        "Value": "https://mypage.com"
    }
}
```

**Comment by chetan8181** [comment]
Dear All,

Thank you for looking into this, Issue has been resolved.

Thanks
Chetan

**Comment by mymindstorm** [comment]
What fixed the problem?

**Comment by drolleman-applyboard** [comment]
I did some testing, unfortunately I was able to reproduce once.
However the setting only accepts true/false. If I try to set it to 1/0 the settings completely disappears from chrome://policy.
