### ISSUE TITLE
Open support link on extension first run / install

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#12]
https://github.com/Authenticator-Extension/Authenticator/commit/23e50abd7657add17a5225af2c64835853cacf8f#diff-f91f6f0a2ea2d1a98a57fa85b3672ba8L163

**Comment by mymindstorm** [comment]
Either open it to wiki/Chrome-Issues or we could make a wiki/Chrome-welcome page, if there isn't a simple way to differentiate between chrome and firefox you can use [getManifest](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/getManifest)

**Comment by Sneezry** [comment]
fixed in https://github.com/Authenticator-Extension/Authenticator/commit/b8a216f64d76c799cf9643a0fcca46d5d073df95
