### ISSUE TITLE
The problem with google autotentikator

### ISSUE THREAD

**Issue by Alexvs07** [Authenticator-Extension/Authenticator#120]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

Hello. The problem with google autotentikator.
 For no apparent reason, codes in the drop-down box of the authenticator in Google Chrome on the laptop ceased to appear. The window drops out, it's empty inside. help me please

**Comment by mymindstorm** [comment]
Is the window all white or can you still add codes and access the menu?

**Comment by Alexvs07** [comment]
Totally white. Nothing.

**Comment by mymindstorm** [comment]
Can you follow [these steps](https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information) and paste any messages here?

**Comment by Alexvs07** [comment]
I have a Google Chrome browser

**Comment by Alexvs07** [comment]
![2018-04-02 12-52-32 developer tools - chrome-extension bhghoamapcdpbohphigoooaddinpkbai view popup html](https://user-images.githubusercontent.com/35767218/38756007-99bd191e-3f70-11e8-98c4-bf0f095e755b.png)

**Comment by mymindstorm** [comment]
At the bottom paste this and press enter:
```javascript
chrome.storage.sync.get(d=>{for(const k of Object.keys(d)){if(d[k].secret){d[k].secret='REDACTED'}}console.log(JSON.stringify(d,null,2))})
```
Does it make an error or does it list your accounts? (you only have to paste anything if it makes error)

**Comment by Alexvs07** [comment]
Here's what happened
![2018-04-15 08-40-33 developer tools - chrome-extension bhghoamapcdpbohphigoooaddinpkbai view popup html](https://user-images.githubusercontent.com/35767218/38775361-5c260ef2-4089-11e8-8467-d9bf7bc5b169.png)

**Comment by mymindstorm** [comment]
- Did you have any data in Authenticator before this happened?
- Is your disk low on space?
- Is Chrome up to date?
- Try running Chrome as administrator and see if it is still white

**Comment by Alexvs07** [comment]
1.Autencifikator generated codes for 5-6 sites, including for exchanges.
2.Disk C - free 17 GB, drive D - free 202 GB.
3.In the settings "About the browser Chrome" writes "
The latest version of Google Chrome is already installed
Version 65.0.3325.181 (Official build), (32 bit) ".
4. I run Google Chrome on behalf of the administrator.

**Comment by Alexvs07** [comment]
Nothing changed

**Comment by mymindstorm** [comment]
There isn't much info on this Chrome error. From what I can tell somehow the file Chrome was using to store your extension data got corrupted or another program is blocking chrome from accessing it. 

The folder Chrome needs to access is:
```
%LOCALAPPDATA%\Google\Chrome\User Data\Default\Sync Extension Settings\bhghoamapcdpbohphigoooaddinpkbai
```

Note that this may be a bit off since this directory is platform specific, look [here](https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md) if you can't find the user data directory.

- In that directory there should be a file named `LOG` that may shed some light on the issue
- Did anything change on your pc before this started happening? (E.g. Windows update or program installs)
- [Check disk integrity](https://support.microsoft.com/en-us/help/2641432/check-your-hard-disk-for-errors-in-windows-7)

**Comment by Alexvs07** [comment]
Maybe this happened after I deleted the backup files on the disk with CCleaner? Maybe this can be somehow corrected? If I update or reinstall my Authenticator, it will not recover? Or is everything lost?
![2018-04-20 07-34-28 bhghoamapcdpbohphigoooaddinpkbai](https://user-images.githubusercontent.com/35767218/39031458-ed954dcc-4470-11e8-9725-54bdf36c287c.png)

**Comment by mymindstorm** [comment]
I've removed the second image, as it contains some of your account data. *Please read all instructions before continuing.*

---

1. For every account you had there will be a  pair of brackets starting with this `{` and ending with this `}`. Copy anything inside any brackets you find to a safe place.

Every pair is one of your accounts. The parts you need are the values for `"secret":` and `"account":`.

2. Save the values for all of your accounts somewhere safe.
3. *Make sure that you have the secrets for all the accounts you need*

If you can't find certain accounts check other files in that folder just in case.

4. Reinstall Authenticator to clear its data. **Make sure you have everything you need before you do this**
5. After opening it again add a code using the "Manual Entry" button. Paste the value for `"secret":` **without quotes** for one of your accounts. Likewise, name the account using the `"account":` value that was in the same pair of brackets.

For example let's say this is one of your lost accounts that you got from the log files:

```
{"account":"Google","hash":"22e991a1711a51f8aab522081666b5d3","issuer":"","secret":"A3MUFPMUQTCNVAAODBRONWFL3KLOFPSK","type":"totp","encrypted":false,"index":0,"counter":0}
```

You should paste `Google` into the `Account Name` field and `A3MUFPMUQTCNVAAODBRONWFL3KLOFPSK` into the `Secret` field. Repeat step 5 as needed.

**Comment by Alexvs07** [comment]
Thank you very much. I will sort this out

**Comment by Alexvs07** [comment]
I could not get. I deleted the Authenticator and loaded it again, but the console again found the same errors. I cleaned the console, manually entered the expression in the siblings {---} with my accounts, pressed Enter, the text was duplicated and nothing happened. Please tell me where the error is. If it does not complicate you, please elaborate on what I need to do.

**Comment by mymindstorm** [comment]
Be careful about what you enter into the console, it could potentially make things worse. To reiterate, make sure you have a backup of everything you need before continuing with any of this.
- Have you tried deleting the folder with the log?
- Try reinstalling Chrome

Alternatively, we could try using the [Firefox version](https://addons.mozilla.org/en-US/firefox/addon/auth-helper/) or another app altogether now that we have your data.

**Comment by Alexvs07** [comment]
Do you need to delete the folder with the log?

**Comment by mymindstorm** [comment]
Yes, it might help if Chrome re-creates it.

**Comment by Alexvs07** [comment]
000003.log -это она?
![2018-04-20 07-34-28 bhghoamapcdpbohphigoooaddinpkbai](https://user-images.githubusercontent.com/35767218/39087979-b0ce38f2-45b2-11e8-9c8e-206f222dd3d4.png)

**Comment by mymindstorm** [comment]
No, the folder named `bhghoamapcdpbohphigoooaddinpkbai`. Make a copy of the folder somewhere safe before deleting it.

**Comment by Alexvs07** [comment]
Thank you for your support. At me all has turned out.

**Comment by mymindstorm** [comment]
Are you trying to say that it works again?

**Comment by Alexvs07** [comment]
Yes, it works as before
