### ISSUE TITLE
Licenses page is not built correctly

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#1201]
### Describe the issue

3rd party lib license is missing

![image](https://github.com/Authenticator-Extension/Authenticator/assets/1621293/13164aac-5c2b-406a-bf9e-ccb22991d977)

### Browser

Chrome

### Browser Version

125.0.6422.142

### Extension Version

7.0.0

**Comment by Sneezry** [comment]
https://github.com/mymindstorm/npm-license-generator/pull/28

**Comment by Sneezry** [comment]
@mymindstorm we need the fix in the next release

**Comment by mymindstorm** [comment]
@Sneezry will do. I will try to get this fixed by Sunday.
