### ISSUE TITLE
Cannot copy code by clicking on it

### ISSUE THREAD

**Issue by stepshep** [Authenticator-Extension/Authenticator#1203]
### Describe the issue

Hi,

When using Chrome and on a "new tab" page I am unable to use the click-to-copy functionality. If I navigate to any URL, clicking on the code once again allows it to copy to my clipboard. Here is the error from the console debug when on a new tab page:

EntryComponent.vue:29 Uncaught (in promise) Error: Cannot access a chrome:// URL
Promise.then (async)
c @ EntryComponent.vue:29
(anonymous) @ EntryComponent.vue:29
Ya @ EntryComponent.vue:29
(anonymous) @ EntryComponent.vue:128

Thanks

### Browser

Chrome

### Browser Version

125.0.6422.142, 126.0.6478.115

### Extension Version

7.0.0

**Comment by keytrap-x86** [comment]
Could you make a little Gif with [Screen2Gif](https://www.screentogif.com/) for example ? It'll be easier to understand. I cannot reproduce your problem.


![Animation](https://github.com/Authenticator-Extension/Authenticator/assets/17864005/70d32e72-e6d9-4fed-a207-71a1126d3c03)

**Comment by stepshep** [comment]
![2024-06-21_09-44-03](https://github.com/Authenticator-Extension/Authenticator/assets/6633985/f110c76a-7541-4b91-9440-93c0d43ba3bd)

**Comment by keytrap-x86** [comment]
Do you have the lastest version ?
![image](https://github.com/Authenticator-Extension/Authenticator/assets/17864005/48ca5573-f22e-48d8-be75-e86dd99dafde)

**Comment by stepshep** [comment]
7.0.0

![image](https://github.com/Authenticator-Extension/Authenticator/assets/6633985/f902d86a-8bd5-41ed-8a8a-a1d963872a9b)
