### ISSUE TITLE
why i can not import QR picture from Google authenticator

### ISSUE THREAD

**Issue by shavadawa** [Authenticator-Extension/Authenticator#1211]
### Describe the issue

why I can not import QR picture from Google authenticator.  I try the Authenticator-Extension from both of edge store and chrome store  , all do not work . it show the  error  -> '无法识别的QR码' trans to English 'Unrecognized QR code'

### Browser

Edge

### Browser Version

125.0.2535.92

### Extension Version

7.0

**Comment by Sneezry** [comment]
从 Google Authenticator 里导出的 QR 码里包含了几个账号呢？建议一次只导出 5 个试试。

**Comment by shavadawa** [comment]
> 从 Google Authenticator 里导出的 QR 码里包含了几个账号呢？建议一次只导出 5 个试试。

还真行啊 解决了
