### ISSUE TITLE
Chrome Issues

### ISSUE THREAD

**Issue by narisoa10** [Authenticator-Extension/Authenticator#1228]
### Describe the issue

REINSTALLING AUTHENTICATOR WILL CLEAR YOUR DATA. NEVER REINSTALL AUTHENTICATOR TO FIX ANY ISSUES
![1](https://github.com/Authenticator-Extension/Authenticator/assets/174806200/50cdc0a6-f509-4ceb-8dd6-e95af30c2973)

### Browser

Chrome

### Browser Version

Версия 126.0.6478.127 (Официальная сборка), (64 бит)

### Extension Version

нету

**Comment by Sneezry** [comment]
This is as designed. This page serves as a reminder: never reinstall the extension to resolve any issues, as this can result in data loss.
