### ISSUE TITLE
Addon installation in MS Edge blocked (by outdated manifest?)

### ISSUE THREAD

**Issue by cherhaus** [Authenticator-Extension/Authenticator#1240]
### Describe the issue

Installation is blocked in Edge, message "Your admin has blocked "Authenticator: 2FA Client". Explanation by our admins:  

"Due to an update by Chrome and Edge, Manifestv2 Extensions are not working anymore, because it won't be supported. In the future only Extensions that are Manifestv3 will still work.

Since this is a change in the Browser, the only thing that you can do is to contact the developer of the Extension to ask if they are working on the manifestv3 support."

To be checked if this is indeed the reason for the installation being blocked.

### Browser

MS Edge

### Browser Version

MS Edge 126.0.2592.113 64-bit

### Extension Version

Not available (installation blocked)

**Comment by Sneezry** [comment]
We plan to release MV3 for Edge around mid-August. In the meantime, you can install the Chrome version on Edge as a workaround.

**Comment by mymindstorm** [comment]
I am trying to submit v7.0.0 which should resolve this, but I am running into an error in Microsoft's system. I have filed a bug report with them to resolve.

**Comment by mymindstorm** [comment]
https://github.com/microsoft/MicrosoftEdge-Extensions/issues/176

**Comment by mymindstorm** [comment]
I just uploaded a version that should fix this to Microsoft. This should be resolved as soon as they approve the update.
