### ISSUE TITLE
Unable to use Authenticator, it cannot display

### ISSUE THREAD

**Issue by Mxmblee** [Authenticator-Extension/Authenticator#1247]
### Describe the issue

When I try to open it, it only displays a white background and nothing else, just like this
![1d2a05b6200d79d1fb5beccd68106744](https://github.com/user-attachments/assets/c5b920e0-f5a5-439d-9f16-c7295d36fb51)

### Browser

Edge

### Browser Version

128.0.2708.0 dev

### Extension Version

6.3.3

**Comment by mymindstorm** [comment]
Could you follow the chrome directions in [these steps](https://authenticator.cc/docs/en/debug-info)?

**Comment by Mxmblee** [comment]
> Could you follow the chrome directions in [these steps](https://authenticator.cc/docs/en/debug-info)?

I am unable to proceed to the second step as I cannot find 'Inspect' when I right-click

**Comment by eternalphane** [comment]
> Could you follow the chrome directions in [these steps](https://authenticator.cc/docs/en/debug-info)?

Elements:
![image](https://github.com/user-attachments/assets/2a66fa74-bbb1-4f65-8ccf-627d706ca636)
Console:
![image](https://github.com/user-attachments/assets/19d1445d-1a96-4fa9-9455-8cc4ceb825ef)
Network:
![image](https://github.com/user-attachments/assets/5aad4458-ff4e-4d00-aa42-ff76a19490b6)

**Comment by Mxmblee** [comment]
> > Could you follow the chrome directions in [these steps](https://authenticator.cc/docs/en/debug-info)?
> 
> Elements: ![图像](https://private-user-images.githubusercontent.com/11267872/354631722-2a66fa74-bbb1-4f65-8ccf-627d706ca636.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjI4NzEsIm5iZiI6MTcyMjY2MjU3MSwicGF0aCI6Ii8xMTI2Nzg3Mi8zNTQ2MzE3MjItMmE2NmZhNzQtYmJiMS00ZjY1LThjY2YtNjI3ZDcwNmNhNjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA1MjI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5N2ZiM2MwMzg2NzJhNzU0ZDZhMjc2M2E1NDAyN2M1OTU5YTI0MjBkNzk5ZGE5ZDc1NmQzYjVlMWU5NmM1YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gHzezpLOrXyAJ5HRKYcOsVmOY1JdQUtcGSQT4ZsJuvI) Console: ![图像](https://private-user-images.githubusercontent.com/11267872/354631899-19d1445d-1a96-4fa9-9455-8cc4ceb825ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjI4NzEsIm5iZiI6MTcyMjY2MjU3MSwicGF0aCI6Ii8xMTI2Nzg3Mi8zNTQ2MzE4OTktMTlkMTQ0NWQtMWE5Ni00ZmE5LTk0NTUtOGNjNGNlYjgyNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA1MjI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZTlmOWQ0OGU1OGViNTY0MGQ4YjNjNzZmNWY2ODdjYmI1ZWRiZTA3NGRhZDEyOGJkMzk2ZTlmMTQxYmE4NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nD2stxGkkxVfQwEnoZYu9JvE9mCGrTpFH-vMcuoWbo4) Network: ![image](https://private-user-images.githubusercontent.com/11267872/354631911-5aad4458-ff4e-4d00-aa42-ff76a19490b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjI4NzEsIm5iZiI6MTcyMjY2MjU3MSwicGF0aCI6Ii8xMTI2Nzg3Mi8zNTQ2MzE5MTEtNWFhZDQ0NTgtZmY0ZS00ZDAwLWFhNDItZmY3NmExOTQ5MGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA1MjI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwOTViOGQ3NGIzMjk4OTM4MmI2NzhjYmM4NmJjZTdkZTY3ZTAxZTIzZmUwYjgzOGQwYzZkYWYwODcxYmQ5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nk-0Iaz_3n9ejfT9ryMtVxK8B6_SwgVm3Tb0zzL_-nQ)

What do I need to do, compare all the content?

**Comment by Mxmblee** [comment]
> commented

Just now, someone commented that this gave me inspiration. I have discovered a problem, what do I need to do now

![b8e1538e61b5721d61283c3bc0434609](https://github.com/user-attachments/assets/d169a098-68da-4c8e-a37c-5a28aa58db76)

**Comment by sabruss** [comment]
Hi i got the same, blank page displayed and no error in console, tested with 7.0.0

I'm running on edge canary Version 129.0.2754.0

Edit:

After somes debug it seem it's caused by ManagedStorage that hang on chrome.storage.managed.get

**Comment by mymindstorm** [comment]
I am unable to reproduce on edge 128.0.2739.5 (Official build) dev (64-bit) with either the published version or what's currently on our development branch. @sabruss if what you are seeing is the source of the bug, this would be an issue with Edge itself. Could y'all submit bug reports to Microsoft via `Alt + Shift + I` with diagnostic data included? 

As a workaround, you can right click -> inspect -> console -> paste in `chrome.storage.sync.get(e=>console.log(e))` -> 'copy object'. Paste your clipboard into the "Import Text Backup" screen in a browser with the working extension.

![image](https://github.com/user-attachments/assets/94c7fe3b-e0a4-4444-a3eb-3c9a8d352652)

![image](https://github.com/user-attachments/assets/95ea2321-c8a5-45bc-a9fe-f276dc6a670a)

**Comment by RichyRicho1** [comment]
Having the same issue in Edge Version 128.0.2739.9 (Official build) stable app, beta channel (64-bit). 
I am able to export the data and reimport, but after reimport and browser restart, the issue re-occurs. 
I have imported to Chrome for now, and don't seem to be having the issue. 
I have also reported the error via alt + shirt + i .

**Comment by eternalphane** [comment]
> After somes debug it seem it's caused by ManagedStorage that hang on chrome.storage.managed.get

Can we add a timeout to `chrome.storage.managed.get()` to avoid it hanging indefinitely?

**Comment by mymindstorm** [comment]
Hey all, thanks for reporting the issue to Microsoft via the edge ui. They reached out to us and have escalated managed storage get hanging to their internal engineering team. 

While we would add a timeout, currently the Microsoft edge partner center is broken and we are unable to issue an update to that version. We do have an impending release within the next week or two and may be able to get a timeout added to the Chrome version.

**Comment by mymindstorm** [comment]
@sabruss @eternalphane could y'all confirm if the attached build fixes the issue? It adds a timeout to managed storage.

1. Download [authenticator-1256.zip](https://github.com/user-attachments/files/16633232/authenticator-1256.zip)
2. Unzip into a new folder
3. Go to `edge://extensions/`
4. Turn on "Developer mode"
5. Click "Load unpacked" and select the directory with the unzipped extension

**Comment by mymindstorm** [comment]
Slight correction, here's a version with a much lower timeout. The original file takes so long it appears to still be broken.

[authenticator-1256-v2.zip](https://github.com/user-attachments/files/16633286/authenticator-1256-v2.zip)

**Comment by eternalphane** [comment]
@mymindstorm I just checked the patched version and it seems working for me.

**Comment by mymindstorm** [comment]
Thanks @eternalphane !

**Comment by mymindstorm** [comment]
Uploaded a version with the fix to the Edge extension store. This will be working again as soon as MSFT approves the update or fixes the bug in Edge.
