### ISSUE TITLE
Google Authenticator QR code not recognized

### ISSUE THREAD

**Issue by xlwindlx** [Authenticator-Extension/Authenticator#1254]
### Describe the issue

After backing up the QR code of Google Authenticator as an image file and importing the QR code in Chrome Authenticator Extension, only a pop-up message "Unrecognized QR code" appears and the import is not possible.

### Browser

Chrome

### Browser Version

127.0.6533.100 (arm64)

### Extension Version

7.0.0

**Comment by Sneezry** [comment]
Google Authenticator supports exporting up to 10 accounts at one time. However, when importing to Authenticator Extension it is recommended to export five accounts at one time to prevent errors.

**Comment by xlwindlx** [comment]
@Sneezry  exported 5 accounts at a time from Google Authenticator using the method you provided, and it was imported normally. Thank you.
