### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by Kingsleyrhema** [Authenticator-Extension/Authenticator#1257]
### Describe the issue

I have been using authenticator for a couple of weeks now, but suddenly, sometime last week it got blank,
fortunately for me I exported my security keys, so I tired reinstalling it, rebooting my PC, but the problem still persists.

### Browser

Edge

### Browser Version

128.0.2739.22

### Extension Version

6.3.3

**Comment by DhulipallaGopi** [comment]
ok

**Comment by Sneezry** [comment]
Microsoft engineers have confirmed this issue is only active for Beta, Dev, & Canary channels and is not active for stable. They are working on a fix.

**Comment by mymindstorm** [comment]
I just uploaded a version with a workaround to the Edge store. This will be resolved when Microsoft fixes the bug or approves our update. 

Duplicate of #1247
