### ISSUE TITLE
Cannot set toolbar hotkey

### ISSUE THREAD

**Issue by DivineMK** [Authenticator-Extension/Authenticator#1274]
### Describe the issue

I tried setting toolbar hotkey but it no longer works. Same hotkeys works for other addons. This applies to all functions (Activate toolbar, Scan QR, Autofill).

### Browser

Firefox

### Browser Version

129.0

### Extension Version

8.0.0

**Comment by rubcap** [comment]
Same here. Since version 8.0.0 of the add-on got installed in Firefox 129.0, I cannot longer set or use the hotkeys. Hotkeys used by other add-ons are still working fine.

Without the hotkeys working, it has become less convenient to quickly open the toolbar menu and copy the secret/code.

**Comment by yermulnik** [comment]
Same here. Linux (Ubuntu), FF 129.0.2, Authenticator 8.0.0.
Chrome — no issues with extension shortcut.
