### ISSUE TITLE
It no longer displays in one-on-one

### ISSUE THREAD

**Issue by masked-shizuma** [Authenticator-Extension/Authenticator#1280]
### Describe the issue

Hello,
I apologize for my poor English.
Previously, when logging into a site registered with the Authenticator, only the corresponding authentication code was displayed. 
However, in the latest version, performing the same operation shows the authentication codes for all registered sites. 
Please fix it so that the codes are displayed one-on-one as before.
Thank you.

### Browser

Firefox

### Browser Version

129.0.2

### Extension Version

8.0.0

**Comment by mymindstorm** [comment]
We moved it behind an option with 8.0.0. Turn on "Smart Filter"

![image](https://github.com/user-attachments/assets/562bda27-ee44-4e92-9d69-1b117e76d263)
