### ISSUE TITLE
Listing the relevant codes based on the current site doesn't seem to work anymore

### ISSUE THREAD

**Issue by jooname** [Authenticator-Extension/Authenticator#1293]
### Describe the issue

Alongside https://github.com/Authenticator-Extension/Authenticator/issues/1262 (which has been resolved in 8.0.1) I did notice one other issue, but this wasn't so severe that I cared to write a bug report about it. But now that I've had to live with the issue for a bit, I do miss when this worked.

**Problem**: 

When you open the browser extension, it doesn't list the codes most matching the currently open site.

**Expected result**: 

When you open the browser extension, it lists the codes most matching the currently open site. So if I was filling in 2FA for my Google account, opening the browser extension should suggest me the Google account 2FA (provided it can be identified) and not require me to search for it. If there were no codes that would match, I think it used to list everything.

**Steps to replicate**:

1. Configure a code to be generated in the browser extension, include for example the site address or domain name in "Issuer" field
2. Access the page where that code is relevant
3. Open the browser extension
4. You get unfiltered list of codes instead of the one matching the open page

### Browser

Chrome

### Browser Version

128.0.6613.86

### Extension Version

8.0.1

**Comment by mymindstorm** [comment]
We changed that feature to turn off by default in 8.0.0. You should be able to turn it on via 'Smart Filter' in settings.

**Comment by jooname** [comment]
Oh nice! Yes, that did the trick.
