### ISSUE TITLE
Smart Filter Not Working

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#1295]
We recently made a change to turn the smart filter feature off by default. If you would like to re-enable it, turn on the feature in the preferences menu.

![image](https://github.com/user-attachments/assets/059cca64-2668-48d6-84e7-43fd96e3ad86)

**Comment by Rasinzz** [comment]
I have smart filter enabled and it's still not working. Where do I go to put the URL in or does it just automatically generate the URL from the entry title? If so, I've been trying to get it to work, made the entry title stuff like `x.com`, `www.x.com`, `https://x.com/home`... nothing works. Any help greatly appreciated!

**Comment by mymindstorm** [comment]
Try putting two colons after the issuer like this: `X::x com`

**Comment by Rasinzz** [comment]
Still not working. Let's just say for example the website is amazon.com, what is all the raw data I should put in the Issuer field?

**Comment by mymindstorm** [comment]
I can't reproduce this on my end. Amazon would be `<account name/anything>::amazon.com`


![Screenshot from 2024-10-13 14-20-07](https://github.com/user-attachments/assets/2ab5a156-b0d3-4fe2-bc7e-6a096b6fbddb)
![Screenshot from 2024-10-13 14-20-00](https://github.com/user-attachments/assets/d14e30a0-f672-477a-bc17-dc4f3c8b7ada)
![Screenshot from 2024-10-13 14-19-56](https://github.com/user-attachments/assets/e889a790-9ce9-473f-b938-96367becda7e)

**Comment by mymindstorm** [comment]
Actually, could you try scanning a QR code? If you haven't accepted the permissions for that, smart filter may not work.

**Comment by Rasinzz** [comment]
Working now, thank you!

**Comment by mymindstorm** [comment]
@Rasinzz please share what you changed to make it work for others in case they have the same issue.

**Comment by Rasinzz** [comment]
Just completely reset the extension and all it's data and it decided to work. And of course, re-enabled Smart Filtering.

My 2 test entries look like this:

`a::authenticationtest.com`
`b::x.com`

Both correctly filter entries as intended on the respective URLs.

**Comment by jayenashar** [comment]
is it possible that every time the firefox addon is upgraded, if the smart filter preference is off, it could open this github issue?  while i noticed it stopped working, new users may not know this wonderful feature is available.
