### ISSUE TITLE
firefox, manifest.json v3 - change "_execute_browser_action" to "_execute_action"

### ISSUE THREAD

**Issue by Xawiu** [Authenticator-Extension/Authenticator#1301]
### Describe the issue

**Problem:** In Manifest Version 3, the command _execute_browser_action has been deprecated and replaced with _execute_action. Because the manifest file still uses the old command, the extension's keyboard shortcuts don't work properly in Firefox.

In the manifest.json, it is necessary to change:

```
"commands": {
  "_execute_browser_action": {},
```

to:

```
"commands": {
  "_execute_action": {},
```

### Browser

Firefox

### Browser Version

130.0

### Extension Version

v8.0.0

**Comment by cesar19004** [comment]
Fixed in #1288. We need to wait for the new version to be deployed to the Firefox Store. The current version is 8.0.0.

**Comment by yermulnik** [comment]
@cesar19004 Is there an approx timeline for that? This feature is drastically missed from everyday workflow 😢 Thanks.

**Comment by cesar19004** [comment]
I don’t know, but maybe @mymindstorm or @Sneezry do. For some reason, we are also missing the 8.0.1 update in Firefox, which fixes #1262

**Comment by mymindstorm** [comment]
Sorry about the delay, I've been super busy. I'll try to get the update submitted to Mozilla within the next few days.

**Comment by mymindstorm** [comment]
Just submitted this to Mozilla, as soon as they approve the update.

**Comment by yermulnik** [comment]
Can confirm it now works w/o issues. v8.0.2 (Sept, 20, 20224). Thanks a bunch 👍🏻
