### ISSUE TITLE
Support period paramater

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#131]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

https://github.com/google/google-authenticator/wiki/Key-Uri-Format#period

https://github.com/Authenticator-Extension/Authenticator/issues/127#issuecomment-388236670

**Comment by Sneezry** [comment]
Done.
