### ISSUE TITLE
Not filtering for currently viewed domain

### ISSUE THREAD

**Issue by baszero** [Authenticator-Extension/Authenticator#1313]
### Describe the issue

This worked like a charm before but suddenly stopped working.
My authenticator plugin always shows ALL entries regardless on which page i am. 

### Browser

Chrome

### Browser Version

128.0.6613.138

### Extension Version

8.0.1

**Comment by teknowledgist** [comment]
I came here to say pretty much the same thing, but I'm using FireFox and version 8.0.2.

**Comment by orschiro** [comment]
Same here.

Example:

I am on the PayPal website, but the authenticator is showing me all my accounts instead of just PayPal.

This issue started happening maybe two or three weeks ago.

I am using the Chrome extension.

**Comment by cmclaughlin** [comment]
Me too

**Comment by baszero** [comment]
This is so annoying. Can any contributor please fix this asap? Seems to be a very quick fix!

**Comment by baszero** [comment]
I would create a pull request to fix this if I would understand the whole application design model.
I think the bug is somewhere here:

![image](https://github.com/user-attachments/assets/be56617b-6436-4d95-99b0-ce6147d8733e)

https://github.com/Authenticator-Extension/Authenticator/blob/dev/src/utils.ts

And maybe this helps:
![image](https://github.com/user-attachments/assets/70b9a9b7-1c9a-4cd1-904c-cd57d7efb4b7)

**Comment by mymindstorm** [comment]
Look at #1295.
