### ISSUE TITLE
URL-Matching didnt work anymore

### ISSUE THREAD

**Issue by Anagastes** [Authenticator-Extension/Authenticator#1321]
### Describe the issue

Hi, recently the url matching TOTP are no longer filtered automatically when you are on a page.

I now have to search for them myself every time. Makes it a bit uncomfortable.

### Browser

Firefox

### Browser Version

Arch Firefox 131.0

### Extension Version

8.0.2

**Comment by mymindstorm** [comment]
Look at #1295
