### ISSUE TITLE
You should be able to recover your account with your phone number.

### ISSUE THREAD

**Issue by toufiqnbr** [Authenticator-Extension/Authenticator#1324]
You should be able to recover your account with your phone number.
phn number is - 01722623322

_Originally posted by @keytrap-x86 in https://github.com/Authenticator-Extension/Authenticator/issues/1162#issuecomment-2182864560_

**Comment by toufiqnbr** [comment]
HOW

**Comment by mymindstorm** [comment]
https://authenticator.cc/docs/en/lost-codes
