### ISSUE TITLE
v5.0.10 Release

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#135]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

We have five new languages ready for the next release. Thoughts on releasing a new version soon?

**Comment by Sneezry** [comment]
I'm in travel, and will be back home on Sunday. I will release a new version to Chrome Web Store after I go back home.

**Comment by mymindstorm** [comment]
Got it, just merge to release whenever it's most convenient for you and I'll release it then.

**Comment by Sneezry** [comment]
Merged.
