### ISSUE TITLE
Seach feature

### ISSUE THREAD

**Issue by ghost** [Authenticator-Extension/Authenticator#138]
will be so hard add a search for this extensión?

**Comment by mymindstorm** [comment]
We already auto filter by site, why do you want a search function?

**Comment by isumairu** [comment]
because it'll be f---ing helpful. I find the auto filter often failed. I have many accounts. Search and/or sorting feature is a feature I need.
By the way, can anyone change the title of this thread to "search and sorting feature" or something more relevant?

**Comment by mymindstorm** [comment]
@isumairu if it can't auto filter it right add `::sitename` to the "Account Name" field. for instance my entry for `GitHub` would be `GitHub::github.com`
