### ISSUE TITLE
Use google authenticator android app MFA with google authenticator extension

### ISSUE THREAD

**Issue by chandrapratapsingh08** [Authenticator-Extension/Authenticator#139]
**Describe the feature you want:**

**Why do you want this feature in Authenticator?**
Hello Folks,

My query is that I am currently using google authenticator android application for MFA, now I install google authenticator extension in my chrome browser. How can I sync my all google authenticator android application MFA with the chrome extension.

Kindly suggest.

Thanks

**Comment by Sneezry** [comment]
The official answer is No, you can't.

Authenticator extension is not a Google product, and it cannot sync data from Google products.

However, there is a workaround to make it possible (a rooted Android phone is required), but you need do it at your own risk.

See https://github.com/Authenticator-Extension/Authenticator/issues/116

**Comment by mymindstorm** [comment]
Additionally, if you want to export any codes you have in the extension there is a button on the top right of any code you can use to export it to other apps.
