### ISSUE TITLE
Oprea Comaptibility

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#141]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

https://dev.opera.com/extensions/apis/

> Opera does not support the sync() and managed() methods.

Shouldn't it be impossible to use the extension in Opera? Should we just change [this](https://github.com/Authenticator-Extension/Authenticator/wiki/Install-in-Opera) to say it's unsupported for the time being?

**Comment by Sneezry** [comment]
It should just fall back to storage.local, but I'm not sure. I remember that I tested to add a new account in Opera, and it works.
