### ISSUE TITLE
Can't enter password to decrypt

### ISSUE THREAD

**Issue by DKaos** [Authenticator-Extension/Authenticator#145]
When you click the authenticator icon, the usual password prompt appears. However, the window disappears as soon as you click the text box to enter password. Hence you can't use the extension at all.

Using Firefox  60.0.1 (64-bit) on Ubuntu 18.04 LTS

**Comment by mymindstorm** [comment]
By window do you mean the enter password screen or the whole popup?

**Comment by mymindstorm** [comment]
No response in over more than a week, closing.
