### ISSUE TITLE
Confirmation of old Dropbox API key removal

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#148]
The old Dropbox API key `013qun2m82h9jim` will be removed because of secret leak in previous versions. The latest Dropbox API key is `mmx38seexw3tvps`. The latest Authenticator on Chrome Web Store has already changed to the latest Dropbox API key.

After we remove `013qun2m82h9jim` from Dropbox API key list, users with old version (v5.0.9 and below) will not be able to login Dropbox in the extension.

Is Firefox ready for old Dropbox API key removal?

**Comment by mymindstorm** [comment]
Yes, most of my users are on 5.0.10

https://addons.mozilla.org/en-US/firefox/addon/auth-helper/statistics/usage/versions/?last=30

**Comment by mymindstorm** [comment]
What do you mean by secret leak?
