### ISSUE TITLE
enrypted codes

### ISSUE THREAD

**Issue by g65jan** [Authenticator-Extension/Authenticator#152]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

**Describe the bug:** <Describe the issue with Authenticator> 

**Platform:** <This is required>

**Comment by g65jan** [comment]
I put a generic security code on google authenticator, but since then all the codes on the pages they used were occult and I can not open them, how can I find it?

**Comment by g65jan** [comment]
answer please for encryped codes,it is very important to me

**Comment by mymindstorm** [comment]
Can you be more specific? What do you mean by "occult"? Are you sure you put your password in correctly? Do you have a backup?

**Comment by g65jan** [comment]
hello! i mean authenticator turn off all my codes as encrypted after i give
it a general code as authenticator recomended..and no i have not backup


2018-06-14 22:01 GMT+03:00 mymindstorm <notifications@github.com>:

**Comment by mymindstorm** [comment]
This probably means that you got your password wrong. I can't do anything about that except refer you [here](https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes).

If you are 100% sure you are using the correct password follow [these steps](https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information) and paste any messages here.

**Comment by mymindstorm** [comment]
No response in over a week, closing.
