### ISSUE TITLE
authenticator.cc - high risk web site blocked

### ISSUE THREAD

**Issue by supportsiden** [Authenticator-Extension/Authenticator#153]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

![image](https://user-images.githubusercontent.com/23124588/41401839-233a02ee-6fc1-11e8-90a2-5d3c3447653a.png)

**Comment by Sneezry** [comment]
This site hosts on GitHub, and it just redirects to this repo. You should ask your ISP for help.

**Comment by mymindstorm** [comment]
I've submitted a request to sophos to re-evaluate our website.
