### ISSUE TITLE
Featred on AMO

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#156]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

https://blog.mozilla.org/addons/2018/07/02/julys-featured-extensions-2/

**Comment by Sneezry** [comment]
Awesome!

**Comment by Sneezry** [comment]
How about adding this great news into README?
