### ISSUE TITLE
Import backup failed

### ISSUE THREAD

**Issue by DavidDickins** [Authenticator-Extension/Authenticator#157]
Hello, after reinstalling the operating system your application does not import the backup file, an error occurs. Important websites are held hostage. How to fix it?

**Platform:** Windows 10
-Browser: Hrome, Firefox.

**Comment by DavidDickins** [comment]
In addition, the application does not import the newly created copy of the file. Which is made specifically for testing.

**Comment by mymindstorm** [comment]
There is a known issue with restoring unencrypted file backups that will be fixed in the next release. For now, open the backup file in a text editor (E.g. Notepad) and follow the steps [here](https://github.com/Authenticator-Extension/Authenticator/wiki/Old-Backups)

**Comment by DavidDickins** [comment]
Many thanks, your advice helped. Good luck.

**Comment by Sneezry** [comment]
@mymindstorm this issue should already be fixed in master branch

https://github.com/Authenticator-Extension/Authenticator/commit/5a4487cfd2a1ca76636f6c9d1d5d64d663b4ebc4
