### ISSUE TITLE
Dropbox backup dialog

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#16]
<DO NOT USE THIS TO ASK HOW TO RECOVER LOST ACCOUNTS>
<MORE INFO HERE: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

'Dropbox Token' is missing a zh-cn translation

I don't really understand how to use the dialog past pasting the code into the Dropbox code field. Maybe add some sort of status text and make the token field `readonly` if you aren't supposed to put anything there?

**Comment by Sneezry** [comment]
Usually, token in Chinese is just translated as 'token' (no specific Chinese word).

![snipaste20180220_222145](https://user-images.githubusercontent.com/1621293/36429049-83b1f30e-168c-11e8-8956-ea439747315e.png)

token field is readonly in Chrome, but it doesn't work in Firefox, maybe we need make it disabled.

**Comment by mymindstorm** [comment]
If you are using css you need to add `-moz-user-select: none;` to it, `readonly` is more widely supported iirc

**Comment by Sneezry** [comment]
I have change the input to disabled, and it works both in Chrome and Firefox now
