### ISSUE TITLE
Search-box Not Working 

### ISSUE THREAD

**Issue by attilahajdo** [Authenticator-Extension/Authenticator#165]
**Describe the bug:** 
Search box not working!
I am working on a big project so i have like 60 (secret's) added to Authenticator, but when i click on the search box and type any of (secret) name's NOTHING shows up. See attached screenshots.

![q](https://user-images.githubusercontent.com/41155536/42634066-e729b728-85ea-11e8-88db-e870aa4adb4e.png)

![q1](https://user-images.githubusercontent.com/41155536/42634067-e74bb85a-85ea-11e8-9844-a1a200b777aa.png)

 

**Platform:** Windows 10 64bit
 - Browser: Chrome
 - Version: 67

**Comment by mymindstorm** [comment]
Search currently doesn't look at the username field, the site name needs to be in the issuer field. If you want I can make you a script that copies the username to the issuer field.

**Comment by Sneezry** [comment]
I find another issue: sometimes, especially when the entries are auto filtered, the search result only updates when you leave mouse from the search box in the first time. After that, it works fine.

GIF:

![example](https://user-images.githubusercontent.com/1621293/42668767-f98a7502-8684-11e8-8ca0-ab36f413b106.gif)

**Comment by attilahajdo** [comment]
Im not an expert on with scripts or so, but what if i edit the secrets and copy paste the title field to issuer field ? It will work then ? 

Or even better if you can make the script and help me implement it , it would be great. :)

**Comment by mymindstorm** [comment]
@Sneezry seems to be that vue uses oninput to tell when a textbox updates, which doesn't like to update in certain cases. Need to change it to update onkeypress

Also, if I leave the extension open for long enough the timer circle gets desynchronised from the actual time left.

![image](https://user-images.githubusercontent.com/27789806/42711116-6a2a7c72-86ac-11e8-8c57-edf2672dd7a8.png)

@attilahajdo run this [in the console](https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information) to copy everything to the right field. **Make sure you have a backup before you run this just in case**.

```javascript
(chrome.storage.sync.get(e => {
  let keys = Object.keys(e)
  for (let i = 0; i < keys.length; i++) {
    if (e[keys[i]].issuer.length === 0) {
      e[keys[i]].issuer = e[keys[i]].account
    }
  }
  chrome.storage.sync.set(e);
}))
```

**Comment by Sneezry** [comment]
@mymindstorm keydown event makes more sense

**Comment by mymindstorm** [comment]
@Sneezry in terms of behavior, should search look at the account name field?

**Comment by Sneezry** [comment]
@mymindstorm some websites set account as issuer and leave issuer blank. Looking at account field makes sense.

**Comment by attilahajdo** [comment]
@Sneezry  I believe the search should look at the Issuer field. It would be much easier  if you are working on a lot of projects like in my case. The script did not work for me, maybe i'm not doing something right. But i copied the Account name of all to Issuers field, and search works this way. The only downside of this is that i'll have to copy each, every time i have a new project to work on.

**Comment by Sneezry** [comment]
@attilahajdo currently, the extension will only search issuer field. We will search for both issuer and account field in the next version.

**Comment by attilahajdo** [comment]
thanks for the head's up @Sneezry . Waiting for the new version.

**Comment by attilahajdo** [comment]
sometimes the search box does not appear ? why ?

**Comment by Sneezry** [comment]
Search box will not appear when:

1. You have less than 10 entries
2. The entries are filtered in current tab

You can always press `/` to call search box.
