### ISSUE TITLE
Support encrypted backup on Dropbox and/or other platforms

### ISSUE THREAD

**Issue by n074v41l4bl34u** [Authenticator-Extension/Authenticator#170]
Authenticator should support encrypted backup to Dropbox and/or other online storage platforms. Since export can already be encrypted it seems natural to enable this functionality to backup. Besides, automatic unencrypted backup is clearly a security risk.

**Comment by mymindstorm** [comment]
Encrypted online backup and Drive support are done and part of 5.2.0, are there any specific online storage platforms that you want?
