### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xiaosheng778** [Authenticator-Extension/Authenticator#171]
Authenticator 身份验证器谷歌浏览器扩展程序-- 点击二维码图标显示捕捉失败
![image](https://user-images.githubusercontent.com/41770400/43301644-0c852d90-9199-11e8-8e11-66db6434ad02.png)

**Comment by Sneezry** [comment]
刷新下页面。如果是本地页面或者本地图片，需要在扩展设置页面勾选允许访问本地资源。
