### ISSUE TITLE
auto learn website chrome extensions

### ISSUE THREAD

**Issue by Odenorde** [Authenticator-Extension/Authenticator#172]
Thx for this great extension. If I understand it correctly, the app will "automatic" know which code should be inserted based on the URL. For example, if I login to google apps, the apps suggest the google authentication code. If I want to login to outlook app, the app suggest the outlook authentication code. 

Now I have a little issue with this. If I login to my Lastpass Extension the app suggest google authentication code instead off Lastpass. I think this is because in the URL link it shows chrome://extensions so the authenticator app "thinks" the user requires a google app.

Is it possible to "fix" this so the lastpass extension is recognized by the authenticator app?

![image](https://user-images.githubusercontent.com/33348015/43308160-e5b21d26-9180-11e8-860d-d1afb87c2b5c.png)

**Comment by Sneezry** [comment]
@Odenorde Thanks for your feedback.

The extension suggests entries in these ways:

1. Check if current page title contains issuer name.
  For example, if the issuer is **Google** and current page title contains Google, the entry will be suggested.

2. Check if current page domain contains issuer name.
  For example, if the issuer is **Google** and current page's domain is www.google.com.hk, the entry will be suggested.

3. Check if current page domain contains specific domain in issuer name.
  You can specific in which domain should this entry be suggested. For example, if the issuer is **Google::github.com** and current page's domain is github.com, the entry will be suggested.

Code logic: https://github.com/Authenticator-Extension/Authenticator/blob/v5.1.0/src/ui/entry.ts#L140

**Comment by Odenorde** [comment]
Hi Li,

Thank you for the reply!

This is the page title when the "lastpass extension" pops up:

<title>Google Authenticator Multifactor Authentication</title>

The URL is "chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/lp_toolstrip.html?browseraction=1&googleauth=1&trustexpired=0&trustlabel="

The only "lastpass entry" above is the extension ID (hdokiejnpimakedhajhdlcegeplioahd).

I see now why the authenticator app suggest my google account in stead off my lastpass account and understand that it's not easy adjusting it so that it would be suggesting my lastpass account.

[cid:60187923-ff52-4933-9d47-1301c9b62fb4]

Have a nice day!

Jeff

________________________________
Van: Zhe Li <notifications@github.com>
Verzonden: vrijdag 27 juli 2018 9:56
Aan: Authenticator-Extension/Authenticator
CC: Odenorde; Mention
Onderwerp: Re: [Authenticator-Extension/Authenticator] auto learn website chrome extensions (#172)


@Odenorde<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOdenorde&data=02%7C01%7C%7Cb830fed7c4c9467bebb708d5f3968957%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636682750225615504&sdata=wK%2BVnDFGPxBdqr0rlApDzcjPEnIONRIWKKfJEnWsAos%3D&reserved=0> Thanks for your feedback.

The extension suggest entries in such way:

  1.  Check if current page title contains issuer name.
For example, if the issuer is Google and current page title contains Google, the entry will be suggested.

  2.  Check if current page domain contains issuer name.
For example, if the issuer is Google and current page's domain is www.google.com.hk<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.google.com.hk&data=02%7C01%7C%7Cb830fed7c4c9467bebb708d5f3968957%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636682750225771756&sdata=fzFWfzhyapVzQjajw2y4w%2FtL6Of5NgzeKdM80ta5YgE%3D&reserved=0>, the entry will be suggested.

  3.  Check if current page domain contains specific domain in issuer name.
You can specific in which domain should this entry be suggested. For example, if the issuer is Google::github.com and current page's domain is github.com, the entry will be suggested.

Code logic: https://github.com/Authenticator-Extension/Authenticator/blob/v5.1.0/src/ui/entry.ts#L140<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAuthenticator-Extension%2FAuthenticator%2Fblob%2Fv5.1.0%2Fsrc%2Fui%2Fentry.ts%23L140&data=02%7C01%7C%7Cb830fed7c4c9467bebb708d5f3968957%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636682750225771756&sdata=cnEOTDbTQzvA%2BdjeQdm4ZohUz3JWaFcLwqPI5vcEBsc%3D&reserved=0>
