### ISSUE TITLE
QR scanner does not recognize certain QR codes

### ISSUE THREAD

**Issue by alystair** [Authenticator-Extension/Authenticator#174]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

**Describe the bug:** 
QR scanner does not recognize certain QR codes.

Attempt scanning [this QR Code](https://api.qrserver.com/v1/create-qr-code/?data=otpauth%3A%2F%2Ftotp%2Fbcu_site.test%253Alorin%2540barcraft.com%3Fissuer%3Dbcu_site.test%26secret%3DD7HMG5LUQI3UNNRSSCG62TZMQIGX4KSK65GDITDWPTIDLP74QJ6ALHN664MDZSMV5CX7SUWWTHZPGDU33LYFHJYY4H7ZCGCZ2H4W3DI&qzone=1&size=250x250&ecc=L&format=png) - it does not get recognized at all. If ECC is changed it's recognized

**Platform:** <This is required>
 - Chrome
 - 70.0.3501.2 (Official Build) canary (64-bit)

**Comment by mymindstorm** [comment]
The QR decoder library we use is old and not maintained well. Need to look into alternatives.

**Comment by Sneezry** [comment]
Agree, but it's not an easy work. Most famous QR decoder libraries are not written in JS or TS. We are able to rewrite those libraries in TS, however, the cost is too much.

The current library works fine with high level ECC (M and above). For example:

![](https://api.qrserver.com/v1/create-qr-code/?data=otpauth%3A%2F%2Ftotp%2Fbcu_site.test%253Alorin%2540barcraft.com%3Fissuer%3Dbcu_site.test%26secret%3DD7HMG5LUQI3UNNRSSCG62TZMQIGX4KSK65GDITDWPTIDLP74QJ6ALHN664MDZSMV5CX7SUWWTHZPGDU33LYFHJYY4H7ZCGCZ2H4W3DI&qzone=1&size=250x250&ecc=M&format=png)

**Comment by mymindstorm** [comment]
I found [this](https://github.com/cozmo/jsQR). It's actively maintained and written in TS. Made a branch to test it out at [qr-engine](https://github.com/Authenticator-Extension/Authenticator/tree/qr-engine).

**Comment by delmicio** [comment]
any workaround for those QR code not recongised?

**Comment by mymindstorm** [comment]
Not exactly a simple problem to fix. For now you can just use manual entry.

**Comment by delmicio** [comment]
yes, I've found that after an hour ... not that intuitive ... maybe you can add a tip about where to find it when scanner could't get the QR code for more than 2 times.

In my case they just gave me the QR code and nothing else ... So I used a thir party service web servide to upload the code and get the information.

**Comment by kwamiii** [comment]
if anyone is willig to help
can someone help with getting a 6 digit code

**Comment by johanberonius** [comment]
I tried to use inverted colors, white on black, for a QR code but that did not work with this extensions. It was accepted in various authenticator apps and using iOS camera.
Normal colors, black on white, was fine for the same QR code.

**Comment by chupetoide** [comment]
Hi, I'm also getting this issue with QR codes already recognized with previous versions. Here is a sample not recognized:
![image](https://user-images.githubusercontent.com/3883353/56533038-4c53ba00-652d-11e9-8a7d-f97ecf7c12c6.png)

Environment: 
Chrome:  73.0.3683.103 (Official Build) (64-bit)
SO: MacOs Mojave 0.14.4 (18E226)
Plugin: 5.3.0

**Comment by mymindstorm** [comment]
@chupetoide I think it's having trouble because of the curves on the alignment patterns. I can't patch any external dependencies due to Mozilla policy. In the next version we plan to be switching to a slightly more maintained fork of jsqrcode.

Bookmarking this for later: https://github.com/nimiq/qr-scanner

**Comment by chupetoide** [comment]
Ok, I'll bookmark it. But I tried it before with previous version and it worked with the same QR.

**Comment by cukal** [comment]
Came here through Google search, also using Gluu OTP generated QR's and facing the same problem.

**Comment by alystair** [comment]
I'm having problems with it recognizing some QRs generated by the [BaconQrCode](https://packagist.org/packages/bacon/bacon-qr-code) PHP package.

**Comment by Sneezry** [comment]
We have added jsQR lib for a secondary solution if it fails with the first try. Let's see if this issue migrates

**Comment by Sneezry** [comment]
All QR codes listed in the post can be recognized in recent version
