### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#180]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

Do you have an svg of the logo? Microsoft Store needs a 150 x 150 and I'd like to make it less blurry.

**Comment by Sneezry** [comment]
How about this one https://github.com/Authenticator-Extension/Authenticator/blob/dev/images/icon.svg

**Comment by mymindstorm** [comment]
That's just the part I needed, thanks.
