### ISSUE TITLE
Importing andOTP data

### ISSUE THREAD

**Issue by erotavlasme** [Authenticator-Extension/Authenticator#185]
Hi,
I can successfully import backup from freeOTP into the plugin. However, freeOTP is not updated and is considered not secure. So I switched to andOTP. Unfortunately, the JSON backup file uses a different format compared to freeOTP and the plugin.
Is there any way to import it?

andOTP JSON

```
{"secret":"7HTONMXGVZTEMMP555","label":"test","period":30,"digits":6,"type":"TOTP","algorithm":"SHA1","thumbnail":"Default","last_used":1530793025525,"tags":["exchange"]}
```
plugin JSON

```
{"22e991a1711a51f8aab522081666b5d3":{"account":"test","hash":"22e991a1711a51f8aab522081666b5d3","issuer":"","secret":"A3MUFPMUQTCNVAAODBRONWFL3KLOFPSK","type":"totp","encrypted":false,"index":0,"counter":0}}
```

**Comment by mymindstorm** [comment]
You can manually change it to our format. Here's the reference:
```json
{
    "<md5 of secret>":{
        "account":"<account name>",
        "hash":"<md5 of secret>",
        "issuer":"<account issuer>",
        "secret":"<secret>",
        "type":"totp",
        "encrypted":false,
        "index":0,
        "counter":0
    }
}
```

If you don't want to manually convert your backup, you can take the `"secret"` value and pate that into the manual entry screen.

**Comment by erotavlasme** [comment]
Ok, I solved via manual entry. However, it is a long process. It would be useful to have an automatic import.
