### ISSUE TITLE
authenticator.cc has been blacklisted in multiple scanners

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#196]
See: https://www.virustotal.com/#/url/6e5e26f5840b51143488c1259eb50d45566d36e585a35e21c9a28a921a2b4896/detection

Have no idea why multiple scanners regard our site as a risk.

Here's details from McAfee: http://www.siteadvisor.com/sitereport.html?url=authenticator.cc

![snipaste20180910_141953](https://user-images.githubusercontent.com/1621293/45279762-a787ed80-b504-11e8-86d8-4afb7aefb796.png)

## Status

https://www.virustotal.com/#/url/6e5e26f5840b51143488c1259eb50d45566d36e585a35e21c9a28a921a2b4896/detection

| Engine | Status | Result (from VirusTotal) |
| ------ | ------ | ------ |
| Avira | Removal request sent | Pending |
| CRDF | Resolved | Removed |
| CyRadar | Removal request sent | Pending |
| ESET | Resolved | Removed |
| Forcepoint ThreatSeeker | Resolved | Removed |
| Kaspersky | Removal request sent | Pending  |
| Sophos AV | Removal request sent | Pending |
| McAfee | Resolved | Removed |
| Symantec K9 | Resolved | n/a |

**Comment by mymindstorm** [comment]
This is probably because we use the `<meta>` tag to redirect, maybe you should switch it to using a 301 redirect? 

I've updated the table a bit.

**Comment by Sneezry** [comment]
Our site is hosted on GitHub Pages which doesn't support 301 redirect. I'll make a real home page for the project soon.

**Comment by mymindstorm** [comment]
Isn't that something you can set from the domain registrar? They all tend call it something different.

**Comment by Sneezry** [comment]
No. This domain is registered with a Chinese company. China government doesn't allow domain registrar to support 301 redirect service.

**Comment by Sneezry** [comment]
And that is the reason Google.cn doesn't redirect to Google.com.hk

**Comment by Sneezry** [comment]
We have sent removal request to all of these security engines. Some have already removed our domain from blacklist, however, some haven't.

The site content is open sourced on GitHub, and this is a ridiculous mistake for these security engines obviously.

We have waited for more then one week, and I believe that engines those haven't taken action will not take action in the future. So I will close this issue. This issue is never on our side.
