### ISSUE TITLE
Code autofilled

### ISSUE THREAD

**Issue by jpfleury** [Authenticator-Extension/Authenticator#197]
Hi,

I'm using Authenticator 5.1.1 (Firefox 62, Xubuntu 18.04). On the [release notes for the version 5.1.0](https://github.com/Authenticator-Extension/Authenticator/releases/tag/v5.1.0), it says that "Codes can now be automatically inserted to a page".

How does it work? I don't see such options in my version.

Thanks for this very useful addon.

**Comment by Sneezry** [comment]
You can enable it from Settings -> Popup Page -> Use Autofill

**Comment by jpfleury** [comment]
Thanks. So I checked it, but it doesn't seem to work. For example, with Github, when I log in, there's only one entry on Authenticator, but the field is not autofilled:

![image](https://user-images.githubusercontent.com/687082/45281616-59440180-b4a6-11e8-87e8-f419f3b4bfcd.png)

Is that the purpose of this option?

**Comment by Sneezry** [comment]
Indeed. GitHub uses tel type input box (for telephone number) instead of text box. We will add specific support for GitHub in the next release.
