### ISSUE TITLE
battle.net add issue

### ISSUE THREAD

**Issue by hchely** [Authenticator-Extension/Authenticator#198]
How add the battle.net , the secret key is wrong.
from battle.net authen app only got the SN and recovery key. which is using to add authenticator? 
the SN like CN-4digital number-4digital number-4digital number-4digital number
the recovery key is A-Z and some digtal number mixed string.
but any those type in authenticator , it is show error for me. it is not base32 of HEX.

**Comment by Sneezry** [comment]
You need discover secret first. https://github.com/Sneezry/PyGetBlizSecret

**Comment by mymindstorm** [comment]
@Sneezry do you have a link to a utility that can get the Steam secret, or should I patch some docs together from [this](https://github.com/SteamTimeIdler/stidler/wiki/Getting-your-%27shared_secret%27-code-for-use-with-Auto-Restarter-on-Mobile-Authentication)?

**Comment by Sneezry** [comment]
I do not have any resource about Stream secret now. Please patch the docs or add a link to the given docs above, thanks.
