### ISSUE TITLE
Twitter bot original tweet link uses display name instead of username

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#204]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>
<You can also open an issue by Tweeting with #AuthenticatorFeedback>

Hence broken links. Example at #203 

Use `screen_name` instead of `name`

**Comment by Sneezry** [comment]
I did a workaround. The origin tweet url will not contain user display name.

There's an issue to show urls contain spaces on GitHub. I have tried

* `<url contains spaces>`
* `[url contains spaces](url contains spaces)`

Neither works.

**Comment by Sneezry** [comment]
Also, I fail to find user name (instead of display name) in Azure Logic App.

There're two parameters related with user name:

* User name (what I use)
* User display name

I will make more test for the real user name (twitter user ID)

**Comment by Sneezry** [comment]
Fixed.

**Comment by mymindstorm** [comment]
Oh, I thought you were using the Twitter API directly. Thanks for the fix.
