### ISSUE TITLE
The import backup page is broken

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#210]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>
<You can also open an issue by Tweeting with #AuthenticatorFeedback>

I forgot a reference. @Sneezry fix in release as 5.2.1 #211

**Comment by Sneezry** [comment]
Do we need take further action on this?

**Comment by mymindstorm** [comment]
It's already fixed, just push the new version and stop deploying 5.2.0 if you haven't already started sending it out

**Comment by Sneezry** [comment]
OK, got it.
