### ISSUE TITLE
Google Drive in Chrome problems

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#212]
![snipaste20180926_131515](https://user-images.githubusercontent.com/1621293/46058594-5b88aa00-c18e-11e8-8c71-77163ab7fcc3.png)

**Comment by mymindstorm** [comment]
I restricted the client id chrome uses to only accept requests when the extension id matches the one in the web store.

Set [key](https://developer.chrome.com/apps/manifest/key) to `bhghoamapcdpbohphigoooaddinpkbai` and try again

**Comment by mymindstorm** [comment]
If you can't get that to work, you can temporarily change the allowed extension id [here](https://console.developers.google.com/apis/credentials/oauthclient/292457304165-u8ve4j79gag5o231n5u2pdtdrbfdo1hh.apps.googleusercontent.com?project=marine-actor-215720 ) since it's not in use yet.

**Comment by Sneezry** [comment]
I am trying to create a new app key for local test.

**Comment by Sneezry** [comment]
Where can I get the secret from the console? I cannot find it in the downloaded JSON file.

**Comment by mymindstorm** [comment]
You don't need a secret for a chrome client id. Don't set that one in credentials.ts, set it in the chrome manifest

**Comment by Sneezry** [comment]
It works now. However, I find two other issues.

1. Logout Google Drive doesn't work correctly (token is undefined)
2. Sign in Dropbox doesn't work

I will do more test and update the result here.

**Comment by mymindstorm** [comment]
1. This is probably it:
```diff
--- a/src/ui/backup.ts
+++ b/src/ui/backup.ts
@@ -60,7 +60,7 @@ async function backup(_ui: UI) {
             xhr.open(
                 'POST',
                 'https://accounts.google.com/o/oauth2/revoke?token=' +
-                    localStorage.driveRefreshToken);
+                    localStorage.driveToken);
             xhr.onreadystatechange = () => {
               if (xhr.readyState === 4) {
                 resolve(true);
```
2. Again, your extension ID needs to be `bhghoamapcdpbohphigoooaddinpkbai` or the generated redirect url for dropbox will be wrong and result in a 400. [Example broken](https://www.dropbox.com/oauth2/authorize?response_type=token&client_id=mmx38seexw3tvps&redirect_uri=https%3A%2F%2Fdhkfjkknlpflbjppmibcjlphnjhkmdce.chromiumapp.org%2F), [Correct auth url](https://www.dropbox.com/oauth2/authorize?response_type=token&client_id=mmx38seexw3tvps&redirect_uri=https%3A%2F%2Fbhghoamapcdpbohphigoooaddinpkbai.chromiumapp.org%2F)

**Comment by mymindstorm** [comment]
fixed in eaaf0add1b34233f1090bbe51498e64b24abb1ea

**Comment by mymindstorm** [comment]
The identity API is a real pain since we can't verify that given redirect URIs are ours, plus the platform disparity that Google adds is annoying me. Thoughts on ditching the identity API completely and just modifying and injecting [dropboxtoken.js](https://github.com/Authenticator-Extension/Authenticator/blob/dev/js/dropboxtoken.js) into authenticator.cc/oauth to handle what `launchWebAuthFlow` does? I don't think it does anything that we can't replicate ourselves.

**Comment by Sneezry** [comment]
There're still some small issues for Google Drive:

1. Sign in Google Drive, and remain popup open after sign in successfully, go to settings, backup, Google Drive, Sign in button remains.
2. Logout Google Drive, close popup page. Open popup page again, and sign in Google Drive, always get failure. Relaunch Chrome will fix the issue.

I will try to fix these issues in these days if I have time.

Also, I find similar code in both backup.ts and background.ts, is it necessary?

**Comment by mymindstorm** [comment]
1. Run _ui.update somewhere in here after authenticator.xxxToken is set:
https://github.com/Authenticator-Extension/Authenticator/blob/109f4fcd6f7d22bde59f062414ddc37c24279be5/src/popup.ts#L128

2. [This](https://developer.chrome.com/apps/identity#method-removeCachedAuthToken) probably needs to be called around here since we revoke tokens now
https://github.com/Authenticator-Extension/Authenticator/blob/eaaf0add1b34233f1090bbe51498e64b24abb1ea/src/ui/backup.ts#L71

What code specifically is similar between the two? I think we have background.ts handling getting tokens and authorization because Firefox will close the extension popup page and terminate execution while the user is giving consent. (This also means that the initial backup won't happen in firefox)

**Comment by Sneezry** [comment]
Views should update automatically, and that is the reason we use Vue. If the view is not updated after we change variables, we should review the code.

In this issue, we use `authenticator.driveToken` to save Google Drive Token directly (`authenticator.driveToken`'s value is the token itself), it's a bad design (this issue shows the reason). A better way is to use an object to store values. Such as

```
authenticator.driveToken = {
  value: <Google Drive Token>
}
```

Thus, when we update `authenticator.driveToken.value`, the view should always update automatically.

Another way to trigger view update is to use `Vue.set` instead of changing variable value directly by using equals.

**Comment by Sneezry** [comment]
Google Drive Token issue fixed in https://github.com/Authenticator-Extension/Authenticator/commit/9fb1b1b628864a0ef466a1ca44787d03bb892b9e

**Comment by Sneezry** [comment]
Remove token cache issue fixed in https://github.com/Authenticator-Extension/Authenticator/commit/8dc0044e037b63b90985de22b01233f2bd6ba393

**Comment by Sneezry** [comment]
All issues fixed.

**Comment by mymindstorm** [comment]
One last thing for this, if a refresh token expires / is revoked and a request gets 401ed should we prompt to re-authenticate?

**Comment by Sneezry** [comment]
Yeah, we should tell the user token has been expired.

**Comment by mymindstorm** [comment]
Potential problem: https://help.github.com/articles/about-token-scanning/#token-scanning-for-public-repositories

**Comment by FDiskas** [comment]
```
Unchecked runtime.lastError while running identity.removeCachedAuthToken: Function unsupported.
    at Drive.<anonymous> (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/build/models/backup.js:95:67)
```
using opera. Plugin installed manualy

**Comment by mymindstorm** [comment]
@FDiskas opera has chrome in the useragent, but is not fully compatible with chrome extensions. This causes the extension to use the chrome specific drive auth flow. We have a more generic version, but it is only used it the browser does not have chrome in the UA.

**Comment by FDiskas** [comment]
@mymindstorm So it's not possible to adapt this plugin to opera also? :older_man:

**Comment by mymindstorm** [comment]
@FDiskas not being able to log into google drive in opera is not a major issue. I'll fix it in the next version. Please open a new issue instead of commenting on a closed issue next time.
