### ISSUE TITLE
Firefox Android

### ISSUE THREAD

**Issue by Riajyuu** [Authenticator-Extension/Authenticator#213]
**Describe the feature you want:**
Rework UI in responsive design so that it looks fine on Firefox Android.

**Why do you want this feature in Authenticator?**
To get TOTP code on Android

**Comment by mymindstorm** [comment]
Authenticator will not support Firefox for Android. Use Google Authenticator or any alternative. All it takes to get the code for use in a mobile app is to hover over a code and click the QR button at the top right.
