### ISSUE TITLE
Battle.Net authenticator is unusable

### ISSUE THREAD

**Issue by xPucTu4** [Authenticator-Extension/Authenticator#215]
**Describe the bug:**
This extension shows 6 digit codes and supports Battle.Net, however Blizzard require 8 digits from in their authenticator, so this is kind of broken.
One solution would be in case of Battle.Net to show 8 digits, however the better solution is to allow configuration for each authenticator for 4-8 digits for example.
Also in the case of Time OTP it would be good to allow to change between 30 and 60 seconds (also per authenticator).

**Platform:** Win10 x64 (irreverent)
 - Browser: Firefox
 - Browser Version: 64.0a1 (nightly)

**Comment by Sneezry** [comment]
Did you select Battle.net type for Battle.net account?

![snipaste20181003_184508](https://user-images.githubusercontent.com/1621293/46405981-9796ae80-c73c-11e8-9197-5cf676c89554.png)

We do support 8-digit code:

![snipaste20181003_184707](https://user-images.githubusercontent.com/1621293/46406040-ca40a700-c73c-11e8-933e-18b1879db48d.png)

**Comment by xPucTu4** [comment]
Yes, the type that I was selected was not Battle.net.
Sorry for the false issue.
Its working.
