### ISSUE TITLE
Auto filter after unlock at first time

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#216]
Generally, the extension will filter code for specific website. However, if we type master password to unlock the extension first time, auto filter doesn't work.

**Comment by vickijeffers** [comment]
I don't know what to do?

**Comment by vickijeffers** [comment]
Help me please

**Comment by mymindstorm** [comment]
@vickijeffers be more specific. Do you want to know how to stop it from filtering?
