### ISSUE TITLE
Verify Github organization domain

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#218]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>
<You can also open an issue by Tweeting with #AuthenticatorFeedback>

We can get a fancy verified stamp by doing [this](https://github.com/orgs/Authenticator-Extension/domain/MDE4Ok9yZ2FuaXphdGlvbkRvbWFpbjc3NA==/verification_steps)

https://blog.github.com/changelog/2018-08-07-domain-verification/

**Comment by Sneezry** [comment]
Done.
