### ISSUE TITLE
Autolock after a certain amount of time.

### ISSUE THREAD

**Issue by Odenorde** [Authenticator-Extension/Authenticator#219]
Suggestion: Add a setting for autolock after a certain amount of  #time.
(for example: after using the authenticator app, the app locks after 30 minutes so you have to type authenticator password again.)

**Describe the feature you want:**

**Why do you want this feature in Authenticator?**

**Comment by aleqx** [comment]
This is pretty vital for security given virtually everyone keeps their browser open nowadays. All password managers have this feature. It's also easy to implement.

p.s. Is there a donation address?

**Comment by aleqx** [comment]
Has this been implemented? I see it's been closed

**Comment by mymindstorm** [comment]
@aleqx it's been in the code for a while and I forgot to close it then.

**Comment by aleqx** [comment]
Ok, but is the current master functional then? If yes, why not push it to chrome store?

**Comment by mymindstorm** [comment]
@aleqx was waiting on argon2 to get into master. Will probably release soon.

**Comment by aleqx** [comment]
I asked because the general lock was not working - remember my report here https://github.com/Authenticator-Extension/Authenticator/issues/387? The browser never asks for the decrypt password (not sure if you fixed that).

**Comment by mymindstorm** [comment]
Yes, I do remember you made that report. A fix for that was made as part of the argon2 changes.

**Comment by aleqx** [comment]
> was waiting on argon2 to get into master. Will probably release soon.

Ok so master then can be built right now if I wanted to enjoy the fixed lock and new autolock?

**Comment by mymindstorm** [comment]
Yep

**Comment by aleqx** [comment]
Hmm, I removed the old extension from my Chrome, then I pulled and built master (under windows) and loaded the unpacked ext in Chrome. Says 6.0.0. I loaded by Backup file. I then setup a password again. I can see the padlock icon in the extension pane. I see no option to setup a timeout for autolock (and no mention of autolock either). What am I missing?

I also found a bug (will report separately).

**Comment by mymindstorm** [comment]
@aleqx it shows under Preferences after you set a password.

**Comment by aleqx** [comment]
I did look in there and there wasn't any preference for timeout ... but now there is! Does Chrome cache extension files too? Weird.

May I ask how you implemented the timeout functionality, specifically: is the timeout reset every time I copy a TOTP from the list? That would be the expected behavior.

**Comment by mymindstorm** [comment]
@aleqx the setting is hidden unless you have a password. The timeout only gets reset every time you open the popup (I.e. keeping the popup open for a long time will not prevent the timeout from taking effect).

You mentioned that you found a bug, could you elaborate on that?

**Comment by aleqx** [comment]
Sweet! Looking forward to using it. Many thanks for your hard work!

**Comment by aleqx** [comment]
> You mentioned that you found a bug, could you elaborate on that?

https://github.com/Authenticator-Extension/Authenticator/issues/424 ... more of a security hole/bad practice than a bug (should be fixed nonetheless).

**Comment by aleqx** [comment]
Why not push 6.0 to the Web store?

**Comment by LuckyLuv77** [comment]
aleqx
Not sure what you mean.. I apologize but I have so much going on a lot of things slip right bye me... I have so much to do and no one but me. Your like the 2nd person to reach out and answer.. In almost 2yrs


Laura

________________________________

**Comment by aleqx** [comment]
@LuckyLuv77 I was addressing @mymindstorm and pointing out that the official Web store version of the extension is still 5.3.2 whereas 6.0 has been functional for more than a month, and was suggesting to push 6.0 to the official Web store.

**Comment by mymindstorm** [comment]
@aleqx that's @Sneezry's decision. You can always sideload a newer build while you wait for an offical update.

**Comment by aleqx** [comment]
@mymindstorm I've already been using 6.0 since end of Jan myself. Everyone else would benefit though if it was in Web store ... @Sneezry why wait?

**Comment by LuckyLuv** [comment]
> Has this been implemented? I see it's been closed

Not sure I just jumped on..
