### ISSUE TITLE
Nextcloud Sync

### ISSUE THREAD

**Issue by ghost** [Authenticator-Extension/Authenticator#222]
**Describe the feature you want:**
A way to sync on Nextcloud our data (hor at least choose a local directory (the nextcloud directory), for the sync. 

**Why do you want this feature in Authenticator?**
Because use dropbox or drive is not very openmided for a service (if used on firefox), firefox user want privacy, so google and dropbox ...

**Comment by mymindstorm** [comment]
It would be nice to have Nextcloud support, but due to content security policy the extension needs to know exactly what endpoints it will be communicating with beforehand. This effectively makes it impossible to add Nextcloud support

**Comment by ghost** [comment]
This effectively makes it impossible to add Nextcloud support
Hum no, some other addon (floccus, passman, ...) do it, so it's possible .......

**Comment by Sneezry** [comment]
@aelisya Authenticator has a very strict policy to access user data. Authenticator only requires necessary permissions. If Authenticator requires all data user access to internet (do the same as floccus, passman, ...), it's an easy work to support Nextcloud.

**Comment by Sneezry** [comment]
@mymindstorm Maybe auto save backups locally can be a workaround for this case

**Comment by mymindstorm** [comment]
That works, though it would only be able to save files in the Downloads directory.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download

**Comment by erotavlasme** [comment]
> 
> 
> **Describe the feature you want:**
> A way to sync on Nextcloud our data (hor at least choose a local directory (the nextcloud directory), for the sync.
> 
> **Why do you want this feature in Authenticator?**
> Because use dropbox or drive is not very openmided for a service (if used on firefox), firefox user want privacy, so google and dropbox ...

What about firefox synx support?

**Comment by vwbusguy** [comment]
As a Nextcloud user myself, I suggest that saving to local should suffice, since many Nextcloud users sync a folder to their desktop anyway.  I would have more concerns trusting a TOTP extension that had permissions to make external internet calls.  

(By the way, many thanks @mymindstorm on the very well-done Firefox extension!)

**Comment by ghost** [comment]
> > **Why do you want this feature in Authenticator?**
> > Because use dropbox or drive is not very openmided for a service (if used on firefox), firefox user want privacy, so google and dropbox ...
> 
> What about firefox synx support?

Beaucause i have centralised my information in my nextcloud instance, i don't want to open a firefox account, if nextcloud can do it

**Comment by Sneezry** [comment]
> If you want to request hosts that you only discover at runtime, include "http://\*/" and/or "https://\*/" as an optional_permission. This lets you specify any origin in Permissions.origins as long as it has a matching scheme.

https://developer.chrome.com/apps/permissions

@mymindstorm here's the official suggestion to handle dynamic hosts permission. Do you think this makes sense?

**Comment by mymindstorm** [comment]
Don't we still have to declare the host in CSP?

**Comment by mymindstorm** [comment]
Permissions.request is also a bit broken in Firefox, will need to work around that.

**Comment by Sneezry** [comment]
@mymindstorm correct, we need to handle CSP. Emmm, then this is still blocking...

**Comment by mymindstorm** [comment]
Looking at the [API that's available](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download), I don't really see a good way to interact with the file system.

**Comment by lxwulf** [comment]
is here any update about that feature? 🤔
