### ISSUE TITLE
Autolock after sometime

### ISSUE THREAD

**Issue by qasims** [Authenticator-Extension/Authenticator#236]
**Describe the feature you want:**
Since it is an authenticator it should be more secure. It is good to have some kind of autolock feature after a minute or so. 

**Why do you want this feature in Authenticator?**
It very easy to forget manual lock by clicking on lock button which is security risk.

**Comment by Sneezry** [comment]
Duplicate with https://github.com/Authenticator-Extension/Authenticator/issues/219
