### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by titan60** [Authenticator-Extension/Authenticator#238]
Hi.
I have a problem with 2-factor authorization after changing time for winter time .
1. Authorization was in English (version 5.1.1), and became in Russian .
2. From authorization gone sites : - app.stex.com ; www.livecoin.net ; novaexchange.com ; ccrb.io and so on .
3. I couldn't copy the authorization because I didn't understand the English translation .
4. I ask you to restore my authorization or explain how to do it . The time is synchronized with Google .
With respect Filippov Igor ( igortitan60@gmail.com )
![03](https://user-images.githubusercontent.com/13693508/47900623-2c98de80-de86-11e8-9bd6-b339812f1389.png)

**Comment by mymindstorm** [comment]
Can you clarify what you have a problem with? Do you need help with the translations or are generated codes wrong?

**Comment by titan60** [comment]
Hi.
I have a problem with 2-factor authorization after changing time for winter time .
1. Authorization was in English (version 5.1.1), and became in Russian .
2. From authorization gone sites : - app.stex.com ; www.livecoin.net ; novaexchange.com ; ccrb.io and so on .


>Суббота,  3 ноября 2018, 18:52 +02:00 от mymindstorm <notifications@github.com>:
>
>Можете ли вы уточнить, с чем вы столкнулись?  Вам нужна помощь в переводах или сгенерированы коды неправильно?
>- 
>Вы получаете это, потому что вы создали тему. 
>Ответьте на это письмо прямо,  посмотрите на GitHub или  отключите тему .

-- 
Igor Filippov

**Comment by mymindstorm** [comment]
Again, please be more specific. What language do you want to use? Is the current language English or Russian? Did the generated codes stop working after you adjusted for winter time?
