### ISSUE TITLE
System time off

### ISSUE THREAD

**Issue by fartovi7777** [Authenticator-Extension/Authenticator#239]
Hello. Two questions.

1. Scan qr code on the right sites. All sites that try to connect to your authenticator write the wrong code? what is the reason ?   
2. In the settings of the application, I click the "synchronize time google" button in Settings. The attachment gives the error: "Attention! Your local clock is too far. Please correct before continuing."

**Comment by mymindstorm** [comment]
Your system time is off. You should sync with an NTP server. 

1. <kbd>Win</kbd>+<kbd>R</kbd> (Open run)
2. Type `timedate.cpl` and press enter
3. Go to the 'Internet Time' tab and click 'Change settings...'
4. Click 'Update now' and make sure it syncs successfully 
5. Go to authenticator and sync clock with google again
6. Test to see if time is correct using [this site](http://security-totp.appspot.com/)

**Comment by vickijeffers** [comment]
Forgive my ignorance, I'm learning. I can't figure out how the Authenticator works. But I know my time is off. Thanks for the fix please help an old Gramma who's young at heart.
