### ISSUE TITLE
Password window closes on first click

### ISSUE THREAD

**Issue by artem1s1** [Authenticator-Extension/Authenticator#242]
Trying to set password for encrypting secrets:

settings > security --> window with 2 fields for passwords opens up. 
as soon as I now click onto the window to set the cursor in the field, the whole authenticator window closes.

This is on ubuntu 18.04.01, using firefox quantum 63.0 (the same issue was reported already ( https://github.com/Authenticator-Extension/Authenticator/issues/145) but then closed due to inactivity by thread's creator)

**Comment by mymindstorm** [comment]
This sounds like a bug with with Firefox. Can you follow [these steps](https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information#firefox) and paste any messages here while reproducing the issue?

**Comment by artem1s1** [comment]
thanks for the quick reply.
not sure if I did everything correctly, but here's the output:
```
Could not read chrome manifest 'file:///usr/lib/firefox/chrome.manifest'.

Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered. components.manifest:150
 error occurred while processing 'sources: TypeError: can't access dead object
Stack: createNonSourceMappedActor@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:311:5
createSourceActors/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:399:21
Line: 311, column: 5 main.js:1576
	_unknownError resource://devtools/server/main.js:1576:5
	_queueResponse/responsePromise< resource://devtools/server/main.js:1605:27
```
tell me if you need anything else.. thanks!

![image](https://user-images.githubusercontent.com/44942275/48338343-b191ae00-e665-11e8-8cab-040a3a7e997c.png)

**Comment by mymindstorm** [comment]
Seems to be an issue with Firefox, I ran Ubuntu in a VM with same version and was able to reproduce. Using the same Firefox version in Fedora 28 did not cause the bug.

I've reported the bug in Ubuntu's bug tracker. 

https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1803631

**Comment by mymindstorm** [comment]
Closing in favor of https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1765304
