### ISSUE TITLE
Authenticator icon is not visible in Chrome

### ISSUE THREAD

**Issue by symbion6** [Authenticator-Extension/Authenticator#243]
**Describe the bug:** 
Authenticator icon was displayed in the extensions bar for weeks.
Since yesterday, the icon is gone. I've tried turning the extension on and off, restarting Chrome, but nothing works. It's gone, I cannot access Authenticator.

**Platform:** MacOS
 - Browser: Chrome
 - Browser Version: 70.0.3538.102 

![screen shot 2018-11-16 at 12 45 47](https://user-images.githubusercontent.com/35668196/48619687-95f81180-e99d-11e8-944f-9feef5fc07a6.png)

![screen shot 2018-11-16 at 12 45 53](https://user-images.githubusercontent.com/35668196/48619692-9a242f00-e99d-11e8-9324-fa4d40f99c2c.png)

**Comment by mymindstorm** [comment]
Check the three dots menu, Chrome will put extensions there if you have too many in the main bar. If it isn't there you should file a bug with Chrome [using these steps](https://support.google.com/chrome/answer/95315?co=GENIE.Platform%3DDesktop&hl=en)

**Comment by symbion6** [comment]
Wow, so easy to overlook....thanks for the help! Best Regards
