### ISSUE TITLE
autofill OTP fields

### ISSUE THREAD

**Issue by cankmeyil** [Authenticator-Extension/Authenticator#244]
hello,

can it automatically fill the OTP areas according to the given rules? for example web address and input element id?

otherwise a quick copy according to the web site name will be ok.

thank you in advance

**Comment by mymindstorm** [comment]
- You can copy by left clicking a code
- Sites will auto-filter if the site name is in the issuer or account name field
- Check popup settings -> autofill for autofilling codes
