### ISSUE TITLE
Allow for directly entering otpauth:// URIs

### ISSUE THREAD

**Issue by AfroThundr3007730** [Authenticator-Extension/Authenticator#245]
**Describe the feature you want:**

A common method of entering authentication codes is via the use of [`otpauth://`](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) URIs in the form:

`otpauth://totp/SiteName:user@email.com?secret=SECRET&issuer=SiteName&digits=7&period=30`

Basically, the contents of the scanned QR codes. I would like to be able to enter them directly.

**Why do you want this feature in Authenticator?**

Some authenticator tools don't make it easy to import/export a list of secrets from them, (looking at you Authy), and allowing the most common methods would increase the flexibility and usability of your tool. 

In the Authy case, a common export method is to do a manual dump from the Chrome devtools (see [this gist](https://gist.github.com/AfroThundr3007730/226072c420a9c38f2c31b1d0cfea0ae0) for details), which generates a bunch of URIs as described above. I could generate QR codes directly, but I'm on a desktop and can't easily import them back into this extension.

As an aside, you could also allow the extension to register a protocol handler for `otpauth://` URIs so if a site offers them, the user could just click on them to import them into the app.

**Comment by AfroThundr3007730** [comment]
Yes I know I can enter the account name and secret manually, but this method allows for handling of all the parameters, including the period, which doesn't have a field in the manual entry box.

Also exporting as a raw URI would be nice too.

**Comment by mymindstorm** [comment]
It's probably easier to just write a script / modify the authy export script to convert to our backup format. For reference, this is what our backups look like: 

```json
{
    "<md5 of secret>":{
        "account":"<account name>",
        "hash":"<md5 of secret>",
        "issuer":"<account issuer>",
        "secret":"<secret>",
        "type":"totp",
        "encrypted":false,
        "index":0,
        "counter":0
    }
}
``` 

- Period selection should be added to manual entry

- We can't register the `otpauth://` protocol handler due to platform restrictions.

**Comment by AfroThundr3007730** [comment]
>     * Period selection should be added to manual entry

Just reminded me, how are codes with other than 6 digits handled? Haven't tested that yet.

**Comment by mymindstorm** [comment]
Currently, we ignore the `digits` paramter. (It's also ignored by Google Authenticator)

**Comment by johanberonius** [comment]
It would be nice if links with an `otpauth://` scheme could be opened.  But "copy link" and paste it in the extension to add it would be good too.

**Comment by Sneezry** [comment]
@johanberonius custom scheme is not fully supported in web extension currently. In which case you need to import `otpauth://` uri? Is scan qr code enough for your case?

**Comment by johanberonius** [comment]
In the 2fa solution for the application we're working on QR codes are not used, only otpauth-links.
End users should use an authenticator app on a mobile device to open the otpauth link, but developers use this web extension. It would be nice to quickly add a link, maybe by drag & drop, copy & paste or right click context menu & open with.

**Comment by AfroThundr3007730** [comment]
> * We can't register the `otpauth://` protocol handler due to platform restrictions.

I was just reading a bit more on this, and found that protocol handlers in webextensions are limited to a [predefined list](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/protocol_handlers) or using the `web+` or `ext+` prefix.

There was [talk](https://bugzilla.mozilla.org/1271553) of implementing custom protocol support, but it appears to have stalled. I wonder how difficult it would be to get the devs to add `otpauth` to the list of allowed protocols.

There is also another project working on something like this at [mozilla/libdweb](https://github.com/mozilla/libdweb), which allows for registering a custom protocol handler, but it's not in the main source tree.

**Comment by Sneezry** [comment]
Currently, custom scheme support is very limited in webextensions. 

Of course, to inject DOM to listen click event of all links can make it done, however, I do not want to expand the permission scope. Also, to peep user's browser is unacceptable.

I personally think this feature is small minority, and QR scanner and manual entry is enough in most cases.

Let's move it to backlog and wait for webextensions to add `otpauth:` to predefined list.

**Comment by fortran77** [comment]
It would be convenient to be able to export the secret for a specific entry as a string that can then be copied to the clipboard. E.g., shift-click instead of control-click could cause the TOTP secret, instead of the generated 2FA code, to be copied to the clipboard.

I like to save all secrets in a secure file as a backup. If I forget to save the secret when enabling TOTP on a website, I then have to go to quite a bit of effort to find it. None of the common TOTP extensions/apps, including this one, make it easy to retrieve a specific secret in a text form that can be copied-and-pasted.

**Comment by Sneezry** [comment]
@fortran77 You can easily backup your secrets by using built-in Export/Import tool. Find it in settings menu. Also, you can link to your Dropbox or Google Drive account to make Authenticator backup your data automatically.

**Comment by fortran77** [comment]
Thanks, yes, I do export the backup. My language was unclear. There are many use cases that need individual secrets. E.g., I recently began using the Bitwarden password manager, and its built-in TOTP code generator needs the secret for each password entry.

**Comment by fortran77** [comment]
Another use case for extracting individual secrets:

[ProtonMail](https://protonmail.com/) is notorious for having no "keep me logged in" option and requiring 2FA (if enabled) on every login even in the same browser tab. An application called [email-securely](https://github.com/vladimiry/email-securely-app), while adding many other features, implements "keep me logged in" by saving the TOTP secret and re-entering the generated code as needed.

**Comment by mymindstorm** [comment]
#286 will allow for adding otpauth URIs via the import page (file & text entry). @AfroThundr3007730 @johanberonius is this good enough for ya'll?

**Comment by mymindstorm** [comment]
5.3.0 has support and is rolling out. The import backup page (file or text) will accept a list of otpauth URIs seperated by newlines.

@AfroThundr3007730 `digits` support is being tracked at #287, manual entry improvements at #304
