### ISSUE TITLE
QR code selection interface improvement

### ISSUE THREAD

**Issue by AfroThundr3007730** [Authenticator-Extension/Authenticator#246]
**Describe the bug:** <Describe the issue with Authenticator> 
Two things:
* In the QR code selection UI, the crosshair is very difficult to see and blends in with the background
* There is no way to abort the selection (preferably with `esc` key), and you have to make a dummy selection to clear it

**Platform:** <This is required>
 - Browser: Firefox
 - Browser Version: Nightly
 - OS is Debian Testing x86_64

**Comment by Sneezry** [comment]
> There is no way to abort the selection (preferably with `esc` key), and you have to make a dummy selection to clear it

Right click mouse should abort the selection. At least it works in Chrome. Could you verify it in Firfox?

**Comment by AfroThundr3007730** [comment]
Ok, that does abort the selection, but opens the right-click menu. Would you consider adding the keyboard shortcut as well?

**Comment by Sneezry** [comment]
@AfroThundr3007730 sure, it makes sense.

**Comment by mymindstorm** [comment]
@AfroThundr3007730 you might want to test in stable and report that in Bugzilla, I don't get a right click menu when the overlay is up. I'm running Firefox 63.0.3 on Fedora 28

**Comment by AfroThundr3007730** [comment]
Just verified in Firefox 60.3.0esr on Windows 10 1803 x64 (at work) that the right click menu still appears when canceling the overlay with the mouse.

**Comment by Sneezry** [comment]
Code has been merged. Will be available in next release.
