### ISSUE TITLE
authenticator fails once in a while

### ISSUE THREAD

**Issue by FlushingP** [Authenticator-Extension/Authenticator#248]
Installed Authenticator. First time works well, after a while it sometimes doesn't accept the generated code.
Couple of days later no problem, after that again a problem.

**Platform: Win10
 - Browser: Chrome
 - Browser Version: 70.0.3538.110

**Comment by mymindstorm** [comment]
These types of issues can be caused when your system time is off. Try this:

1. <kbd>Win</kbd>+<kbd>R</kbd> (Open run)
2. Type `timedate.cpl` and press enter
3. Go to the 'Internet Time' tab and click 'Change settings...'
4. Click 'Update now' and make sure it syncs successfully 
5. Go to Authenticator and sync clock with Google

**Comment by FlushingP** [comment]
Tnx. Tried that but no luck. The weird thing is that it sometimes works and sometimes not. Like this morning a nono, and a couple of hours later a yesyes. Very annoying.
Sorry about this but authenticator is installed on an android phone and authenticator is used to login to a website.

Sjors
