### ISSUE TITLE
QR quick scan button is misaligned

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#25]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

| ![image](https://user-images.githubusercontent.com/27789806/36446929-70672e02-1648-11e8-8c51-ffefe828cc14.png) | ![image](https://user-images.githubusercontent.com/27789806/36446973-9585a1dc-1648-11e8-875b-e3768afff5e1.png) |
| ------------- | ------------- |

**Comment by Sneezry** [comment]
That is as designed. The misaligned icons are visually aligned.
