### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by pvkan** [Authenticator-Extension/Authenticator#264]
Authenticator worked fine for a couple of weeks.
Since today selecting the icon in Chrome results in a blank (white)
![auth blank](https://user-images.githubusercontent.com/46726154/51206384-37e99b00-1908-11e9-8d6b-0d864224809a.PNG)
 pulldown.
I am not able to selects anything; icon for installation/setup is also not visible.

**Platform:** Windows 10 Home
 - Browser: Chrome
 - Browser Version: 71.0.3578.98

**Comment by mymindstorm** [comment]
Can you follow [these steps](https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information) and paste any messages here?

**Comment by pvkan** [comment]
Hi,

As you asked:

popup.html:1 Error in response to storage.get: TypeError: Cannot convert undefined or null to object at Object.chrome.storage.sync.get [as callback] (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/build/models/storage.js:25:49) at Object.chrome.storage.local.get [as callback] (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/build/models/storage.js:24:45)
popup.html:1 Unchecked runtime.lastError while running storage.get: IO error: .../LOCK: No further details. (ChromeMethodBFE: 15::LockFile::1) at Object.chrome.storage.local.get [as callback] (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/build/models/storage.js:24:45)

﻿Peter

**Comment by maiarosaqwert** [comment]
I do not even know how to do the drawing for my authenticator to give me
the code, please if I can tell me how to activate without drawing

pvkan <notifications@github.com> escreveu no dia quarta, 16/01/2019 à(s)
06:45:

**Comment by mymindstorm** [comment]
I remember having to deal with this before, but I can't seem to find the issue related to it.

Can you reboot your computer completely and try again?

**Comment by pvkan** [comment]
Did that several times.
I occurs on my laptop and i always shut it down at the end of the day.
So it reboots every morning.

**Comment by pvkan** [comment]
Completely uninstalled chrome, including entries in register.
Re-installed Chrome again and problem is gone.

So i guess Chrome was the faulty one ?

**Comment by mymindstorm** [comment]
Yes, Chrome uses LevelDB for local storage which seems to get corrupted easily. If you forced a shutdown (or ran out of battery) and that caused Chrome to close unexpectedly that probably caused it. If you hadn't reinstalled it we may have been able to get your data back, but it's too late for that now.

Chrome bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=490915

**Comment by Sneezry** [comment]
@mymindstorm user data should be safe in `chrome.storage.sync` if uninstall the browser directly, but not uninstall the extension first.

**Comment by pvkan** [comment]
Hi,

Thanks for the explanation.
I have a backup of the entries but fortunately, I use your extension on 2 computers (laptop and PC) and Google synchronizes these two including de data from your Authenticator.
As a result, my data was not lost but was immediately synced as soon as I had installed Chrome again.

Thanks again
Peter

Van: mymindstorm <notifications@github.com>
Verzonden: donderdag 17 januari 2019 23:35
Aan: Authenticator-Extension/Authenticator <Authenticator@noreply.github.com>
CC: pvkan <peter_van_kan@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Authenticator-Extension/Authenticator] Blank screen (#264)


Yes, Chrome uses LevelDB for local storage which seems to get corrupted easily. If you forced a shutdown (or ran out of battery) and that caused Chrome to close unexpectedly that probably caused it. If you hadn't reinstalled it we may have been able to get your data back, but it's too late for that now.

Chrome bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=490915<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbugs.chromium.org%2Fp%2Fchromium%2Fissues%2Fdetail%3Fid%3D490915&data=02%7C01%7C%7Ce86dd03f9f574d948b8908d67ccc13dc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636833613275146911&sdata=Q8rtlxmQs%2BOU%2FdPizzuZsnuOhxsFcVazHKZYy5XRFfs%3D&reserved=0>
