### ISSUE TITLE
Question - API Calls, using Python.

### ISSUE THREAD

**Issue by tobenary** [Authenticator-Extension/Authenticator#274]
Hi,
I'm a newbie learning API calls and Python.

I'm using your extension to get inside my regular 2fa sites. ( simple UI - great ).
One of my colleague at work developed a Python script to make new users for a specific system.
His script is not handling the 2fa cases, and I was thinking to myself if I could take his code, and modified ot a bit to have an integration with your code.

Basically, what I was thinking is changing his code when getting 428 response.

/web/api/v1.6/users/login > if 428 is the respond code, I'll redirect to Authenticate page.
/web/api/v1.6/users/auth/request-app  > from the respond there, I'm getting the time-based code. ( plain text )

I now only need to insert it to your plug-in ( extension ) and get the time-base respond.

Please advice how should I approach it.

Again, sorry it's a beginner's question, but I'm willing to learn.

**Comment by mymindstorm** [comment]
There isn't an easy way for us to add integration like that. Webextensions can't register the protocol handler for `otpauth://` and it's impossible to use an extension page that you could redirect to since the extension UUID in Firefox is unique for every install.

If you are only adding one code per user it's easiest to just generate a QR code and have users scan that. If you generate more than one secret per user, then you could have your script generate a backup file for Authentictor. Backup files are just JSON data formatted like this:

```json
{
    "<md5 of secret>":{
        "account":"<account name>",
        "hash":"<md5 of secret>",
        "issuer":"<account issuer>",
        "secret":"<secret>",
        "type":"totp",
        "encrypted":false,
        "index":0,
        "counter":0
    }
}
``` 

More on this at #245

**Comment by tobenary** [comment]
Thanks for your respond.
But if I create this backup, even if I import it to your extension, how do I "export" the time -based code from your extension to my code?

**Comment by mymindstorm** [comment]
I'm a bit confused, can you give me a bit more information on your application? I thought you were trying to import codes from your user generation script to Authenticator?

**Comment by tobenary** [comment]
Think about this scenario.

1. We usually log-in via API-Token to siteX.
2. Once this API-Token expired or someone regenerated a new token, the token is not valid anymore.
3. We now need to create a new random user ( other script ), but the 2fa is giving us some troubles making it automatically.
3a. if the site is not requesting for the 2fa, we logged in with the random user, then, generating the API key, then, saving it to our database.
3b. When the 2fa option is configured ON, we are generating new randome user, but when we try to login, the 2fa "new password" page pops out and there is the 2fa code to be placed in the GAuth app.

4. I want to take this time-based code "YWSJCBTH2HA27TBD" for an example ( text changed... ) and placed it in your application ( via backup or API call ( whatever you'll tell me how to do it ).

5. I want to "read" the current number/code appear in this second I am making the "call".
6. I'll pass the code to the login screen.
7. all done, I'll then be able to regenerate the APITOKEN, and skip my 2fa code ( that was mandatory in step 4&5 )

hopefully, I address my question correctly this time.

Thanks

**Comment by mymindstorm** [comment]
Authenticator is designed as an application for users. The environment Authenticator runs in disallows communication with other scripts. You could use [native messaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) to get what you want, but you will have to make those types of modifications yourself.

I think it makes more sense for you to completely ignore Authenticator and use browser automation tools like Selenium to get the secret and have the script use its own implementation of TOTP.

**Comment by tobenary** [comment]
Thank you very much for your directions.

I'll go over the first link since it looks easier for a newbie like me, but I'm sure I need to learn Selenium.

**Comment by mymindstorm** [comment]
Good luck!
