### ISSUE TITLE
autofill not working on Virtualizor VPS Control Panel

### ISSUE THREAD

**Issue by ghost** [Authenticator-Extension/Authenticator#276]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

**Describe the bug:** Autofill is not auto filling the auth box in [Virtualizor VPS Control Panel](https://virtualizor.com)

It used to work previously and I suspect a regression been introduced with version 5.2.2.

I cannot provide a login for testing purposes and the [Virtualizor demo](http://demo.virtualizor.com:4082/#act=twofactauth) does not seem suitable for testing.

**Platform:** <This is required>
 - Browser: FF | Vivaldi
 - Browser Version: FF 65/66/67 | V 2.2.1388.34 (Chrome/71.0.3578.85)
 - OS W10 1809 b17763.292 amd64
 - WX version 5.2.2

**Comment by mymindstorm** [comment]
Authenticator version 5.2.2 didn't change too much in the autofill code. Does the code get put into the right field when you try to use it?

**Comment by ghost** [comment]
It does not get filled at all but it did in the past even with https://github.com/Authenticator-Extension/Authenticator/issues/164

There is not output/error in the browser console.

I am not aware how the auto-fill field detection works but this is the html code

```
<input type="password" name="otp" id="otp" class="login_input" data-bcup="attached"
```

**Comment by erotavlasme** [comment]
Hi,
I have the same problem about auto fill with GNU/linux ubuntu mate and firefox developer edition 66 or firefox 65.

**Comment by mymindstorm** [comment]
@erotavlas85 with the same website?

**Comment by erotavlasme** [comment]
@mymindstorm several private Web sites.

**Comment by alfredonodo** [comment]
Hi,
I have the same problem with presearch.org

**Comment by mymindstorm** [comment]
@erotavlas85 @alfredonodo can you use inspect element and copy the html for the code `input` element?

**Comment by erotavlasme** [comment]
@mymindstorm for me one site is [protonmail](https://protonmail.com/).
This is the HTML of 2FA input

`<input autocapitalize="off" autocorrect="off" autocomplete="off" class="TwoFA-input ng-empty ng-invalid ng-invalid-required ng-valid-minlength ng-valid-maxlength ng-touched" type="text" ng-minlength="6" ng-maxlength="8" required="" ng-model="twoFactorCode" autofocus="autofocus" id="twoFactorCode" name="twoFactorCode" placeholder-translate-context="Placeholder" placeholder="Two-factor passcode">`

**Comment by alfredonodo** [comment]
@mymindstorm presearch.org

```
<div id="2fa-form" class="tab-pane animated flipInX active">
        <form method="POST" action="https://www.presearch.org/2fa/validate">
  <input type="hidden" name="_token" value="YpWqw4NmfvbwU9HO6ufHTMDHfeHJOGT6Rl9MMtKg">
  <input type="hidden" name="2fa_form" value="1">
  <input type="hidden" name="redirect_url" value="">

  
  <div class="form-group text-center">
    Please open your authenticator app and enter the current one-time password below:
  </div>

  <div class="form-group text-center">
    <input type="number" class="form-control" name="totp">
  </div>

  <div class="form-group text-center">
    <button type="submit" class="btn btn-block btn-primary">
      Validate
    </button>
  </div>
</form>

<div class="text-center">
  <a href="#login-form" data-toggle="tab" class="login-form-show">Back To Login Form</a>
</div>
      </div>
```
