### ISSUE TITLE
Authenticator Blank Screen on Chrome

### ISSUE THREAD

**Issue by delafurie** [Authenticator-Extension/Authenticator#278]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>
<You can also open an issue by Tweeting with #AuthenticatorFeedback>
I get a blank screen when I click on Authenticator to get a security code.
I followed the instructions in a previous post about a Blank Screen that said to copy any error messages into the console. 
I don't see any error messages. 
I'm not a programmer so I don't know where to even look for errors, but I don't see any messages in red like in the original post. 
I use the Authenticator on my HP laptop in Chrome and it works with no problems. 
Is there some reason why it won't work in Chrome on my Dell laptop?
They are both running the same version of Chrome: Version 72.0.3626.81 (Official Build) (64-bit)
Any suggestions on how I can get this to work on my Dell? 
Thanks

**Comment by mymindstorm** [comment]
You're saying you followed [these](https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information#chrome) instructions on your dell laptop and didn't see anything? By white screen do you mean the whole extension popup is white, or can you still see the header?

**Comment by delafurie** [comment]
Those are the instructions I followed. 
I see the console but I don't have any error messages to copy and paste into it. 
Are the error messages under another tab?
If so, which one?
I believe I looked at them all and don't see anything like in the previous instructions. 
Yes, the header is visible but no security code appears. 
I

**Comment by mymindstorm** [comment]
Did you reinstall the extension? It sounds like you just lost all your data. Try importing a backup from your HP laptop.

**Comment by delafurie** [comment]
That's what it's done since I first installed the extension on my Dell.
When you say create a backup on my HP, d you mean my emergency codes?
The ones I use if my device isn't available?

**Comment by mymindstorm** [comment]
No. Did you install it on the Dell and expect it to immediately sync everything? Go to the menu, then to `Import / Export`, `Download Backup`, then take that file and use the `Import Backup` button on your other computer.

**Comment by delafurie** [comment]
When I installed MFA on my HP I originally set it up to work by sending a code to my cell phone.
We have such a weak signal where I work it took me too much extra time to log into my company's cloud, cause I'd have to go outside or wait around a few minutes. This was all making me very late for work each day. Then I found out about the Browser Extension and I downloaded that because it's much easier and faster for me to access.  So when I downloaded the original emergency back up numbers, i did that with the intention of using them when my cell phone was taking too long. I just recently got the  Dell and I just added the extension in Chrome. If there's some set up I needed to do beyond that, I'm not sure what it is. 
So you're saying on my Dell go to menu, Import/Export, Download BackUp, and then take that file and use Import Backup on my HP?
Then things will be synched up and I'll be able to get a code on my Dell?

**Comment by mymindstorm** [comment]
If you already have the account added on the Dell, yes. Authenticator doesn't work with emergency backup codes, it's a drop-in replacement for Google Authenticator. If your company only lets you use SMS for MFA, Authenticator can't do anything to help you.

**Comment by delafurie** [comment]
"Authenticator doesn't work with emergency backup codes, it's a drop-in replacement for Google Authenticator. If your company only lets you use SMS for MFA, Authenticator can't do anything to help you."
I'm not really sure what you mean by that, but I'll try the steps you outlined tomorrow when I get to the office.

**Comment by mymindstorm** [comment]
> So you're saying on my Dell go to menu, Import/Export, Download BackUp, and then take that file and use Import Backup on my HP?
Then things will be synched up and I'll be able to get a code on my Dell?

If the Dell has your company account and is working, this will work.

> When I installed MFA on my HP I originally set it up to work by sending a code to my cell phone.
We have such a weak signal where I work it took me too much extra time to log into my company's cloud, cause I'd have to go outside or wait around a few minutes.

Some people can get MFA codes through text messages, you mentioned needing signal to get MFA codes. If you use text messaging to get your login codes, Authenticator is not compatible with that.

If you want to add your company account to Authenticator, you will need to setup your MFA to use an app.

**Comment by delafurie** [comment]
I'll give it a try tomorrow.
Thanks for your help. 
I appreciate it.

**Comment by delafurie** [comment]
That worked.
Thanks again for all your help. 
You're a real lifesaver!
