### ISSUE TITLE
Too easy to export secret using "hidden" button

### ISSUE THREAD

**Issue by tjoanp** [Authenticator-Extension/Authenticator#280]
Just tried this extension in Firefox, and it's really nice, but I have a "problem" with it.

The "hidden" QR button on existing entries seems way to dangerous. Compared to the Android and iOS apps where it's practically impossible to retrieve the secrets, stealing the secrets in this browser extension is done within 10 seconds on an unattended computer. Copying the secret is as easy as copying the OTP. It should not be that easy.

Would any of you feel comfortable storing your passwords in a text file on the desktop, and "secure" it by remember to lock the computer when leaving the desk?

**Comment by mymindstorm** [comment]
Check the security menu and set a password. It only stays unlocked until the browser is completely closed or you hit the lock button. 

> Would any of you feel comfortable storing your passwords in a text file on the desktop, and "secure" it by remember to lock the computer when leaving the desk?

It's normal policy to lock your computer when leaving your desk for many companies. Even if you don't have Authenticator, anyone getting into your email could wreck more havoc then just stealing some OTP secrets.

> Compared to the Android and iOS apps where it's practically impossible to retrieve the secrets, stealing the secrets in this browser extension is done within 10 seconds on an unattended computer. Copying the secret is as easy as copying the OTP. It should not be that easy.

It takes just about the same amount of time to export a backup the normal way and steal that. We won't be removing that functionality. If you are seriously concerned about this, you can always just only use a phone app.
