### ISSUE TITLE
Standardize backup format

### ISSUE THREAD

**Issue by fortran77** [Authenticator-Extension/Authenticator#282]
We seem to have more and more open source TOTP applications. Each one can export to json but uses its own format. I think one of the developers should publish a proposed a json export format and invite everybody to use that. This would be for data exchange, so encryption is not strictly needed (though desirable).

So far we have:

[Authenticator-Extension/Authenticator](https://github.com/Authenticator-Extension/Authenticator) (this one). Relevant previous issue #185.

[Gnome Authenticator](https://gitlab.gnome.org/World/Authenticator). (Gnome desktop.) Relevant issue: [https://gitlab.gnome.org/World/Authenticator/issues/111](https://gitlab.gnome.org/World/Authenticator/issues/111).

[FreeOTP+](https://github.com/helloworld1/FreeOTPPlus) (Android app.) See above issue.

[AndOTP](https://github.com/andOTP/andOTP) (Android app.) Relevant issue: https://github.com/andOTP/andOTP/issues/255

**Comment by mymindstorm** [comment]
I'm fine with doing this, but it's pointless to make a standard backup schema without any other developers on board.

See also: https://github.com/google/google-authenticator/wiki/Key-Uri-Format

**Comment by fortran77** [comment]
So if a URL format of the type otpauth could be standardized, then maybe an export format could be just a series of these URLs, newline-separated. If so, then we need to get everybody to agree on the URL format.

**Comment by mymindstorm** [comment]
@fortran77 that's already standardized, everyone uses it for adding individual secrets via QR codes. You wanted a standardized backup format which would hold multiple secrets.

**Comment by fortran77** [comment]
Well, that's great, then! So we just need a file containing one otpauth URL per line. That would work, wouldn't it? No encryption, but all we're looking for is data exchange. If we can get just one developer to use this format for import and export, it should be easy to get everyone else to do so.

**Comment by mymindstorm** [comment]
@fortran77 it would be simpler to just use JSON. It's a great idea to standardize the format, but it's pointless to do without anyone else willing to implement it. If you can find another developer willing to work with us on this then this could happen.

**Comment by fortran77** [comment]
Requested that the Gnome Authenticator developers consider the one otpauth URL per line format:

[https://gitlab.gnome.org/World/Authenticator/issues/111#note_439185](https://gitlab.gnome.org/World/Authenticator/issues/111#note_439185)

**Comment by mymindstorm** [comment]
@fortran77 using the otpauth URI format is fine for when you're transmitting a single code and nice for browser integration, but it doesn't really make sense to use for multiple values. Wouldn't it would make more sense to use something like the following?
```json
{
    "secrets": [
        {
            "secret": "string",
            "type": "string",
            "label": "string",
            "issuer": "string",
            "algorithm": "string",
            "digits": 6,
            "counter": 0,
            "period": 30
        }
    ]
}
```
With `secret` being the only required value.

**Comment by fortran77** [comment]
First of all, I appreciate your willingness to consider my proposal.

Now here are the pros and cons of one-otpauth-per line vs the json you listed.

One-otpauth-per-line: User-friendly as the user can manually edit the text file line by line before importing it. Each application already has the code to parse this. So on import, just parse each line the same way -- easy to implement. 

A standard json such as what you listed: Not user-friendly for manually editing the exported file. Each application developer will have to rewrite their code to parse this json on input. They will want to know why they should rewrite their code, and why doesn't everybody else just use the json they are already using. And they already have a json format for input, so now they have to support two different json formats on input (for imports from legacy files), and they have to figure out which one they are importing.

One-otpauth-per-line is so easy to implement it can probably be done in a couple of hours. At least one developer (see: [https://github.com/helloworld1/FreeOTPPlus/issues/30#issuecomment-464973951](https://github.com/helloworld1/FreeOTPPlus/issues/30#issuecomment-464973951)) seems ready to do it.

**Comment by Sneezry** [comment]
I think one-otpauth-per line is good for both human and program, let's do it :-)

**Comment by fortran77** [comment]
Great! If you would be so kind as to keep [helloworld1/FreeOTPPlus](https://github.com/helloworld1/FreeOTPPlus) aware of your plans, maybe both projects can implement and test for compatibility in parallel.

**Comment by Sneezry** [comment]
Code ready: https://github.com/Authenticator-Extension/Authenticator/pull/286

**Comment by fortran77** [comment]
Thanks, that was quick. This is very exciting.

**Comment by bilelmoussaoui** [comment]
Hey! I'm Authenticator developer.
I'm going to follow the standard backup format on Authenticator too. 
Will add it in the next release :)

**Comment by fortran77** [comment]
@bilelmoussaoui  That will be awesome.

(Of course there are multiple applications called Authenticator, but I know you're referring to [Gnome Authenticator](https://gitlab.gnome.org/World/Authenticator).)

**Comment by mymindstorm** [comment]
Authenticator 5.3.0 has support and the Firefox release should be rolled out to users in a few days. We're linking to this [page](https://authenticator.cc/docs/en/otp-backup) on the import screen. I'll keep it updated, so feel free to link to if wanted. I've also created a developer info page [here](https://authenticator.cc/docs/en/otp-backup-developer). Any feedback on those pages is welcome.

**Comment by ashutoshsaboo** [comment]
Hi @fortran77 , I saw a similar feature request of yours with FreeOtp+ as well - https://github.com/helloworld1/FreeOTPPlus/issues/30 . So far, there seem to be some alternatives for desktop (authenticator.cc), android (freeotp+), but are you aware of any iOS apps so far that already support this standard backup import/export format? Or have you raised/know of a similar feature request to any ios app as well?
