### ISSUE TITLE
Search box confusion restriction that requires / key

### ISSUE THREAD

**Issue by fortran77** [Authenticator-Extension/Authenticator#285]
Currently, under certain conditions (see: https://github.com/Authenticator-Extension/Authenticator/issues/165#issuecomment-407642686) the search box appears only when the / key is typed. But there is a "show all entries" button.

I find this confusing. It's a special case and I must remember to hit the / key.

It would be nicer if clicking on the "show all entries" button made the search box appear.

**Comment by mymindstorm** [comment]
I think that bug is already fixed (pending release), I'll have to check again since I rewrote the stylesheet. If you just hit `/` directly without clicking the "Show all entries" it'll stop filtering and open search directly.
