### ISSUE TITLE
Deleteing a charater in edit mode while filtering makes code disapear

### ISSUE THREAD

**Issue by fortran77** [Authenticator-Extension/Authenticator#289]
**Describe the bug:** <Describe the issue with Authenticator>

While on a specific web page, clicking on the extension icon shows one or more 2FA entries for that domain.

At this point suppose I click on the Edit icon (top right corner, looks like a pencil) and edit the provider field of an entry (the one above the numeric code). Editing seems to to normally. E.g., I can position the mouse cursor within the provider field and hit backspace to delete a character. However, there is one exception:

If I position the mouse cursor jusr after the first character in the provider field, and hit backspace to delete that character, the entire 2FA entry gets deleted instead. The deletion becomes permanent if I then click on the check mark.

I also seem to have permanently deleted one of two entries in the above situation without clicking on the check mark. I haven't reproduced this.

**Platform:**
 - Browser: Chrome (on a Linux desktop)
 - Browser Version: Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by mymindstorm** [comment]
It's not deleted, when you delete a character in filter mode it doesn't match the filter for the website you're on anymore and it filters it out.
