### ISSUE TITLE
Password cacheing in Firefox does not work  

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#29]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

**Comment by Sneezry** [comment]
I cannot repo on my side, could you provide more details how to repo?

https://www.useloom.com/share/3f38da9ce54d497ba58a56c8b809b377

**Comment by mymindstorm** [comment]
![image](https://thumbs.gfycat.com/SkinnyHelpfulBrownbutterfly-size_restricted.gif)

Secret 1 gets completely replaced by secret 2

**Comment by Sneezry** [comment]
I'll check if it is a Firefox specific issue

**Comment by mymindstorm** [comment]
I can repro in chrome

**Comment by Sneezry** [comment]
Maybe issue related with cookie, I'll test it on my side.

**Comment by mymindstorm** [comment]
It's not an encryption issue, I retested with completely unencrypted secrets

**Comment by mymindstorm** [comment]
Secret 1:
```json
{"22e991a1711a51f8aab522081666b5d3":{"account":"test@security-totp.appspot.com","hash":"22e991a1711a51f8aab522081666b5d3","issuer":"","secret":"A3MUFPMUQTCNVAAODBRONWFL3KLOFPSK","type":"totp","encrypted":false,"index":0,"counter":0}}
```
Secret 2:
```json
{"22e991a1711a51f8aab522081666b5d3":{"account":"","hash":"22e991a1711a51f8aab522081666b5d3","index":0,"issuer":"","type":"totp","counter":0,"secret":"A3MUFPMUQTCNVAAODBRONWFL3KLOFPSK","encrypted":false}}
```

**Comment by mymindstorm** [comment]
Oh wait they have the same hash

**Comment by mymindstorm** [comment]
I'm using the wrong test data, oops

**Comment by Sneezry** [comment]
This issue may need to be open...

When passphrase does not match the one used to encrypt data in main storage, the data may overwrite the storage.

import.html reads passphrase from document.cookie, and if document.cookie is empty, import.html will regards that user doesn't encrypt data, and ask storage.ts to read existing unencrypted data to merge - obviously, get no data unencrypted in storage.

It seems we cannot set cookie by calling `document.cookie="passphrase='bla bla'"` in Firefox, is there another way to cache the password in cookie in Firefox?

Also, we need disable import if the password is wrong.

**Comment by mymindstorm** [comment]
You should be able to call `document.cookie` (https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie). If it's giving you trouble you can try to use the webextension cookie api https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies

**Comment by mymindstorm** [comment]
> import.html reads passphrase from document.cookie, and if document.cookie is empty, import.html will regards that user doesn't encrypt data

Shouldn't it be checking if the entries have `encrypted: true` set and not the cookie? If the cookie is correct and `encrypted: true` is set for the codes in storage, only then should it import.

**Comment by Sneezry** [comment]
I didn't check encryption in import. Import is open from popup, and popup won't open import if the user doesn't provide a valid password. So everything should be okay when import opens. However, it seems we cannot set cookie with document.cookie in Firefox extension:

![snipaste20180222_012609](https://user-images.githubusercontent.com/1621293/36495339-dad4f29c-176f-11e8-8646-f6bab5f678f6.png)

This should split into two issues:

1. Check encryption in import.html, and stop user importing backups, or all data in storage will be overwritten
2. Find a way to cache password in Firefox

**Comment by mymindstorm** [comment]
![image](https://user-images.githubusercontent.com/27789806/36495663-9b4dcf6e-16fb-11e8-86c1-745ada408d1a.png)

**Comment by Sneezry** [comment]
My Firefox version is 58.0.2 (32-bit), how about yours?

**Comment by mymindstorm** [comment]
I think this is a scope issue. It won't let you assign cookies to the extension url.

**Comment by Sneezry** [comment]
Ooops, Chrome allows us to set cookie under extension url. Is there a way to cache data temporary in Firefox extension?

**Comment by mymindstorm** [comment]
We can use `sessionStorage` and it seems to stay after the pop-up is closed since we have background pages.

**Comment by mymindstorm** [comment]
![image](https://user-images.githubusercontent.com/27789806/36496232-435e6a82-16fd-11e8-9dfb-eb29465a4852.png)

**Comment by Sneezry** [comment]
background will be killed in idle in Chrome, but it seems Firefox will keep it. It seems sessionStorage is a good solution. I will fix the code.

**Comment by mymindstorm** [comment]
I'm not sure about this but have you tried to use `cookies.set()`? They might have removed document.cookie to make you use that

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/set

**Comment by Sneezry** [comment]
Do we need ask cached password from background then? It seems seesionStorage doesn't share with the scope.

**Comment by mymindstorm** [comment]
So it needs to use `sessionStorage` in ffox and `import.html` needs to ask for the users password if current data is encrypted and no cookie is detected if I understand correctly?

**Comment by Sneezry** [comment]
I just tested with browser.cookies, it works, but some workaround need to do:

1. browser.cookies requires cookies permission
2. browser.cookies does not allow set cookie under extension url, either. So we need to save the password under other url, such as https://127.0.0.1

If we save the password into sessionStorage, we need talk with background. In fact, we needn't save it in sessionStorage, we can just save it in memory - simple a variable

Which way is better in your opinion?

**Comment by mymindstorm** [comment]
I'm partial to saving it as a variable since it looks like other extensions with the right permissions can read our cookies if they want to using [cookies.get()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/get) if they know where to look.

**Comment by Sneezry** [comment]
Yeah, then let's save password in background.

**Comment by Sneezry** [comment]
This issue should be fixed now.

**Comment by mymindstorm** [comment]
Confirmed fixed
