### ISSUE TITLE
Cookies also delete settings.

### ISSUE THREAD

**Issue by ghost** [Authenticator-Extension/Authenticator#292]
**Describe the bug:** Autofill feature is disabled when I delete cookies in Firefox.I have to set again Autofill feature every time.

**Platform:** <This is required>
 - Browser: [Firefox Quantum]
 - Browser Version: 65.0.2 (64 bit)

<details><summary>Screenshot:</summary>

![auto](https://user-images.githubusercontent.com/34379403/53677297-a4550980-3cbe-11e9-95f4-6e7c92264837.png)

</details>

**Comment by mymindstorm** [comment]
We store settings that aren't part of secret data in `localStorage`. When you clear cookies in Firefox it looks like it clears `localStorage` too. We can't really do much about this. It might be more appropriate to file in bugzilla as clearing cookies deletes extension data.
