### ISSUE TITLE
resizing popup does not enlarge viewport

### ISSUE THREAD

**Issue by aleqx** [Authenticator-Extension/Authenticator#293]
Resizing the popup does pretty much nothing, really. The viewport remains the same regardless of the new size of the popup window. The idea (I thought) was so I can see more entries, but that doesn't work.

It would also be nice if we could edit the css of the page. I for one have no use of the big fonts, etc, and would rather have as many entries as possible so i can click directly, instead of scrolling/searching through all of them.

Cheers!

**Comment by mymindstorm** [comment]
The only way to change the size of the page is through the scale dropdown. If you edit `localStorage.zoom` you can set a custom value. The stylesheet is not responsive. If you want to edit the stylesheet you're going to need to build your own version of the extension.

Stylesheet here: https://github.com/Authenticator-Extension/Authenticator/blob/dev/sass/popup.scss
