### ISSUE TITLE
I fully translated for Catalan and Spanish on Crowdin

### ISSUE THREAD

**Issue by caos30** [Authenticator-Extension/Authenticator#296]
Hi, this piece of software is great!! Wonderful work!! I hope i will collaborate improving it from now :-)

I've completed the translations on Crowdin for Catalan and Spanish (both native languages of mine). I think that i must communicate here (on Github) to be included in the next build of the extension.

In fact, i've fixed several minor not-well-formed phrases. 

Thanks a lot!
Sergi

**Comment by mymindstorm** [comment]
Hi Sergi,

First of all, thanks for helping translate Authenticator. You don't need to raise an issue here to get translations in the latest builds, as I always update the translations before a release. If I missed any translations please let me know. I've also given you proofreader permissions on Crowdin.

**Comment by mymindstorm** [comment]
Version 5.3.0 is rolling out, your contributions should be there. I redid the stylesheet, so there may be some text overflow issues I didn't catch. If you see any please tell me.
