### ISSUE TITLE
Feedback Page Comes up automatically and is confusing users - can it be removed?

### ISSUE THREAD

**Issue by larrymac41** [Authenticator-Extension/Authenticator#298]
**Describe the bug:** Can we disable the feedback page?  We cannot deploy to thousands of users with the additional page coming up.  We are running Windows 10 with the Chrome browser. 

**Platform:** <Windows 10>
 - Browser: [Chrome
 - Browser Version: Version 72.0.3626.121 (Official Build) (64-bit)

Thank you!

Larry

**Comment by mymindstorm** [comment]
If you're willing to make your own build all you need to do is remove this section:
https://github.com/Authenticator-Extension/Authenticator/blob/a56a94a41d2c1db3fc6299f3549eeedda49fac3d/src/background.ts#L267-L289

Otherwise I can throw together some policies if you'd rather that.

**Comment by mymindstorm** [comment]
Version 5.3.0 has some policies you can use. It should be available in a few weeks/days, see https://github.com/Authenticator-Extension/Authenticator/wiki/Policy-Configuration for more info.
