### ISSUE TITLE
Token with and 7 digits codes

### ISSUE THREAD

**Issue by emericv** [Authenticator-Extension/Authenticator#300]
Hello, It's not possible to add a token with and 7 digits codes (used with some services).
Result : the interface display 6 instead of the 7 digits
Thanks in advance :)

 - Browser: Firefox
 - Browser Version: NA

**Comment by emericv** [comment]
Similar issue onkeepassxc to illustrate: https://github.com/keepassxreboot/keepassxc/issues/1762

**Comment by mymindstorm** [comment]
Duplicate of #287
