### ISSUE TITLE
manual entry ui improvements

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#306]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>
<You can also open an issue by Tweeting with #AuthenticatorFeedback>

- Text boxes should be for issuer and secret, not account name and secret. It's far more common to have a different issuer than a different username. I don't really like how Google Authenticator does it that way.
- Account name should be replaced with username, since that terminology is more common (in English at least).
- An advanced settings accordion should be added so we can hide account type and period settings under it

I'm pretty sure a user complained about the first two points at least once.

**Comment by firekod** [comment]
Better make 3 fields:
issuer
secret
account name
