### ISSUE TITLE
Error updating from 5.2.2 to 5.3.0

### ISSUE THREAD

**Issue by isumairu** [Authenticator-Extension/Authenticator#307]
The title is pretty much all the detail I know.
![err](https://user-images.githubusercontent.com/16854686/54925314-a10d1080-4f40-11e9-8183-7360694ff61e.JPG)

Platform:
 - Browser: Firefox x64 on Windows 10
 - Browser Version: 66.0
![ab](https://user-images.githubusercontent.com/16854686/54925417-d6b1f980-4f40-11e9-83e2-315500254bba.JPG)

**Comment by mymindstorm** [comment]
What does it say if you try to use the link [here](https://github.com/Authenticator-Extension/Authenticator/releases/download/v5.3.0/firefox-5.3.0.xpi)?

**Comment by isumairu** [comment]
![wo](https://user-images.githubusercontent.com/16854686/54936538-40d49980-4f55-11e9-8bfc-badd8afe724c.JPG)

**Comment by isumairu** [comment]
Update: Fixed.
The issue is caused by my disk's permission, I needed to run Firefox as an admin for the extension to be installed.
Thank you for this extension 👍
