### ISSUE TITLE
Donation Address to support development?

### ISSUE THREAD

**Issue by KharmaScribbles** [Authenticator-Extension/Authenticator#309]
I've searched High and Low but did not come across an address or place for submitting donations in support of development.  I understand the devs might not be in this for money and it's probably only a side gig anyways but how can I show my appreciation better than just saying Thank You?

Why? [TL;DR- **I know these days people hate reading on the internet, so you can stop here at this point because all I want is an address to donate/tip with either crypto or fiat because I really love this extension and want it to be around for awhile still and maybe even improve..
If you really care and want a testimonial, continue to read my _"wall of text"_ below**]

_I use a Chromebook and don't own a Smartphone. My Chromebook supports Android but most authenticator apps in the Play Store aren't configured for Chromebooks so the install option is not possible._

_I only ever found one other 'trustworthy' extension to use for 2FA auths, unfortunately, I began using that one first because this project, Authenticator, seemed so basic by looks and with such a basic name? So, I used a different one but always had this extension installed just 'disabled' all this time._

_The extension I first started using became bulky and I ran into a problem where a site only provided a QR code and no manual entry code for 2FA activation: even after contacting support.  When I first contacted them explaining I couldn't scan the QR code and asked them to supply me the code for manual activation, they had no idea what I was even talking about, went on to explain how 2FA worked and insisted that they had no way of accessing the codes and I needed to provide the code from my authentication app.  🙄_  
 _They seemed completely blindsided by the fact that I couldn't scan the QR code. I had to screenshot a site showing what I meant: the QR code with a manual code somewhere on the page usually with the tag line "having trouble scanning? Enter this code manually in your authenticator app: xxxx"_

_Anyways, so that was when I really started evaluating the extension I was using.
Then, after powerwashing my Chromebook and re-syncing my Chrome browser one day, my extension started asking for a password I know I never made, because 1) I didn't put it in my password manager and 2) I purposely did not set a password because I remember reading on their GitHub how people left and right were getting 'locked out' because of failed password attempts and being stuck with an encrypted authenticator._  
_Funny thing is that so many people were claiming they had never set up a password either. Of course, the devs chalked it up to user error and told them to keep trying to remember the password otherwise they are SOL.._ 
_That was the main reason I purposely made sure to never set up a password with it, because I too thought people were just forgetting them.. 
Well.. seems the users were right afterall?_

_So trying to cut this long story - ah, medium length - I used my backup codes but instead of starting 2FA over again with that same extension - I decided to give this one a try.  I set up a password, recorded the password in my LastPass, and also have saved various backups..I should be good to go avoiding my previous blunder now hopefully._ 

_I noticed right away though how quick and easy this extension makes the 2FA process in comparison to the competition.. This 'basic' UI that first turned me away has been a blessing, the simplicity of it all and how easy it makes the login flow has encouraged me to turn on 2FA for a lot more sites that I wouldn't have bothered with before due to the inconveniences, especially at login time.  This extension makes login times a breeze though!_

_I absolutely love love love this extension and being able to compare with what else is out there; especially in my small market of Chromebook power users without a Smartphone;  I would hate to ever lose this app anytime soon.  I would love to see it improved with dark mode and other features I've already seen suggested around here.._

How can I buy you a coffee? Would love to tip in Crypto but fiat links would work just as well :)

**Comment by Sneezry** [comment]
Thanks for your feedback. I'm really glad to learn this extension helps you a lot. Please use it for free, and no donation needed. If you like, you can donate to projects really need donations, such as Wikipedia.

If you have any question or feature request, please let us know. We are always happy to give a help.

**Comment by mymindstorm** [comment]
Thanks for the nice message! While we don't accept donations, we always welcome bug reports, feature requests, translations, and code. 

I actually used to only have a Chromebook. I've moved to having a real laptop now, but I completely understand what you mean by Authenticator being indispensable for your demographic. That's one of the reasons why I started helping out here.
