### ISSUE TITLE
Release 5.0 Tracker Bug

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#31]
Is there anything else major to finish before merging and deploying 5.0.2? I think what we have is pretty solid for a release.

**Comment by Sneezry** [comment]
We need test it ourselves for days, and then publish a public preview version. The build number may increase fast, and it may be not a release version.

**Comment by Sneezry** [comment]
5.0.4 would be a stable version for public, do we still have anything need to do? If all things go ready, maybe we can release 5.0.4 on March 3rd

**Comment by mymindstorm** [comment]
I don't think so. Before we release, though I would like to test it with
broken data one last time just to be safe. I think I'm also going to add
documentation on what to do when users see a white screen.

On Mar 1, 2018 9:40 AM, "Zhe Li" <notifications@github.com> wrote:

5.0.4 would be a stable version for public, do we still have anything need
to do? If all things go ready, maybe we can release 5.0.4 on March 3rd


You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/Authenticator-Extension/Authenticator/issues/31#issuecomment-369631861>,
or mute the thread

**Comment by Sneezry** [comment]
OK, then let's release it later. Do we have white screen issue in current version (5.0.3)?

**Comment by mymindstorm** [comment]
No issues that I know of, we can release on 3rd, just want to make sure we didn't forget to put a check somewhere. No white screen issues, but if a user runs into that I want them to put logs in the report before asking.

**Comment by mymindstorm** [comment]
Give [wiki/Getting-Debugging-Information ](https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information) to anyone you need to get to give logs.

**Comment by Sneezry** [comment]
@mymindstorm Please create 5.0.4 release from release branch

**Comment by mymindstorm** [comment]
Done
