### ISSUE TITLE
A way to show the code for manual entries as well

### ISSUE THREAD

**Issue by NinjaTurtle007** [Authenticator-Extension/Authenticator#310]
It seems to auto show just the code for sites where you've entered the secret with the QR code scan. 
That doesn't work for manual entries as it doesn't match it to the site.
However I'm sure there is something specific we need to enter when manually entering a secret to make it match to a site.
What is it?

**Comment by Sneezry** [comment]
Add an issuer for the entry, and the entry will match the site with the same name.

**Comment by NinjaTurtle007** [comment]
wow indeed!
Thank you!
