### ISSUE TITLE
scanning of QR does not seem to work on site starting with file:///  

### ISSUE THREAD

**Issue by hmakmur** [Authenticator-Extension/Authenticator#312]
Scanning QR codes in local webpage starting with  file:/// does not seem  work.

**Comment by mymindstorm** [comment]
Are you using Chrome? You need to go into chrome://extensions => details for Authenticator => enable 'Allow access to file URLs'

**Comment by hmakmur** [comment]
Sorry, I did not see that. Thanks for your quick response!
