### ISSUE TITLE
Plus sign in QR code not properly converted space

### ISSUE THREAD

**Issue by ericsnap** [Authenticator-Extension/Authenticator#313]
**Describe the bug:**
When capturing a QR code where the URL contains a `+` within the issuer, it does not convert it to a space as the specs states (for _query parameters_ not path elements).
The following QR code generates the entry `ACME+2FA` instead of `ACME 2FA`.

![qr code with plus sign](https://user-images.githubusercontent.com/16297214/55646565-b8e26100-5798-11e9-8e14-2f0c12777fb6.png)

![Screen Shot 2019-04-05 at 11 39 08 AM](https://user-images.githubusercontent.com/16297214/55646545-a9fbae80-5798-11e9-8dea-db662681138c.png)

This URL was generated using JavaScript's default `URL` class.

It also displays without the `+` properly in several other apps like Microsoft and Google's Authenticator apps.

I will look into the code and see if I can figure out where it is and submit a PR... that doesn't seem like rocket science.

**Platform:**
 - Browser: `Chrome`
 - Browser Version: `73.0.3683.86 (Official Build) (64-bit)`

**Comment by mymindstorm** [comment]
This should be the function you'll want to edit if you'd like to make the PR:

https://github.com/Authenticator-Extension/Authenticator/blob/c9fda310af83ca1da972657c0df93b364bf169cd/src/background.ts#L60
