### ISSUE TITLE
Investigate autofill issue

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#324]
@mymindstorm 

It _does not work at the first login after the FF browser been restarted_. Once logged the manual way and logged out _and then logging in again it does work_, which seems curious.

_Originally posted by @n8v8R in https://github.com/Authenticator-Extension/Authenticator/issues/253#issuecomment-484474598_

**Comment by ghost** [comment]
@mymindstorm 

Been able to narrow it down a bit.

It seems to be related/correlated to the decryption feature of the WX. Having encryption enabled and (re)starting the FF browser autofill/key events would not work on the Discourse platform on the first go.

However once having successfully logged into any account with the assistance of this WX and in due course having entered the password for decryption _any subsequent autofill/key events do work_ on the Discourse platform.

**Comment by mymindstorm** [comment]
I still can't get the bug to happen on forum.openwrt.org after about ten tries. My process is roughly:
- Logout
- Start and navigate to site
- Hit login
- Login to site
- Login to authenticator and autofill in one session
- hit login
- Close browser and retry

I made you a special build with a fix I think will fix it and some extra debugging info. If the code doesn't appear follow [this](https://authenticator.cc/docs/en/debug-info) and send me the output from it failing to input a code. There will be more in the website's console that you should send too.

[firefox.zip](https://github.com/Authenticator-Extension/Authenticator/files/3105385/firefox.zip)

**Comment by ghost** [comment]
@mymindstorm 

Thank you for the extra effort but the special build does not install as FF citing that it has not been verified and it points to https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct
___
My assumption about the decryption is wrong. For that I removed the encryption and restarted the FF browser and the issue is present if the first login (after browser start) is on a Discourse platform.
Any subsequent login _after a first successful login at any platform_ works then.

Not sure whether it is worth to spend more time/effort on this since I know how to work around if the first login is on a Discourse platform.

**Comment by mymindstorm** [comment]
@n8v8R unzip => about:debugging => Load temporary addon => manifest.json

I'm just curious what's causing it at this point. It's probably not injecting the content script properly. That is definitely the issue if the code isn't pasted at all when it doesn't work. 

After you load it, run it on a page and if it doesn't work, load that page's (not the extension's) console up and see if there is any output (not from the website itself). Note that it will probably unload the temp build on restart.

**Comment by ghost** [comment]
> special build with a fix I think will fix it

Yes, it does fix the issue indeed and that build is not exhibiting the issue.

**Comment by Riajyuu** [comment]
@mymindstorm Just a small question here:

Are you guys implementing full autofill like [mine](https://github.com/foxauth/foxauth) does, or context menu filling or something else more specific.

**Comment by Sneezry** [comment]
@Riajyuu here's how we handle autofill: https://github.com/Authenticator-Extension/Authenticator/blob/dev/src/content.ts#L176

**Comment by Riajyuu** [comment]
@Sneezry 
well
it's much less hacky but also much less universal.

any plan to make it a bit universal?

**Comment by mymindstorm** [comment]
@Riajyuu excluding looking for the input box, adding a bubbling `input` and `changed` event fixes the sites' input boxes not wanting to recognize the updated input. Not exactly sure what you mean by universal?

**Comment by Riajyuu** [comment]
> excluding looking for the input box, adding a bubbling `input` and `changed` event fixes the sites' input boxes not wanting to recognize the updated input

As you see, Google, M$, Yandex and many more sites are supporting multiple accounts. Also, some sites (afaik, Twitter, V2EX, Epic Games) do use login account name as OTP account name param.

So I wonder if you guys have anything to do with those cases, or perhaps you can find any better matching solution than mine?

**Comment by mymindstorm** [comment]
We filter by site and only autofill when the user clicks a code. It isn't the best solution, but it's better than guesswork.

I tried to test out your solution, but I couldn't get it to work. Not sure if I'm doing something wrong. I added an account manually since I couldn't get the QR scan to work, it looks like [this](https://user-images.githubusercontent.com/27789806/58037879-1a198600-7af4-11e9-80fe-58647d50a2ca.png). Then I clicked the autofill button and it didn't really do anything either. I tried both the right click and menu buttons on [this website](http://security-totp.appspot.com/).

**Comment by Riajyuu** [comment]
If you are using appspot test demo, current autofill code is supposed not working. As I first try to catch login account name: nothing will be filled if no account name is catch. This avoids some unnecessary  autofill (like Twitter without logging in).

And Yes, I have to say my current work looks pretty similar like guesswork. But it is already the quickest implement to full auofill I can find now.

Hope you guys can find anything better.

**Comment by mymindstorm** [comment]
@Riajyuu it's a really convenient system when it fills codes though. Github doesn't even put the username on the 2FA page so it must be pretty hard to get the username for some sites.

**Comment by ghost** [comment]
> I still can't get the bug to happen on forum.openwrt.org

v5.3.2 on FF 69.0a1 (2019-07-06) (64-bit) it does not work on my node.

It has actually gotten worse in a way that upon the first copy/paste process manually deleting and retyping the last character does not provide a login, a workaround that used to work.
Now a requires a second pass of copy/past _plus_ manually deleting and retyping the last character.

**Comment by mymindstorm** [comment]
I honestly have no clue at this point. It _was_ working, but I assume they updated it. I really don't want to dig through Discoure's source to figure out what magic sequence has to happen for it to register Authenticator's input.

**Comment by mymindstorm** [comment]
Oops, I was using the wrong build and the wrong secret. It still does work fine, but the fix isn't out yet. 5.3.2 was just a one line change. I have been working on #352 and waiting until that's fully done before making any more updates.

**Comment by ghost** [comment]
Whilst development seems stalled since July 2019 here [1] is another case where autofill does not work (neither with GC or FX)

[1] https://www.virustotal.com
![Annotation 2019-11-14 080610](https://user-images.githubusercontent.com/13611490/68834275-ab3d7400-06b5-11ea-956c-aae403781c03.png)

**Comment by mymindstorm** [comment]
It hasn't, this has already been fixed. I'm waiting on #395 (and planning to investigate #399) before pushing the update that fixes this. #395 has a lot of changes, so it will take time to review.
