### ISSUE TITLE
Cookie problem

### ISSUE THREAD

**Issue by U1s2e3r4n5a6m7e** [Authenticator-Extension/Authenticator#325]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 
Settings resetting when I clean the browser cookies. Can you fix the issue for this extraordinary extension ? 😞

**Platform:** <This is required>
 - Browser: Firefox
 - Browser Version: 66.0.3 (64 bit)

**Comment by mymindstorm** [comment]
We store all data that isn't part of a code in `localstorage`. You need to file a bug in Bugzilla to get Firefox to stop clearing extension local storage when clearing cookies.
