### ISSUE TITLE
Recover Keys

### ISSUE THREAD

**Issue by drthaxx** [Authenticator-Extension/Authenticator#329]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <During Windows Updates there was a failure and I had to restore my PC a day before . but when i opened the chrome most of my keys were lost. Is there a way to restore them. > 

**Platform:** <Windows 7>
 - Browser: [Chrome,]
 - Browser Version: 74.0.3729.157

**Comment by mymindstorm** [comment]
Do you have a backup? If yes restore from it. If no refer to the message that you should have seen when making this issue.

> Do not use this to ask about lost codes or accounts
> More info here: https://authenticator.cc/docs/en/lost-codes
