### ISSUE TITLE
Command line option?

### ISSUE THREAD

**Issue by ivulfson** [Authenticator-Extension/Authenticator#331]
Here's an idea: a command line version of the authenticator.  This would work from the .json file that can be exported from the extension.  The command line tool takes 2 arguments: 1) .json filename, and 2) which account (or issuer) to use.  It would just display the current code and exit.

```
$ authenticator --json ~/backup/authenticator.json --account $USER@gmail.com
123123
$
```
Maybe another option to specify time remaining - it less than N seconds remaining on the current code, sleep until it rolls over to the new number.

Uses:

Assign keystroke to this command:
```
authenticator --json ~/backup/authenticator.json --account $USER@gmail.com | xclip -in -selection clipboard
```
Hit a hotkey, and current code is copied to the clipboard.  Then you just paste it where it's needed - saves 2 mouse clicks? :)

Another use is using the current code in other command line tools.  For example, I have a script to connect to my work VPN, which uses 2FA.  I have to go to Chrome, copy the current auth code, back to command line and paste the code to the script, and then the script connects to VPN.  Having a command line tool just give me the code would make it simpler.

Why don't I want to switch to using a full-time command line tool for this? Well, because sometimes I need it on a Windows box, and having a browser extension is much better.

Just a thought, doesn't hurt to ask. :D

**Comment by mymindstorm** [comment]
That would be nice, but I don't really have the time to make something like that right now. We are trying to make the format for our backups more open, which I have documented [here](https://authenticator.cc/docs/en/otp-backup-developer). If you'd like to make something like that I'd be happy to help you out.

**Comment by mymindstorm** [comment]
Also, I'm pretty sure utilities like that already exist, you could always just extend the functionality of one of those tools.

**Comment by ivulfson** [comment]
Excellent, thanks for the pointers.  I'll take a look around. :D  Keep up the good work, your app is helping people every day.

**Comment by ivulfson** [comment]
Well, this was much easier than I thought:

https://github.com/robbiev/two-factor-auth

Once you compile it, run:

```./main SECRET```

Where `SECRET` is the 32-char value of "secret" key in the .json file generated by this extension.  It prints the current code and how many seconds are left on it.  Example [obfuscated]:

```
$ ./main SECRET
071998 (4 second(s) remaining)
$ sleep 5
$ ./main SECRET | cut -d' ' -f1
142296
$
```

I'm going to tweak the code to read the secret from the .json file, and to wait for N+1 seconds it the code is about to timeout in N seconds, with some default value (maybe 5 seconds).  That'll give me more than enough time to either paste it somewhere, or run another script to connect to VPN or whatnot.

Anyway, I thought someone might also find it useful as is.
