### ISSUE TITLE
Remove old edge code from codebase

### ISSUE THREAD

**Issue by netandreus** [Authenticator-Extension/Authenticator#332]
**Describe the bug:**
After click on scan icon nothing happens. Scan does not work.

**Platform:** 
 - Browser: Edge
 - Browser Version:  44.17763.1.0 EdgeHTML version: 18.17763
 - Extension version:  5.3.1 (from Microsoft store).

After click on scan icon appears message "Capture failed, please reload the page and try again." After second click nothing happens. In console this message appears:
API Call: 'runtime.onMessage'.

**Comment by mymindstorm** [comment]
I've asked for an update from Microsoft. Still works with stable builds of Windows.

**Comment by Sneezry** [comment]
FYI, Microsoft has released [Edge Insider](https://www.microsoftedgeinsider.com/en-us/) which is based on Chromium. If you'd like, this new Edge is another option. And you can install Chrome version on the new Edge.

**Comment by mymindstorm** [comment]
I think I'll disable scan functionality in (old) edge with an update targeting the affected windows build and above and branch it. Past that, I don't think we should support old Edge any more. Will also remove all those overrides from the main branch.
