### ISSUE TITLE
Reconsider Mobile Support

### ISSUE THREAD

**Issue by Riajyuu** [Authenticator-Extension/Authenticator#335]
Literally one year ago, I brought out #213 here to expect Firefox Android support but denied. At that time, Firefox Android is the only mobile browser with WebExt support.

Now we have kiwi browser as another Android browser with Chromium supporting WebExt, especially Edge mobile is considering this as well. So I think it is now a proper time to revisit this issue.

As for my side, we do have plan for a Chromium support but will surely take really looooong as a lot of features are still missing, a trunk of necessary improvement and some significant logic changes (many codes targets Firefox too far so very hard to implement on Chromium).

Of course, maybe collaboration is a way but we seems to have different philosophy: we intend to bring as simple & easy management as we can and we have a lot of compatibility code with Firefox Android.

**Comment by Sneezry** [comment]
There has already been many 2fa clients for mobile platform, and we would not like to make another wheel. May I ask what is your scenario to expect Android support?

**Comment by Sneezry** [comment]
It is great to provide more options to users. If you have plan to support Chromium, no matter on PC or mobile platform, I'm very glad to see that happen :-D

**Comment by Riajyuu** [comment]
@Sneezry the reason is quite simple: syncing.

indeed many app on android, but none syncs except authy. but authy wants your cellphone and refuses open platform like dropbox so I started foxauth. 

So foxauth is also trying balance security and convenience

**Comment by mymindstorm** [comment]
@Riajyuu I'm a bit more concerned on the security side for mobile. I think it makes more sense to push a native app in that respect. On that front, FreeOTP+ seems to have added support for the standardised OTP backup format. The browser sync systems are a bit finicky anyway.

**Comment by bittner** [comment]
My interest in this topic, apart from syncing, is that I don't want an app just for OTPs. Most OTPs I use is on websites, hence it's natural for me to be using Firefox anyway when I need access to a login token.

Also, Authenticator automatically filters my OTP entries based on the website I currently visit, which is something OTP apps don't do.

**Comment by AntonioRedondo** [comment]
Adding support for Firefox Mobile wouldn't be adding yet another OTP app on Android. I don't see it in that way.

By taking advantage of the already developed Authenticator in the desktop, I'd assume that adapting it to mobile should not bit a big task (let me do this assumption for a second 😄), and hence we would enjoy a tightly integrated OTP functionality on Firefox Mobile, browser which is where I always use my OTP codes.

Most importantly, **I would have all my OPT codes synchronised in both desktop and mobile installations thanks to the Authenticator's _Browser Sync_ preference.**

I never use any external OTP app like Google Authenticator. This extension is better integrated in my opinion, and it's open-source.

**Comment by benjaminoakes** [comment]
For what it's worth, it seems to _mostly_ work on Firefox for Android if the "use desktop site" workaround is used to install the add-on within Firefox for Android.

**Edit:** The first load requires zooming in via pinch.

**Comment by AntonioRedondo** [comment]
Yeah, actually using the desktop Firefox add-ons website allows to install Authenticator on Firefox Mobile.

It has two issues though:
- The interface doesn't take the whole screen. ➡️ Not really a big deal. You can pinch in. 👍
- Browser Sync functionality with the codes from Firefox Sync doesn't work. ➡️ This is a big deal. 😢

<img src="https://github.com/Authenticator-Extension/Authenticator/assets/5444421/7ff963d8-73b5-4bb0-b27b-1ae59668efd9" width="200" />

**Comment by saona-raimundo** [comment]
I tried installing the Authenticator add-on in my mobile by visiting the desktop Firefox add-ons website.
It does install, but then it shows nothing (blank page).
My interest is in syncing and simplicity (phone working as similar to the pc as possible).
