### ISSUE TITLE
How to recover Authenticator Account name and Secret 

### ISSUE THREAD

**Issue by vinhk** [Authenticator-Extension/Authenticator#338]
Hi,

Previously, I used Authenticator to authenticate a website. It was working and I was able to log on. But recently, I do not see any account on the Authenticator extension. Now I am having trouble remembering the Account and Secret for this website. Is there a way to access it again so I can see the generated code for that website?

**Comment by mymindstorm** [comment]
Do you have a backup? If not then there isn't really much I can do (unless it disappeared because of a bug). Refer to https://authenticator.cc/docs/en/lost-codes
