### ISSUE TITLE
Seems Dropbox auth breaks in Chrome on Windows

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#339]
I will make further confirmation.

![Snipaste_2019-06-10_16-49-08](https://user-images.githubusercontent.com/1621293/59184037-cef90d00-8b9f-11e9-9115-e00e93edf967.png)

**Comment by mymindstorm** [comment]
Looks like the client id is missing. Did you build it yourself or grab the build from travis? Self builds don't decrypt the client credentials.

**Comment by Sneezry** [comment]
I built it on my machine. I will test travis built version.
