### ISSUE TITLE
Dropbox setting UI

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#34]
Currently we have two buttons in different size on Dropbox setting UI, how about changing the big one into a link and move it next to Dropbox code label?

![snipaste20180224_003112](https://user-images.githubusercontent.com/1621293/36604992-54f8bdde-18fa-11e8-9d14-9befdda21708.png)

**Comment by mymindstorm** [comment]
Moving it like that would break from what we are doing with all our other links. I think you should either:

- Move it how you are saying, but change it to use a verb like "Login to Dropbox" or "Get Dropbox Code" to make it more obvious what the button does
- Make the button less obvious by making it's height smaller

**Comment by mymindstorm** [comment]
I don't really want to break from what we are doing currently with everything else but I  think you are right.

**Comment by Sneezry** [comment]
how about move it into the input box? https://jsbin.com/femeda

**Comment by mymindstorm** [comment]
That works perfectly, yay for context
