### ISSUE TITLE
CODE INVALID!!

### ISSUE THREAD

**Issue by KiranaPutriAzazel** [Authenticator-Extension/Authenticator#341]
I just changed Windows 7 to Windows 10, I logged in Google Chrome account on Windows 10 and synchronized all data including Authenticator. There is a problem with all of my Authenticator codes being invalid! Is there any solution?

I have no data backup because I haven't had time to export data!

**Comment by Sneezry** [comment]
Is your clock correct? Try `settings` -> `Sync Clock with Google`. Your data is safe, and you can make a backup from settings menu now.

**Comment by KiranaPutriAzazel** [comment]
caution your local clock is far please fix it before continuing

**Comment by KiranaPutriAzazel** [comment]
![image](https://user-images.githubusercontent.com/46416083/59595552-3d9a1580-9120-11e9-88a3-72c4b50918a3.png)
succes now, but code still error/ invalid

**Comment by KiranaPutriAzazel** [comment]
OMG work!!! Thank you Mr. Zhe Li!
