### ISSUE TITLE
 not work to see the code of presearch and coinbase

### ISSUE THREAD

**Issue by salvador77** [Authenticator-Extension/Authenticator#343]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 

**Platform:** <This is required>
 - Browser: [Chrome, Firefox, Edge]
 - Browser  not work to see the code of presearch and coinbase

**Comment by Sneezry** [comment]
Please provide more details.
