### ISSUE TITLE
Restore cleartext bug: Entries with the same secret key only imported partially

### ISSUE THREAD

**Issue by ghost** [Authenticator-Extension/Authenticator#344]
I am building a bash converter for syncing AndOTP and Authenticator. For this task i've made two test entries in the test import file authenticator.txt

otpauth://totp/TEST?secret=1234567812345678&issuer=TEST
otpauth://totp/TEST2?secret=1234567812345678&issuer=TEST2

Importing this text backup will only import TEST2. TEST ist lost.

Now change the first line to:
otpauth://totp/TEST?secret=1111111111111111&issuer=TEST

Try importing again is successfull - both test entries will be restored.

I assume this happens because unique entries are identified by the secret key too.

Regards.

**Comment by mymindstorm** [comment]
Wontfix, we identify by hash of secret; importing with the same secret will overwrite old data.

**Comment by ghost** [comment]
Agree.

Probability that hash of non manually generated secrets is going to zero.

Am Mi., 26. Juni 2019 um 01:06 Uhr schrieb mymindstorm <
notifications@github.com>:
