### ISSUE TITLE
Feature Request: Import/Export cleartext/encrypted backups from and to AndOTP

### ISSUE THREAD

**Issue by ghost** [Authenticator-Extension/Authenticator#345]
I've installed lately LineAgeOS at my mobile to get rid from Google's Android. In the open source app store http://f-droid.org you find several otp solutions and decided to install AndOTP as a good solution.

My target is a open source solution for OTP at my mobile and would like to sync with Authenticator as a solution for my open source linux desktop.

Would be nice to have a import function for AndOTP backups and the way around exporting Authenticator to AndOTP format.

Regards.

**Comment by mymindstorm** [comment]
We don't support importing other formats at the moment. Consider asking them to support our data exchange format. https://authenticator.cc/docs/en/otp-backup
