### ISSUE TITLE
Mistyping encryption password and generating HOTP code causes data corruption

### ISSUE THREAD

**Issue by sfalvey** [Authenticator-Extension/Authenticator#348]
**Describe the bug:** Mistyping encryption password prevents future use of counter based code

Steps to recreate
1. Start browser normally, use correct unlock password for authenticator
2. Create a counter based code
3. Quit browser
4. Start browser normally, use incorrect password for authenticator
5. Click the counter based passwode note it will respond with "Encrypted"
6. Quit browser
7. Start browser normally, use correct unlock password for authenticator
8. All time based codes will no longer say "Encrypted" but counter based one clicked above never works again. Only option is to reregister which with a counter based means tons of clicking to get the code to one that can be used again.

**Platform:** MacOS
 - Browser: Firefox
 - Browser Version:  67.0.4

**Comment by mymindstorm** [comment]
The data only gets corrupted when you click the button. Just getting the password wrong won't corrupt the secret data for that account.
