### ISSUE TITLE
QR code scan error on Firefox

### ISSUE THREAD

**Issue by webmihir** [Authenticator-Extension/Authenticator#351]
On Firefox (Windows 10), when I am previewing a PDF file and click on the scan QR code button in Authenticator, I get the following error message:
"Capture failed, please reload the page and try again."

Platform: Windows 10
 - Browser: Firefox
 - Browser Version: latest

**Comment by mymindstorm** [comment]
The extension can't access PDFs due to what looks like a bug with Firefox extension permissions. To work around either take a screenshot of the QR, preview that in Firefox, and then scan the QR or just enter the secret manually.

**Comment by mymindstorm** [comment]
Closing, Firefox blocks content scripts on PDF previews intentionally. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1454760
