### ISSUE TITLE
sync not working

### ISSUE THREAD

**Issue by Rik44444** [Authenticator-Extension/Authenticator#355]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 
hi all, sync is not working for me. I installed Authenticator on my desktop and my laptop, using Firefox on both, and after several times syncing, the codes have still not shown up on my laptop (i inputted them on my Desktop). I checked: i am logged in correctly, 'sync' is checked in the Storage and Backup option tab, and other things sync fine (eg tabs). 

**Platform:** <This is required>
 - Browser: [Chrome, Firefox] Firefox
 - Browser Version: 68.0 
Windows 10 PRO
for both computers

**Comment by mymindstorm** [comment]
It takes a while and is finicky sometimes. You can force it to sync using the three bar menu and clicking the button to the right of your name. Make sure extension data is getting synced. I can't really do much about Firefox being dumb. If you really want the data, you can export a file and import that on the other computer.

**Comment by Rik44444** [comment]
they just appeared!! 
thanks for developing the app; pretty great to have an open source solution for this, let me know if there's anything i can do to help. 
are you planning any further features for the future?
Rik

**Comment by mymindstorm** [comment]
> let me know if there's anything i can do to help.

If you want to help you can translate, report bugs, or submit pull requests.

> are you planning any further features for the future?

Everything being considered is in the issue tracker, you can look through that if you want. Everything being put into the next release is here: https://github.com/Authenticator-Extension/Authenticator/compare/release...dev
