### ISSUE TITLE
please add encryption password expiration (timeout)

### ISSUE THREAD

**Issue by aleqx** [Authenticator-Extension/Authenticator#358]
Encrypting the TOTP is a must in my opinion. However, once I decrypt the Authenticator codes, they remain decrypted for as long as I keep my browser open. Physical access to my laptop (theft, etc) would mean they get access to the TOTP codes already decrypted previously when I opened the browser.

Can you please add a password expiration feature where we can set a timer in minutes in order to protect the TOTP?

This is a basic feature of all password managers. The Authenticator extension is, in a way, also a password manager.

**Comment by mymindstorm** [comment]
Duplicate of #219
