### ISSUE TITLE
l18n strings overflow

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#36]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

**Comment by Sneezry** [comment]
There're still some more work need to do. Some string is missing, such as "Time based". Also, some Russian string is too long, and UI is broken in Russian.

**Comment by Sneezry** [comment]
![1](https://user-images.githubusercontent.com/1621293/36615707-28d21058-191c-11e8-8c28-92aa8fd8fa0c.png)
![2](https://user-images.githubusercontent.com/1621293/36615708-291276e8-191c-11e8-8e2f-d39fb1b2fd4f.png)
![3](https://user-images.githubusercontent.com/1621293/36615709-295645f8-191c-11e8-80d8-f8a248578918.png)
![4](https://user-images.githubusercontent.com/1621293/36615710-29a123d4-191c-11e8-8784-0782e97273fd.png)
![5](https://user-images.githubusercontent.com/1621293/36615712-29e769de-191c-11e8-8ea0-1837f2aa19f5.png)

**Comment by mymindstorm** [comment]
Time based string was submitted just like that, but if need be we can mark it as untranslated again. 

Are you ok with me changing it back to wrapping the text and centering things horizontally? 1e70c0961a63765e81b273087d776a8ea8cda61e

**Comment by Sneezry** [comment]
Do you mean center align text in menu, like this?

![snipaste20180224_045146](https://user-images.githubusercontent.com/1621293/36616375-7920746c-191e-11e8-9cd0-de4e6f0de4de.png)

**Comment by mymindstorm** [comment]
No, not at all. With the French translations I had one string that wrapped, and if I remember correctly the icon on the left wasn't horizontally centred, though I'm pretty sure that's fixed now.

**Comment by Sneezry** [comment]
I just hide the overflow text at https://github.com/Authenticator-Extension/Authenticator/commit/1e70c0961a63765e81b273087d776a8ea8cda61e. If the string is wrapped, some content is out of range in the popup, as we do not provide a scroll bar in settings page.

Current workaround is set a title for every menu entry.

**Comment by mymindstorm** [comment]
What about this? d2f4c6061f9696730fe2d807453cf7582ad421c2
![image](https://user-images.githubusercontent.com/27789806/36617839-a2601154-18ae-11e8-80e2-c9f50a36bcfd.png)

**Comment by mymindstorm** [comment]
Obviously the wrapping still needs some work, but the important part is the scroll bar

**Comment by Sneezry** [comment]
It should be better to show icons in a separate column
