### ISSUE TITLE
 Faucethub

### ISSUE THREAD

**Issue by maciel2017** [Authenticator-Extension/Authenticator#360]

**Comment by mymindstorm** [comment]
Please don't post personal information here, everything is public.

Have you synced your clock? If not, can you generate a new secret from that site and reproduce the behavior?

**Comment by maciel2017** [comment]
Preciso saber o email vinculado ao 2fatores pis nao recebo codigo para desativacao nao chega nos meus email preciso saber se há outro email desconhecido recebendo esses codigos. help help.

**Comment by mymindstorm** [comment]
Contact Faucethub support.
