### ISSUE TITLE
How does your app work? 

### ISSUE THREAD

**Issue by RoderickSpraguethe4th** [Authenticator-Extension/Authenticator#368]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 

**Platform:** <This is required>
 - Browser: [Chrome, Firefox]
 - Browser Version:

**Comment by RoderickSpraguethe4th** [comment]
Okay, now my Farcebook no account asks me for my six digit code, but the computer sits there inert. Am I supposed to pull it out of my ass?

**Comment by SpiritWolfe** [comment]
HEY NOW, Numbnuts ... the Devs have enough to worry about than your smart comments... here's your help. You are Welcome!

Are you SURE you are not receiving your six-digit code via TEXT OR EMAIL?!
Second, the page that you are on HAS TO HAVE a Two-Step verification process ACTIVE to work.

This link will provide you the steps you need to help you activate [Facebook's 2-Step Authentication](https://isn.page.link/78n4) process. (It even has pictures just in case your pea brain can not read!)

**Comment by mymindstorm** [comment]
Please refrain from using expletives in the issue tracker @RoderickSpraguethe4th.
