### ISSUE TITLE
Replace MD5 with SHA256

### ISSUE THREAD

**Issue by PatOnTheBack** [Authenticator-Extension/Authenticator#369]
**Describe the bug:**
Authenticator used MD5, but MD5 is vulnerable to collision attacks (https://en.wikipedia.org/wiki/MD5#Collision_vulnerabilities).
Replacing MD5 with SHA256 will mitigate this risk.

**Platform:** All
 - Browser: All
 - Browser Version: All

**Comment by mymindstorm** [comment]
closed by #395
