### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by 01aca10** [Authenticator-Extension/Authenticator#374]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 

**Platform:** <This is required>
 - Browser: Chrome
 - Browser Version: Version 76.0.3809.100 (Official Build) (64-bit)

Code not working. We added the secret key manually for 3 users (same key) for 1 team member's authenticator does not work. Is there a limit on how many times the key is used?

**Comment by mymindstorm** [comment]
The time on that person's computer is probably off. Go to them menu and hit "Sync Clock With Google"

**Comment by 01aca10** [comment]
Thank you for this.

We did try Syncing clock with Google and it still doesn’t work….


Tina Academia
Admin and Marketing Assistant
tina.academia@viewlegal.com.au<mailto:tina.academia@viewlegal.com.au>
View Legal Pty Ltd
General mail: GPO Box 681, Brisbane  QLD  4001
Secure storage: PO Box 221, Enfield LPO  NSW  2136
1300 843 900
viewlegal.com.au<http://www.viewlegal.com.au/>
[vl]
Learn more about View Communities here<https://comviewnities.com/>.

  If you have made it reading this far and have great eyesight, your ‘reward’ is what is allegedly best practice to state, even though no-one we know takes any notice … namely that this email may contain confidential or privileged information. If received in error, please delete it from your system and notify the sender.

**Comment by mymindstorm** [comment]
Have you tried re-adding the key on the computer that can't use the code? Try this:
1. Delete the broken code
2. Export a backup of a working code from someone else's computer
3. Import the code

**Comment by 01aca10** [comment]
Thanks!

It worked.

Tina Academia
Admin and Marketing Assistant
tina.academia@viewlegal.com.au<mailto:tina.academia@viewlegal.com.au>
View Legal Pty Ltd
General mail: GPO Box 681, Brisbane  QLD  4001
Secure storage: PO Box 221, Enfield LPO  NSW  2136
1300 843 900
viewlegal.com.au<http://www.viewlegal.com.au/>
[vl]
Learn more about View Communities here<https://comviewnities.com/>.

  If you have made it reading this far and have great eyesight, your ‘reward’ is what is allegedly best practice to state, even though no-one we know takes any notice … namely that this email may contain confidential or privileged information. If received in error, please delete it from your system and notify the sender.
