### ISSUE TITLE
Partial Decryption when using Cookie AutoDelete

### ISSUE THREAD

**Issue by abrahamjuliot** [Authenticator-Extension/Authenticator#379]
Not necessarily a bug. But, it certainly appears so at a glance:

Decryption password strangely only decrypts some accounts when extension Cookie AutoDelete is active.

 - Platform: Win 10
 - Browser: Chrome
 - Browser Version: Latest

**Comment by mymindstorm** [comment]
Please follow [these steps](https://authenticator.cc/docs/en/debug-info) while reproducing the bug.

**Comment by mymindstorm** [comment]
No response in over a week, closing.
