### ISSUE TITLE
Support algorithm paramater

### ISSUE THREAD

**Issue by kleena-k** [Authenticator-Extension/Authenticator#380]
**Describe the bug:** The codes generated by Authenticator for the settings URL posted below are not being accepted by a website

**Platform:** 
 - Browser: Firefox
 - Browser Version: 68.0.2 x64

The settings URL: otpauth://totp/IconParc:viktor@*anonymized*?REMOVED&algorithm=SHA512&digits=6

The site to accept it is not publicly accessible, but comparison with another generator should enable code testing.

Thank you for looking into this!
Viktor

**Comment by mymindstorm** [comment]
We don't support `algorithm` yet. Convert the secret to SHA1 or hexadecimal manually for now.
