### ISSUE TITLE
Steam Desktop Authenticator Wiki needs to be updated!

### ISSUE THREAD

**Issue by magicoflolis** [Authenticator-Extension/Authenticator#382]
The wiki page for "Getting Shared Secret from Steam Desktop Authenticator (Windows)" needs to be updated.
**Old:**
"shared_secret":"your_secret_key"
**New:**
"uri":"otpauth://totp/Steam:your_steam_username?secret=your_secret_key&issuer=Steam"

**The old method gives you an error.

**Comment by Sneezry** [comment]
Steam related wiki is beyond our control, please raise an issue at https://github.com/SteamTimeIdler/stidler
