### ISSUE TITLE
Problem with password storage, can i contribute?

### ISSUE THREAD

**Issue by mtravnicek** [Authenticator-Extension/Authenticator#384]
Hello, I noticed problem with plaintext local storage of passwords in your app.
Before I corroborate more on this, can i contribute by commiting some code in new branch (as it is easier than explaining) and i want some credit :) or is this project strictly 2 developer project?

**Comment by mymindstorm** [comment]
Feel free to submit a PR and I'll review it.On Aug 30, 2019 8:38 AM, mtravnicek <notifications@github.com> wrote:Hello, I noticed problem with plaintext local storage of passwords in your app.
Before I corroborate more on this, can i contribute by commiting some code in new branch (as it is easier than explaining) and i want some credit :) or is this project strictly 2 developer project?

**Comment by mymindstorm** [comment]
@mtravnicek do you still plan on submitting a PR? If you don't have the time, you can email me with details at [my username]@evermiss.net.

**Comment by mymindstorm** [comment]
It's been over a month with no response, closing.
