### ISSUE TITLE
Hide QR overlay on drag

### ISSUE THREAD

**Issue by wytcld** [Authenticator-Extension/Authenticator#386]
**Describe the bug:** Several users trying this with Chrome on Windows report that the overlay showing how to drag over the QR code itself gets in the way of reading the QR code, which is either then unreadable or takes multiple tries to capture.

**Platform:** Windows 10
 - Browser: Chrome
 - Browser Version: latest
![qrcrop](https://user-images.githubusercontent.com/1467471/64281968-5990a480-cf22-11e9-9b36-819c19b842fd.png)

**Comment by mymindstorm** [comment]
QR overlay is not captured on scan. You need to make sure the QR code isn't cut off (box must completely cover code). To see what the application is parsing go to the about menu, scroll all the way down, open the QR debugging page, and scan a code while that tab is open. 

I'll update the overlay to hide the tutorial gif on click.

**Comment by wytcld** [comment]
Thanks! What version may we anticipate this change in?

**Comment by mymindstorm** [comment]
Probably the next version (or whenever I get around to it). Lots of bigger changes are waiting on review, and that can take time.
