### ISSUE TITLE
Capture failed, please reload the page and try again

### ISSUE THREAD

**Issue by drivencompassion** [Authenticator-Extension/Authenticator#389]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>
<You can also open an issue by Tweeting with #AuthenticatorFeedback>

Tried reloading this page over several days and it is the only page that still gives this error: 
"Capture failed, please reload the page and try again"

https://accounts.firefox.com/settings/two_step_authentication

**Comment by mymindstorm** [comment]
Firefox accounts and addons are not allowed to be interacted with by extensions due to security reasons. Use manual entry.

**Comment by davidcsi** [comment]
I'm getting this in chrome.

**Comment by Mds92** [comment]
I have the same problem with Chrome
