### ISSUE TITLE
Alternative extension with restricted permissions

### ISSUE THREAD

**Issue by rruizt** [Authenticator-Extension/Authenticator#392]
Hello,

Right now this extension requires "Access your data for all websites" permission. I understand why this is used and I agree reading QR codes from the screen is useful, but I consider it too risky to use.

I understand that this extension going rogue would mean that the attacker could get the login information together with the TOTP token. Am I correct?

It would be nice to have an alternative extension (maybe a fork: Authenticator-lite?) that would only allow you to introduce the shared secret as plain text but it doesn't require any additional permissions.

Thank you for your work!

**Comment by Sneezry** [comment]
Hi @rruizt , do you use Chrome or Firefox or other browser?

**Comment by rruizt** [comment]
Hello!

I use Firefox.

**Comment by Sneezry** [comment]
@mymindstorm Could you explain why we ask for `<all_urls>` permission on Firefox? I remember there was a tech block issue, and we did that for a workaround. Also, is it possible to make `<all_urls>`  an optional permission?

**Comment by mymindstorm** [comment]
Firefox doesn't implement `activeTab`, so you have to use `<all_urls>`. [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureVisibleTab)
Requesting permissions from extension popups is broken in Firefox. [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1432083)

> I understand that this extension going rogue would mean that the attacker could get the login information together with the TOTP token. Am I correct?

Yes, that is correct but unlikely for a few reasons:
1. AMO reviewers review source code periodically.
2. Authenticator doesn't (and will never) load any external code, so the only way outside of a vulnerability for it to become compromised would be for a malicious update to be released.
3. [CSP is enforced](https://github.com/Authenticator-Extension/Authenticator/blob/54ab5dc22a7af84341affde70f87f3d371334eb7/manifest-firefox.json#L57).

There are a few workarounds that you could use:
- Verify that a release is not malicious and disable auto-updates.
- Fork and remove the `<all_urls>` permission from the manifest and use your own build of the extension.

**Comment by jonathan-reisdorf** [comment]
Hi :wave: Is the answer still up-to-date? I see that the Firefox bug has been closed in Bugzilla. Perhaps there's now a way to work with less permissions? Thanks!

**Comment by mymindstorm** [comment]
The permissions that would be requested by that are not that important and I can't release a version that uses permission popups until firefox 75 is in ESR.

**Comment by geekley** [comment]
> I can't release a version that uses permission popups until firefox 75 is in ESR.

@mymindstorm Is it possible now?

**Comment by mymindstorm** [comment]
> > I can't release a version that uses permission popups until firefox 75 is in ESR.
> 
> @mymindstorm Is it possible now?

It should be!
