### ISSUE TITLE
Google Authenticator Android App vs Google Authenticator Chrome Extension: can we use only one?

### ISSUE THREAD

**Issue by kampiamodikuesto** [Authenticator-Extension/Authenticator#394]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 
i have google authenticator app on my smartphone and it work properly. Now i installed this extension to use with chrome. I add new element/account:

- in the first field i insert the name of the site where 2FA has been enabled then in the second field i insert the code of android google authenticator app.

If i use extension code i get always wrong code. So if i use google authenticator on my phone then i can't use the extension? have i to disable and reanable f2a from the site?

**Platform:** <This is required> osx 
 - Browser: [Chrome, Firefox] chrome
 - Browser Version: last

**Comment by mymindstorm** [comment]
You don't put in the code, you put in the account secret. Account secrets look like QR codes or text similar to this: `TCQ2O67OP6EFTUZNE74D2OKR7VQYQJE5`

**Comment by kampiamodikuesto** [comment]
i have used QR Code or text code when i configured my android app, now from the site (where i enabled f2a) i have no more code but only an advice that f2a is active. 

so or we use android app or we use extension chrome? now i try to disable/enable f2a, then first i configure the extension and lastly the android app.

**Comment by mymindstorm** [comment]
Disable 2FA on the site, and then setup 2FA again to get a new code. Then setup on both.

**Comment by kampiamodikuesto** [comment]
i'm sorry i used another application https://github.com/gbraad/gauth/ and i write here has been a mistake. With your all things work right!!
