### ISSUE TITLE
建议添加一个扫描图片文件的功能

### ISSUE THREAD

**Issue by Tmalll** [Authenticator-Extension/Authenticator#400]
建议添加一个扫描图片文件的功能，现在的扫描二维码的功能只能扫描网页中的二维码，无法扫描已经保存为图片的二维码

**Comment by Sneezry** [comment]
![Snipaste_2019-11-04_08-54-34](https://user-images.githubusercontent.com/1621293/68095001-c3a4d600-fee0-11e9-9cbc-f4c4a02d01db.png)

在扩展管理页面开启本地文件权限，然后用Chrome打开二维码图片，即可像普通网页一样读取二维码。

Open extension management page, enable local file permission, then open the QR image file with Chrome, and you can scan the code like normal web page.
