### ISSUE TITLE
Authenticator is blank

### ISSUE THREAD

**Issue by Mim137** [Authenticator-Extension/Authenticator#406]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** I just installed this, but I'm not getting any 6-digit numbers. Is this affected by other Chrome add-ons? 

**Platform:** 
 - Browser: Chrome
 - Browser Version: Windows 10

![image](https://user-images.githubusercontent.com/58518832/70152597-836d7a80-167b-11ea-8fd9-35a2eea85c22.png)

**Comment by Sneezry** [comment]
You need add account secret first. This extension is not a Google official product, so it cannot sync with your Android phone, iPhone or iPad.

Here's an introduction for how to use this extension on a 3rd party website, and I hope it may help: https://www.messiah.edu/download/downloads/id/7243/Google_Authenticator_based_Desktop_install.pdf
