### ISSUE TITLE
Auto Lock

### ISSUE THREAD

**Issue by DanieDuToit** [Authenticator-Extension/Authenticator#407]
I would like to see some way of "Auto lock" this app.

**Why do you want this feature in Authenticator?**
The reason is simply to have more security. I sometimes forget to lock "Authenticator" and I will find it still active when I use my browser again. I do not always close my browser after work.

**Comment by Sneezry** [comment]
Dup with https://github.com/Authenticator-Extension/Authenticator/issues/219

**Comment by Sneezry** [comment]
I believe this feature request has been completed in the latest code, and it should be available in the next release.
