### ISSUE TITLE
QR Code inside frame is not recognized

### ISSUE THREAD

**Issue by theedgeu2** [Authenticator-Extension/Authenticator#410]
**Describe the bug:** 
If the page that includes the QR-Code is in a frameset, Authenticator plugin doesn't recognize the image and I've to write the code manually.
Would it be possible detect QR-Code in frameset?

**Platform:** 
 - Browser: Chrome
 - Browser Version: 74.0.3729.169

**Comment by Sneezry** [comment]
I cannot reproduce this issue on my side:

![Snipaste_2019-12-17_22-18-05](https://user-images.githubusercontent.com/1621293/71002943-3c6f9280-211b-11ea-8a63-615f5d3041d5.png)

Can you see correct QR image captured by the extension? You can open QR debugging page by Settings -> About, scroll down to the bottom, then click QR Debugging. Back to the page, scan the QR, then switch to QR Debugging page, see what the extension actually captures.

**Comment by theedgeu2** [comment]
I've enabled QR Debugging and a page with "QR Scan Debugging Page" appears.
I've opened the page with **frameset**, try to scan the QR code but I don't see any messages in the Debugging Page.
I can not scan the QR Code. The image with the "+" sign to scan the QR Code doesn't appears.

If I open the QR Code on another tab then I can scan the code and in the debugging page I see results about widths and a screenshot.

In the example you are using **iframe** and all runs ok, but the page that fails to me use **frameset**.

test.html
<frameset rows="25,*" frameborder="NO" border="0" framespacing="0">
<frame src="header.html">
<frame src="qrcode.html">
</frameset>
The QR Code is in qrcode.html

If I open test.html the plugin doesn't recognize the QR Code.
If I open directly qrcode.html the plugin can recognize the QR Code.

I've attached a zip with the example. If I run directly from my hard disk, when I try to capture the code an error appears. I suppose a web server is needed.
[test.zip](https://github.com/Authenticator-Extension/Authenticator/files/4052893/test.zip)

**Comment by Sneezry** [comment]
I can reproduce this issue. Because it is not allowed to put DIV over FRAMESET element.

However, I do not have plan to fix this issue, because FRAMESET has been deprecated: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frameset

You can open the page in FRAMESET in a new tab or open the QR image in a new tab, and then scan it.
