### ISSUE TITLE
Google Authenticator

### ISSUE THREAD

**Issue by gaswer** [Authenticator-Extension/Authenticator#411]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 

I added google authentication to my Snapchat account and lost authentication
When entering a Snapchat account, it requires authentication
The solution is

**Platform:** <This is required>
 - Browser: [Chrome, Firefox]
 - Browser Version:

**Comment by mymindstorm** [comment]
https://support.snapchat.com/en-US/a/using-recovery-code
