### ISSUE TITLE
None of my 2fa codes are working

### ISSUE THREAD

**Issue by Slinkydu** [Authenticator-Extension/Authenticator#417]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 
I'm having some issues where none of my codes of the authenicator are working.
I haven't touched anything at all. Everything was working just fine up until today where none of the
codes, not even one is working?

Anyone having the same issue?
Please help support.

Thank you.

I'm using Brave Browser btw.

**Platform:** <This is required>
 - Browser: [Chrome, Firefox]
 - Browser Version:

**Comment by Sneezry** [comment]
Please go to `Menu -> Sync Clock with Google` to correct clock offset, and check if the issue can be resolved.

**Comment by Slinkydu** [comment]
oh, wow. I didn't even notice my clock wasn't synced. 
Its ok now. Thank you so much for the help. I was worried there for a bit. hehe
Thank you again

**Comment by Sneezry** [comment]
Glade to know your issue has been resolved. Then I'm closing this issue. Please open a new one if you have other questions.
