### ISSUE TITLE
Direct download not possible, how can I install it?

### ISSUE THREAD

**Issue by StuC73** [Authenticator-Extension/Authenticator#420]
Hello. I have been asked to install this on a customer Win 10 estate, however due to security restrictions they are unable to download the EDGE Authenticator themselves - I will have to download it on a non restricted PC and copy it across. 
Is this possible and if so, what would I need to do? 

(This is my first github post so if I've gone about this the wrong way I'll apologise now. )

Thanks.

**Comment by mymindstorm** [comment]
Are you talking about old edge or new edge? 

If old edge use https://businessstore.microsoft.com/en-us/store to download the appx. Old edge will not be receiving any more updates.

If new edge use gpo to install it from the chrome web store.

**Comment by StuC73** [comment]
Hi. Thanks for the reply. To answer the question, it's currently for Old Edge, but will need to work on New Edge in the not too far future.   I'll see what I can do.

**Comment by mymindstorm** [comment]
The old edge version will not be supported soon or work on new edge and extension data will not be migrated automatically. It would be a lot easier for you to install it on new edge. It looks like the only way to force install extensions on new edge is to use gpo.
