### ISSUE TITLE
"Invalid!" every time using with Magento 2

### ISSUE THREAD

**Issue by OwenG99** [Authenticator-Extension/Authenticator#421]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** We've been using this with Magento 2 for the past 6 months and not had any issues, however today, every time we log in it says "security code not recognised", and when trying to confirm the code we now get "Invalid!" - however if using the google authenticator app, it works without any problem

**Platform:** Magento 2
 - Browser: Chrome
 - Browser Version: 79.0.3945.130

**Comment by mymindstorm** [comment]
Have you tried going to the menu and hitting the "Sync Clock with Google" button?

**Comment by mehdichaouch** [comment]
Hi!

I get the same error.

I by passed the error by using the manual adding,
![image](https://github.com/Authenticator-Extension/Authenticator/assets/861701/f027b796-84a7-48a8-b894-41924e261624)
and pasting the Adobe Commerce Authenticator code from Adobe commerce website, eg:
![image](https://github.com/Authenticator-Extension/Authenticator/assets/861701/5dbfee1b-d039-4b85-8735-34a6a3c77957)

This may help some other users... :wink:
