### ISSUE TITLE
Google API ratelimt shenanigans

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#423]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>
<You can also open an issue by Tweeting with #AuthenticatorFeedback>

We aren't using any of the scopes listed, but I still see verification warnings...

https://support.google.com/cloud/answer/9110914#restricted-scopes

**Comment by mymindstorm** [comment]
So we aren't impacted by that, but for some reason it put a quota of only 100 new users on us (it isn't clear when it resets). That is the same limit unverified apps get, which is odd because the consent screen is verified.

**Comment by Sneezry** [comment]
> User caps limit the number of users who can grant permission to sensitive scopes.

So I think this limit only affect on *sensitive* scopes, which we do not need to access to.

> Your current per day token grant rate limit is 10,000 grants per day.

I think this is the *real* limit how many new users we could have every day.

**Comment by Sneezry** [comment]
@mymindstorm I have just added you into owener group for authenticator DNS zone, please check your outlook.

**Comment by mymindstorm** [comment]
> So I think this limit only affect on sensitive scopes, which we do not need to access to.

There is no list of sensitive scopes. We only use drive.file which is why this is weird. Maybe it's a leftover metric from development? It's really confusing because it asks you to verify to remove the cap. I resubmitted it just in case.

I accepted the email. I never added you to the firefox listing, do you want access to that at your microsoft or gmail address?

**Comment by Sneezry** [comment]
> I never added you to the firefox listing, do you want access to that at your microsoft or gmail address?

No, I'm not familiar with firefox related things, I think it's not nessary to grant my permission.

**Comment by Sneezry** [comment]
> it must comply with the Google API User Data Policy and have its OAuth consent screen configuration verified by Google.

https://support.google.com/cloud/answer/9110914#restricted-scopes

> Ensure that all scopes that your Google API project uses appear in your project's OAuth consent screen scope configuration in the Google API Console. For instructions, see the User consent section in the "Setting up OAuth 2.0" help article.

https://support.google.com/cloud/answer/9110914#restricted-scopes

> There are changes to the OAuth consent screen after your app has been approved.

https://support.google.com/cloud/answer/9110914#circumstances

It seems Google asks developers to declare what permissions (OAuth consent screen) their apps need before to call Drive API. This is called *Restricted Scope App Verification*. And if we change the OAuth consent screen (same as new request here I think), our app must be verified by Google.

So, if I understand correctly, all apps that call Drive API, no matter what permissions they require currently, they need be verified by Google, or there will be a limit of number of new users.

**Comment by mymindstorm** [comment]
> It seems Google asks developers to declare what permissions (OAuth consent screen) their apps need before to call Drive API. This is called Restricted Scope App Verification. And if we change the OAuth consent screen (same as new request here I think), our app must be verified by Google.

There are 3 types of verification:

- Consent screen verification (we already have this)
- Restricted scope verification (does not apply to us)
- Sensitive scope verification (????)

The question is:

- Are we using a sensitive api scope?
- Why do we already have 21/100 of the quota used already?

I think that this doesn't impact us; it isn't very clear.

**Comment by Sneezry** [comment]
<img width="423" alt="Capture" src="https://user-images.githubusercontent.com/1621293/73565448-85e22a00-449c-11ea-8b6f-3503ca0ca502.PNG">
<img width="392" alt="Capture1" src="https://user-images.githubusercontent.com/1621293/73565451-867ac080-449c-11ea-8086-64855e0688d7.PNG">
<img width="579" alt="Capture2" src="https://user-images.githubusercontent.com/1621293/73565454-87135700-449c-11ea-914d-eac729d024a9.PNG">

No idea whether all scopes related to Drive are sensitive. According to Google's words, if a user shares a file in Drive with other people, all apps have Drive scopes may know their names and contact information, which is regarded as sensitive data. To our app, if a user shares his/her backup file to his/her friends or familly, we are able to read his/her friends or familly names and contact information.
