### ISSUE TITLE
Cannot decrypt some accounts after v6.0 update

### ISSUE THREAD

**Issue by erotavlasme** [Authenticator-Extension/Authenticator#428]
Hi,
after the latest update v6.0 when I open the extension and I unlock it with password, not all my accounts are visible. Some of them remain encrypted.
Moreover, even if I setup a lock after some minutes, authenticator locks each time I close it.
I'm using the latest firefox v72.0.2 on GNU/linxu 64 bit.

**Comment by mymindstorm** [comment]
> Some of them remain encrypted.

Did you close the window during the first unlock after it updated or during a password change?

It won't cache your credentials if you have any accounts that show encrypted.

**Comment by erotavlasme** [comment]
I opened the plug in as usual. I did not change any password. Then, I saw some encrypted accounts and I discovered about the update.
What can I do?

**Comment by mymindstorm** [comment]
Can you follow [these steps](https://authenticator.cc/docs/en/debug-info)?

**Comment by erotavlasme** [comment]
I have several extensions:
These should be the errors related to authenticator:
`NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "Invalid autocomplete selectedIndex" {file: "resource://gre/actors/AutoCompleteChild.jsm" line: 196}]'[JavaScript Error: "Invalid autocomplete selectedIndex" {file: "resource://gre/actors/AutoCompleteChild.jsm" line: 196}]' when calling method: [nsIAutoCompletePopup::selectedInde`x]

**Comment by mymindstorm** [comment]
please just paste everything in the window after you open and decrypt authenticator

**Comment by erotavlasme** [comment]
```

Promise rejected after context unloaded: sender.tab is undefined
dnt.js:52
Promise rejected after context unloaded: sender.tab is undefined
fingerprinting.js:316
Promise resolved after context unloaded
Messages.js:67
Promise resolved after context unloaded
settings.js:442
sender.tab is undefined 2 MessageChannel.jsm:1019
Promise resolved after context unloaded
settings.js:442
TypeError: can't access dead object 2
Invalid chrome URI: /
Invalid chrome URI: / 3

```

**Comment by mymindstorm** [comment]
I threw together something to try and decrypt your data. 

1. Open the console (follow debugging steps)
2. Enter `chrome.storage.sync.get(e=>console.log(e))`
3. Right click the blue text and click "Copy Object"
4. Copy that into the input box [here](https://mymindstorm.github.io/authenticator-tool/)
5. Put in password and hit run

It should spit out a backup of whatever it could decrypt. Once you are sure nothing is missing, delete the encrypted accounts and import them back.

**Comment by erotavlasme** [comment]
Is there any way to do the same offline?
Fortunately, I found a recent backup and I removed and reinstalled the extension.

**Comment by mymindstorm** [comment]
> Is there any way to do the same offline?

All of it is done client-side. If you want to host it locally you can clone the repo below, run `npm i`, use webpack to compile, and run a simple http server out of the directory to get it up.

https://github.com/mymindstorm/authenticator-tool
