### ISSUE TITLE
Location of local backup?

### ISSUE THREAD

**Issue by gitkeymaster** [Authenticator-Extension/Authenticator#436]
Hello,

I am trying to figure out **where the local backup is stored** (so I can make a real backup of it, say in a USB stick.)

It is not clear where this file is located. So can anyone help me?

My suggestion is that the file location should be displayed more prominently to the user.

Otherwise great extension!

**Comment by Sneezry** [comment]
If you have set default download directory in browser, your backup is there. If you haven't set default download directory, the browser will popup file explorer to let you choose the location.

**Comment by gitkeymaster** [comment]
Oh I missed that. It was in import/export menu. Many thanks!
