### ISSUE TITLE
Feature Request: Use Firefox Sync

### ISSUE THREAD

**Issue by fdw** [Authenticator-Extension/Authenticator#440]
**Describe the feature you want:**
Instead of using a third-party service, I would like to sync the 2FA data using Firefox Sync

**Why do you want this feature in Authenticator?**
Since syncing is already supported, I would like to not rely on a third-party service but use the Firefox Sync I have already set up for my Firefox.

**Comment by Sneezry** [comment]
Firefox Sync should be already supported as we support `storage.sync`. CC @mymindstorm for confirmation.

**Comment by fdw** [comment]
Oh, cool :)

However, I haven't found where to turn it on with v6.0.1. Do you have any pointers there?

**Comment by Sneezry** [comment]
Firstly, confirm you have selected `sync` for storage location.

Secondly, sign in to Firefox with your Firefox account.

All done.

![Snipaste_2020-03-06_21-11-38](https://user-images.githubusercontent.com/1621293/76086661-7dc36000-5fef-11ea-9667-18fa0e2ff1f7.png)

**Comment by fdw** [comment]
I have done both, but I have yet to notice that it syncs :/
Anyway, thank you :)

**Comment by Sneezry** [comment]
If you sign in on other device, the data should be synced between your two devices. Have you signed in your Firefox account on all your devices?

Also, here's the docs about how to sync on your computer: https://support.mozilla.org/en-US/kb/how-do-i-set-sync-my-computer

**Comment by mymindstorm** [comment]
@fdw browser sync tends to be slow and finicky. You can try and force it to sync by going to the menu -> your username -> force sync. 

You need to have extension data on in the sync settings.

**Comment by fdw** [comment]
Thank you all!

It seems that my problem is with Firefox Sync, so I'll close this ticket and try to fix my problem.
