### ISSUE TITLE
Completely blank addon frame

### ISSUE THREAD

**Issue by istolpov** [Authenticator-Extension/Authenticator#442]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** 
Honestly, I don't even know what to describe. It just stopped working at all.
It does draw the frame but _everything_ inside it is completely blank.
I can't go to settings or do anything -- there are no buttons.

Here are logs from console (uglified code does not help point out the issue, by the way).
```

Unchecked lastError value: Error: An unexpected error occurred popup.js:1
    get moz-extension://0314e57b-8054-ee4b-aa4a-55ef2fe18d7b/dist/popup.js:1
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-2.2.8
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 450 OpenGL Engine
FBO Texture Target: TEXTURE_2D
sender.page is undefined MessageChannel.jsm:1019
    promise resource://gre/modules/MessageChannel.jsm:1019
page is undefined MessageChannel.jsm:1019
    promise resource://gre/modules/MessageChannel.jsm:1019
Promise resolved after context unloaded
polyfill.js:237
    shouldWrapAPIs moz-extension://04733b31-d960-b14c-acbf-aa15957ffaf0/polyfill.js:237


```

Here is screenshot:
![Screenshot 2020-03-10 at 00 40 28](https://user-images.githubusercontent.com/8819524/76260033-f896b000-6267-11ea-9fe7-57530e76dfee.png)

Browser restart does not help.

**Platform:**
 - Browser: Firefox
 - Browser Version: 73.0.1 (64-bit)
 - Addon Version: 6.0.1

**Comment by istolpov** [comment]
Oh, and by the way, If you have any workaround to recover from this, possibly using other 2fa apps and maybe some hacks, I would be very much obliged. Currently this keeps me locked out of a _very_ important and a bit urgent things.

TIA.

**Comment by mymindstorm** [comment]
To get access to the data, you can paste `chrome.storage.sync.get(e=>console.log(e))` into the console. If you are using encrypted data I have a decryption tool [here](https://mymindstorm.github.io/authenticator-tool/). The code for it is [here](https://github.com/mymindstorm/authenticator-tool), if you want to run it locally.

You can directly use the `secret` property of a decrypted data in any totp client.

**Comment by mymindstorm** [comment]
I think this might be an issue with Firefox itself. Can you try running the extension with a new profile? You can use about:profiles to do this. If it works in a new profile you should be able to just import the encrypted data.

**Comment by istolpov** [comment]
```
$ chrome.storage.sync.get(e=>console.log(e))
-> undefined
undefined debugger eval code:1:36
Unchecked lastError value: Error: An unexpected error occurred debugger eval code:1
    <anonymous> debugger eval code:1
```

**Comment by mymindstorm** [comment]
Do all the tests on this page pass?
https://firefox-storage-test.glitch.me/

**Comment by istolpov** [comment]
Ok, I created new profile, installed addon there and entered secret that I just remembered I made a photo of just in case -- it worked.

However, because add-on has been installed again I assume we cannot exclude the possible files corruption -- it maybe that add-on installations are namespaced.


All tests pass from the old profile.

**Comment by mymindstorm** [comment]
@wyde19 you should report this bug to Mozilla: https://bugzilla.mozilla.org/enter_bug.cgi?format=guided#h=dupes|WebExtensions|Storage
