### ISSUE TITLE
Question: Are secrets encrypted if using 'sync'

### ISSUE THREAD

**Issue by MrSkinny** [Authenticator-Extension/Authenticator#444]
Happy to contribute a quick PR into documentation on this, but wanted to understand:

1. If you don't add a password under "Security" then all of the secrets are stored in plaintext?

1a. If you backup to Drive/Dropbox, those same secrets are uploaded in plaintext?

2. If you choose Storage Location as 'sync', and you use encryption for Google Sync, is the data stored ONLY on Google's servers and thereby encrypted?

Just trying to understand if your secrets can be stored encrypted without needing a separately managed password under "Security" option, when using Google Account Sync.

**Comment by mymindstorm** [comment]
1. Yes, there is bold text in the Firefox addon listing to discourage this.

1a. If you don't have encryption setup we show scary red warning text before you login to a backup account.

2. You can set a sync passphrase in chrome to encrypt your sync data, but I don't know how secure it is.

> Just trying to understand if your secrets can be stored encrypted without needing a separately managed password under "Security" option, when using Google Account Sync.

I strongly encourage setting a password under "Security". Even if you enable a sync passphrase, the data is still stored on disk unprotected.
