### ISSUE TITLE
Dear sir please i need somme help because to day 29-03-2020 i can't accesse to all my website because all my website tel me error code ( the code given by the app is error) please help

### ISSUE THREAD

**Issue by samirmas** [Authenticator-Extension/Authenticator#449]
Dear sir please i need somme help because to day 29-03-2020 i can't accesse to all my website because all my website tel me error code ( the code given by the app is error) please help
my email   
![Capture 1](https://user-images.githubusercontent.com/58117719/77861284-3e65e900-7214-11ea-9030-37f37523f31d.JPG)
![capture 2](https://user-images.githubusercontent.com/58117719/77861288-4160d980-7214-11ea-9d5a-6ca262ba41e0.png)
![capture 2](https://user-images.githubusercontent.com/58117719/77861289-41f97000-7214-11ea-8b0d-5021c70ce4f5.png)
![Uploading Capture 1.JPG…]()

**Comment by mymindstorm** [comment]
Try using Menu -> Sync clock with Google.
