### ISSUE TITLE
QR-Reader

### ISSUE THREAD

**Issue by TriMoon** [Authenticator-Extension/Authenticator#462]
<You can also suggest feedback by Tweeting with #AuthenticatorFeedback>

**Describe the feature you want:**
Ability to scan QR-Codes for other usages besides adding 2FA info.

**Why do you want this feature in Authenticator?**
You already seem to have the QR-Reader functionality, why not extend it/allow it to be used to scan QR-codes without the info being used for 2FA purposes?
This would make this extension even more useful as it is now...

I propose the "Scan QR-Code" functionality for other usages to be available as a right-click menu item on an image...

**Comment by mymindstorm** [comment]
This is a bit out of scope for Authenticator, this idea would work better as it's own extension.

**Comment by Sneezry** [comment]
Authenticator does support scan other QR codes. Just click the Scan QR code icon, and drag to cover the QR code like what you do when you add account. The result will popup on the current page:

![Snipaste_2020-05-15_08-37-19](https://user-images.githubusercontent.com/1621293/81999379-77a0ce00-9687-11ea-9609-932e9f49687e.png)
