### ISSUE TITLE
Can't type my password if it contains /

### ISSUE THREAD

**Issue by kalbasit** [Authenticator-Extension/Authenticator#464]
**Describe the bug:**

Recently I noticed that I can no longer type in my password. As soon as type in `/` the focus is taking away from the password prompt into the search bar.

**Platform:**
 - Browser: Chrome on Linux and Chrome on Mac.
 - Browser Version: `81.0.4044.92` on Linux and `81.0.4044.113` on Mac.

**Comment by Sneezry** [comment]
I cannot reproduce this bug on a Windows machine. What is your extension version?

**Comment by kalbasit** [comment]
It's 6.0.1.

**Comment by mymindstorm** [comment]
I can reproduce with 6.1.0, it only happens when I press `/` twice.
