### ISSUE TITLE
How many addresses?

### ISSUE THREAD

**Issue by Gennadii111** [Authenticator-Extension/Authenticator#471]
Hello everyone! How many addresses can I add to the authenticator?
What happens if the lemite is over, and then you add another address, rewriting and deleting which existing address?
Thanks in advance for your reply!

**Comment by mymindstorm** [comment]
You should only be limited by the amount of storage the browser lets Authenticator use. If your storage location is set to `sync`, it caps when you hit either ~500 items or 100 KB. If you are using `local` you can store up to 5 MB worth of accounts. See: https://developer.chrome.com/extensions/storage#property-sync

If you hit the limit, it will probably just not work whenever you try to add or edit entries. If you are at the point where you are asking these questions you might want to look into just building your own script for this.

**Comment by Gennadii111** [comment]
> Вы должны быть ограничены только объемом памяти, который браузер позволяет использовать Authenticator. Если ваше хранилище установлено на `sync`, оно закрывается, когда вы нажимаете ~ 500 элементов или 100 КБ. Если вы используете, `local`вы можете хранить до 5 МБ учетных записей. Смотрите: https://developer.chrome.com/extensions/storage#property-sync
> 
> Если вы достигнете предела, он, вероятно, просто не будет работать, когда вы пытаетесь добавить или изменить записи. Если вы находитесь в точке, где вы задаете эти вопросы, возможно, вы захотите просто создать собственный сценарий для этого.



> You should only be limited by the amount of storage the browser lets Authenticator use. If your storage location is set to `sync`, it caps when you hit either ~500 items or 100 KB. If you are using `local` you can store up to 5 MB worth of accounts. See: https://developer.chrome.com/extensions/storage#property-sync
> 
> If you hit the limit, it will probably just not work whenever you try to add or edit entries. If you are at the point where you are asking these questions you might want to look into just building your own script for this.

Thanks for the answer!
