### ISSUE TITLE
The Authenticator hang

### ISSUE THREAD

**Issue by khamdanfath** [Authenticator-Extension/Authenticator#473]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 

blang white, 2 days what should i do? i dont have backup code

**Platform:** <This is required>
 - Browser: [Chrome, Firefox]
 - Browser Version:

**Comment by mymindstorm** [comment]
Please open Authenticator and follow [these steps](https://authenticator.cc/docs/en/debug-info).

**Comment by khamdanfath** [comment]
syntax error, unexpected token. only this text i found, and its cant to copy

**Comment by khamdanfath** [comment]
![Screenshot (162)](https://user-images.githubusercontent.com/64734004/80955428-825a9800-8e29-11ea-8c4f-68935a1dd111.png)

**Comment by khamdanfath** [comment]
@mymindstorm how to fix it? can i edit it or somethings? please help me :'(

**Comment by mymindstorm** [comment]
You can get your data by going to the console and typing in
```js
chrome.storage.sync.get(e=>console.log(JSON.stringify(e)));
```
If you copy the output of that command and import it using text backup, you should get your data back.

We do not support UC Browser as it has not been updated in two years. Please switch to Chrome or Firefox.
