### ISSUE TITLE
Cannot find where option stores locally

### ISSUE THREAD

**Issue by Tharn** [Authenticator-Extension/Authenticator#475]
**Describe the bug:** Using Storage Location: Local to save config will store the extension settings _somewhere._ Where is it? I haven't been able to find it.

Sorry about making a bug report for this, but this should either be declared when using the option, or it should be a file download dialog like 'Export'.

**Platform:**
 - Browser: Firefox
 - Browser Version: 76.0.1 x64

**Comment by Sneezry** [comment]
It's stored in IndexedDB in `<profile>/storage/default` (see [this doc](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Where_is_the_data_stored)) - however, you shouldn't touch it or you may destroy your browser.

Currently, we don't support backup settings, but only entries. Are you requesting a new feature?

**Comment by Tharn** [comment]
Okay, thanks. After looking at the dialog more closely, it simply saves settings locally and is not meant to save-to-file for the user to do anything with. Cheers.
