### ISSUE TITLE
store data on Dropbox/GDrive encrypted if password is set

### ISSUE THREAD

**Issue by aleqx** [Authenticator-Extension/Authenticator#476]
As subj says. If a password is set then why not store the data on dropbox/gdrive in encrypted form instead of unencrypted? Currently if I try to activate sync to dropbox it warns me that the data would be stored unencrypted.

Also, is dropbox/gdrive used to actually sync between devices or just to push a backup on cloud? If yes, then in order to sync the extension would need to be unlocked. That would be fine, e.g. sync to/from when extension is unlocked, and then every M minutes.

**Comment by Sneezry** [comment]
>  If a password is set then why not store the data on dropbox/gdrive in encrypted form instead of unencrypted?

Dropbox/GDrive backups do be encrypted if you set a master password in security setting. What browser and which version of the extension do you use?

> is dropbox/gdrive used to actually sync between devices or just to push a backup on cloud?

No. dropbox/gdrive is only used to push a backup on cloud.

**Comment by mymindstorm** [comment]
@aleqx set your password again and it should go away
