### ISSUE TITLE
Some code become Invalid after set a password

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#485]
This bug can be reproduced in the latest code in dev branch

<del>1. Export an encrypted backup
2. Open a new Authenticator instance (do a rest before test, make sure no password is set in Authenticator)
3. Import the backup with correct password
4. Set a different password in security menu
5. Some code become Invalid</del>

This bug won't make all code Invalid, but all code are broken with incorrect results.

## Update:

This issue has no relationship with import backups.

It seems when we set a password, we failed to set encrypted flag for existing entries.

1. Open a new Authenticator instance (do a rest before test, make sure no password is set in Authenticator)
2. Add a new account
3. Set a password in security menu
4. Execute `chrome.storage.sync.get(console.log)` to see result

The existing account secret has been encrypted, but the `encrypted` flag is still set to `false`.

Still digging

## Update2:

The latest code has fixed this issue. This issue doesn't affect any published versions of Authenticator.

The root cause of this bug is because we retired `encrypted` flag and use a new field `encSecret` to handle detecting encrypted secret. There is a logic mistake to migrate this change. We have also created a [new issue](https://github.com/Authenticator-Extension/Authenticator/issues/486) to remove `encrypted` flag to make the logic clear.

**Comment by mymindstorm** [comment]
How are you clearing? If you are using the button it could be clearing the time offset from localstorage.

**Comment by Sneezry** [comment]
It seems an issue about set master password

**Comment by mymindstorm** [comment]
I think this might be because of bdfd6540d8958951787d03b9698eb0d67e8c1aee

**Comment by mymindstorm** [comment]
I really need to get some integration tests going...

**Comment by Sneezry** [comment]
Emmm, we retired `encrypted` flag and have a new field to handle encrypted secret. This makes sense. I think we can do a migration when import backups, and remove all logic about `encrypted` flag.

**Comment by Sneezry** [comment]
I have verified the latest code has fixed this issue. This issue doesn't affect any published versions of Authenticator.
