### ISSUE TITLE
Страка1 позиция1

### ISSUE THREAD

**Issue by Elbrus1** [Authenticator-Extension/Authenticator#487]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 

**Platform:** <This is required>
 - Browser: [Chrome, Firefox]
 - Browser Version:

**Comment by Elbrus1** [comment]
Браузер Гоогле

**Comment by Sneezry** [comment]
Could you provide more information to describe your question? And could you write in English as we cannot read Russian. Google translate doesn't help. Thanks.

**Comment by Elbrus1** [comment]
I like WinAuth Google very much but recently I can't use it because the Line 1 Position 1 POPs up and tells me that this incomprehensible error that I can't do anything about. Please help me deal with the problem and tell me if You do not find it difficult what I need to do. I want to thank you in advance for your help because I do not doubt Your generosity and I am sorry to bother you.

**Comment by Kalibruss** [comment]
Отправлено с моего телефона Huawei-------- Исходное сообщение --------От: Zhe Li <notifications@github.com>Дата: пт, 22 мая 2020 г., 11:30Кому: Authenticator-Extension/Authenticator <Authenticator@noreply.github.com>Копия: Subscribed <subscribed@noreply.github.com>Тема: Re: [Authenticator-Extension/Authenticator] Страка1 позиция1 (#487)
Could you provide more information to describe your question? And could you write in English as we cannot read Russian. Google translate doesn't help. Thanks.

**Comment by Sneezry** [comment]
@Elbrus1 Can you post the error screenshot here?

**Comment by Elbrus1** [comment]
Hello to the support group!
I am sending you a screenshot and hope You can tell me how to cope with
this problem. Thank you very much



пт, 22 мая 2020 г. в 18:53, Zhe Li <notifications@github.com>:

**Comment by Sneezry** [comment]
I'm closing this thread as there is no further update.
