### ISSUE TITLE
Sync icon shows even oauth flow breaks with Google Drive

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#491]
This issue can be reproduced in latest code in dev branch.

It may because I didn't set Google API secret for testing, but obviously, it is still a bug.

Reproduce steps:

1. Pull the latest code from dev branch
2. Run `npm i && npm run chrome` to compile the code
3. Load the chrome folder in Chrome browser
4. Click **Google Drive** button in Storage & Backup menu
5. Click **Sign in** button (nothing will happend because there is no API secret)
6. Go back to home page of popup, sync icon shows

The drive token is stored in value of `undefined` as string, and Authenticator considers that is a valid token, so shows the sync icon.

Haven't tested in prod version which contains a valid API secret.

**Comment by mymindstorm** [comment]
not seeing this in my firefox dev or prod version. Drive auth is currently messed up in prod Firefox due to 75 changes. I would try cancelling the auth flow and seeing if that causes the issue too.

**Comment by mymindstorm** [comment]
Chrome uses a different auth flow for Google, that's probably why this is happening. It doesn't use an API secret, it uses extension id.

**Comment by Sneezry** [comment]
The easiest way is to check if the token eques to `"undefined"`. A better way is we shouldn't set the token in LocalStorage if it is `"undefined"`.

**Comment by mymindstorm** [comment]
I found the problem. Will submit fix soon.
