### ISSUE TITLE
Extend the qr reader to all qr (Not only authenticators)

### ISSUE THREAD

**Issue by Ares9323** [Authenticator-Extension/Authenticator#492]
I've been using this extension for a while and I find it extremely useful. 
One thing I like a lot is the possibility to scan QR codes, I was wondering if it was possible to extend this feature to generic qr codes in webpages and maybe copying the url to te clipboard instead of returning an error..
There is no other extension that does this in a screen portion, I've tried many and some use the webcam, others ask you to upload an image..

Thanks for the attention, have a nice day!

**Comment by Sneezry** [comment]
Authenticator does scan generic QR, and will popup the result.

What the error you got when you scan the QR?

![](https://user-images.githubusercontent.com/1621293/81999379-77a0ce00-9687-11ea-9609-932e9f49687e.png)

**Comment by Ares9323** [comment]
Oh I'm really sorry I opened this issue without trying different qr types, I tried several generated with a php library and logo in the middle but probably the problem was in the library..

However if it doesn't cost much effort I'd really love a button with "Copy" in addition to "Ok", It would be very useful!

Sorry for wasting your time asking for a think it already present!

**Comment by Sneezry** [comment]
The QR reader cannot read some code. We have improved it and will release in the next version. I have created a feature request for fast copy.
