### ISSUE TITLE
Refresh codes for next tick

### ISSUE THREAD

**Issue by est** [Authenticator-Extension/Authenticator#499]
When copy paste the code in Authenticator, if the tick is just about to expire, by time I switch app window, paste, the code has already expired and thus invalid. Re-copy the code is annoying, and next time it happens, I have to wait for the code to refresh.

I hope there's a "manual refresh to next tick" button to trigger the code change. This guarantee a single copy will succeed without need to switch Chrome and target app window back and forth.

**Comment by Sneezry** [comment]
TOTP is based on time and shouldn't be triggered manually. I understand your scenario, but such a feature does more harm than good. It will increase complexity of code logic and confuse users in the UI. If the code is expiring when you copy it, the best solution is to wait for a few seconds for the new tick.

However, I'm open to discuss for this feature request. If you have any strong reason that waiting for some seconds is hard to accept for use experience, please feel free to let me know.

**Comment by est** [comment]
> but such a feature does more harm than good

The hole point of 2FA is to have TOTP on a secondary device. The Chrome extension is largely turning 2FA into 1FA, it's for better convenience rather than less harm. 🙏

> the best solution is to wait for a few seconds for the new tick.

That's what I am doing right now. I feel my work flow is broken by idle pending for the code to update and it's driving my insane. 😂

Maybe we can add this as a hidden feature, some shortcut key to fast-forward the time a little bit?

**Comment by Sneezry** [comment]
> it's for better convenience rather than less harm

Harm I mentioned here means "It will increase complexity of code logic and confuse users in the UI"

Also, we do take serious with security. Any convenience at the expense of security is unacceptable. However, the harm here has no relationship with security.

> Maybe we can add this as a hidden feature, some shortcut key to fast-forward the time a little bit?

I don't think it's worth to do on project dev side. However, PR is always welcomed.

**Comment by Tharn** [comment]
Timed codes are the whole point of 2FA. It's not just convenience, it also removes the requirement of having to own a smartphone. And it still adds security. I'm against this request, the extension works fine as it is.

And a more reasonable counter to the request is this: When you want to grab the 'next' code, the counter is likely about to expire. Clicking on 'next code' is an extra user action. Waiting a second or two instead seems trivial and is the _obvious choice_.

**Comment by Sneezry** [comment]
I'm closing this thread as this is a out-of-scope feature request.
