### ISSUE TITLE
Setup instructions?

### ISSUE THREAD

**Issue by tueksta** [Authenticator-Extension/Authenticator#500]
<You can also suggest feedback by Tweeting with #AuthenticatorFeedback>

**Describe the feature you want:**
There's absolutely no explanation how to set this up. Maybe a wiki page or in the about page?

**Why do you want this feature in Authenticator?**
I don't know how to use it.

**Comment by mymindstorm** [comment]
We do need better onboarding. When you setup 2FA for a service, all you have to do is scan the QR code a website gives you with the extension. After that, the code should appear in the extension.

You can test it using this website: http://security-totp.appspot.com/

**Comment by Sneezry** [comment]
I'm closing this thread as there is no further update.
