### ISSUE TITLE
support external sync adaptor/external sync code/sync over given directory

### ISSUE THREAD

**Issue by warichnict** [Authenticator-Extension/Authenticator#503]
hi,

saying to dont allow sync with my own nextcloud server for security reason seams quite dumb in my ears... But if you say so could you at least allow an external sync adaptor that i can configure to use, like save to a special directory (directory of nextcloud/syncthing/whatever data directory and handle conflicts (eg. one file per entry or auto merge subroutine)) or an direct external database (like odbc or so) interface to save the data as i want it.

**Comment by mymindstorm** [comment]
This is a duplicate of #222. 

> saying to dont allow sync with my own nextcloud server for security reason seams quite dumb in my ears

Please remain respectful in the issue tracker. The workarounds mentioned in that thread are too complicated from an end user's perspective and are pretty hacky. We cannot (and should not) dynamically define CSP. Removing CSP would be a legitimate security issue, and we will not hurt security for ancillary functionality.
