### ISSUE TITLE
Can't immediately tab into password field after opening extension

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#505]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>
<You can also open an issue by Tweeting with #AuthenticatorFeedback>

- Open extension
- press tab
- password field is not focused

This worked prior to 5.2.0

**Comment by isumairu** [comment]
I don't know which one is the "password field".

This?
![Picture1](https://user-images.githubusercontent.com/16854686/87613685-39cc2e80-c738-11ea-994c-fe547550d509.jpg)
