### ISSUE TITLE
Run on webserver

### ISSUE THREAD

**Issue by kadmin-stack** [Authenticator-Extension/Authenticator#514]
<You can also suggest feedback by Tweeting with #AuthenticatorFeedback>

**Describe the feature you want:**
Wondering if I can run this on a web server where all the codes are generated on a page. Thereby, there's a single location to view only the TOTP codes (QR codes would not be seen).

**Why do you want this feature in Authenticator?**
I would like to share the codes for some sites and having a shared internal location would make it scalable. Easier then individuals installing the app and re-inputing each QR code.

I realize there are some security issues with this; therefore, it would run behind a firewall and not be available to others.

Is this possible?
Are you ok with this type of application of your software?
And, how complicated would be the implementation?

**Comment by mymindstorm** [comment]
No, we rely on a lot of extension APIs that are only available on clients and letting people do that would be a security no no as you said. You should look into password managers catering to buisnesses like Bitwarden witch allow you to share this type of data securely with a team.

**Comment by kadmin-stack** [comment]
Thank you! Bitwarden might be just the product I've been looking for. And, I really appreciate your product. It's awesome, and your team is doing a great job. Thanks.

**Comment by MaivKhanh20181** [comment]
[]()
