### ISSUE TITLE
CCleaner v5.69 > Firefox > Internet Cache cleaning deletes 2 files (at least one of which is apparently) needed by Authenticator

### ISSUE THREAD

**Issue by Tom-Usher** [Authenticator-Extension/Authenticator#519]
CCleaner v5.69 > Firefox > Internet Cache cleaning deletes 2 files (at least one of which is apparently) needed by Authenticator for its data. Glad I had my exported backup.

I'm on Windows 7 Pro. Firefox is 79.0 (64-bit). Authenticator is 6.2.1.

Firefox > Internet Cache needs to be deselected in CCleaner, or the files need to be added to CCleaner's "Exclude list."
...\AppData\Roaming\Mozilla\Firefox\Profiles\...\storage-sync-v2.sqlite-shm
...\AppData\Roaming\Mozilla\Firefox\Profiles\...\storage-sync-v2.sqlite-wal

I haven't submitted anything to CCleaner about it. You might want to after you confirm this issue.

**Comment by Sneezry** [comment]
This could be a related issue: https://community.ccleaner.com/topic/45531-firefox-sync-disconnected-after-running-ccleaner/

**Comment by mymindstorm** [comment]
This is probably related: https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/

Windows 7 is EOL, that could also be causing problems. You should submit a report against extension data storage at https://bugzilla.mozilla.org.

**Comment by mymindstorm** [comment]
The CCleaner bug is being tracked at bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1657385
