### ISSUE TITLE
Allow Images for Importing Auths

### ISSUE THREAD

**Issue by machineghost** [Authenticator-Extension/Authenticator#520]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** It's impossible to import QR codes from a phone into this app.

Let's say I have authentication setup with Google on my phone.  The only way I can export it is with a QR code.  However, this app has no way to get that code.  Even if I used my computer's webcam to try and scan my phone ... it doesn't work.

You could try and improve that functionality, but it seems to me that approach is just inherently problematic.  But anyone can take a screenshot of their computer/phone, so why not just let people upload an image of their QR code instead?

**Platform:** <This is required>
 - Browser: Chrome
 - Browser Version: 84.0.4147.105 (Official Build) (64-bit)

**Comment by mymindstorm** [comment]
>  But anyone can take a screenshot of their computer/phone, so why not just let people upload an image of their QR code instead?

You can open an image using your browser (drag and drop the file into the window) and then use the QR scanner. If you are using Chrome you will need to go to chrome://extensions and enable "Allow access to file URLs".

**Comment by machineghost** [comment]
I'm just curious ... why the strong attachment to this weird "highlight part of the page" thing (with all the baggage of trying to get that QR code on the page with webcams, Chrome alterations, etc.), and why the strong opposition to just "here's my screenshot file, use it"?

**Comment by mymindstorm** [comment]
There isn't really any opposition, we just haven't gotten around to a file picker option yet. The thought process here is using the computer with the extension to setup 2FA and then using the extension's export to propogate the account to a phone or other computer.

I'm a bit confused on what you are getting restricted by here.

**Comment by machineghost** [comment]
>I'm a bit confused on what you are getting restricted by here.

I think we're talking past each other: I'm not "getting restricted", I'm lobbying for (what I see as) a superior UI.  And if you have nothing against a better UI ... except the time to make it ... then I think that's the best possible (real/honest) answer you can give :)

**Comment by mymindstorm** [comment]
What I'm trying to say is: what steps are you taking that support this UI? I don't understand how you got to a screenshot of a QR code from a phone. Most apps (E.g. Google Authenticator) do not even allow you to export accounts, and if they do it tends to be in a text format.

**Comment by machineghost** [comment]
> I don't understand how you got to a screenshot of a QR code from a phone. 

Most phones have a built-in way to take screenshots (some key combination that varies by phone).  I used mine to take this picture of the "Transfer" menu of Authenticator: https://i.imgur.com/Er9JEbe.png

> Most apps (E.g. Google Authenticator) do not even allow you to export accounts, and if they do it tends to be in a text format.

As you can see from that screenshot, Google Authenticator does in fact allow exporting accounts, and actually the *only* way they allow it is via QR code.  I would _much_ prefer if they gave me a number or string I could just use, but they've settled on QR codes ... thus my lobbying for an easier path to import said QR codes.

**Comment by mymindstorm** [comment]
> Most phones have a built-in way to take screenshots (some key combination that varies by phone). I used mine to take this picture of the "Transfer" menu of Authenticator: i.imgur.com/Er9JEbe.png

The app blocks me from screenshotting the export QR code.

**Comment by Sneezry** [comment]
I'm not able to find such a feature in Google Authenticator iOS app. Is this for Android phones only?

**Comment by machineghost** [comment]
>I'm not able to find such a feature in Google Authenticator iOS app. Is this for Android phones only?

I only use Android, so I can't speak to iPhones.

>The app blocks me from screenshotting the export QR code.

Oh nuts, I should have tried that myself.  Thanks Google: way to make it completely impossible to export a key from my phone to my computer :(

(And thank you mymindstorm for identifying the pivotal flaw in my proposal!  Unlike my "thank you" to Google, this one is sincere.)

**Comment by mymindstorm** [comment]
@machineghost we will implement a file picker anyway, the current system for reading QR codes from files is not intuitive at all.

**Comment by machineghost** [comment]
Awesome!  I'm sure it will be an improvement for others (and hopefully someday Google will give me a way to use it!)
