### ISSUE TITLE
Please add a password protection to access.

### ISSUE THREAD

**Issue by ciciolina** [Authenticator-Extension/Authenticator#522]
<You can also suggest feedback by Tweeting with #AuthenticatorFeedback>

**Describe the feature you want:**
Please add a password protection because the extension is very vulnerable to a maid attack, i found very disturbing that one person only click and have access to the user name the webpage and the 2FA code... the password its easy to hack if you make a maid attack...

**Why do you want this feature in Authenticator?**
For privacy concern... i think its necesary, or at least hide the user name... you can add this feature like bitwarden extension, you click the icon, put the pass and have access to the vault of Autenticator.
Thanks for your time and i hope you can add this feature in the near future.

**Comment by mymindstorm** [comment]
You can add a password by going to the security menu.

**Comment by ciciolina** [comment]
Thank you, i see the default option (2min lock) didn't works for that reason i think this app doesn't have the feature, i change it to 1 min and now works... thanks and sorry for the misunderstanding.
