### ISSUE TITLE
Allow user to specify how entries are matched with websites

### ISSUE THREAD

**Issue by jmlag** [Authenticator-Extension/Authenticator#528]
<You can also suggest feedback by Tweeting with #AuthenticatorFeedback>

**Describe the feature you want:** 
Allow the user to define the criteria the extension uses when determining if an entry matches the current URL in the browser. Ex. only match on subdomain.example.com instead of example.com, use regex, etc.

**Why do you want this feature in Authenticator?**
Pretty much every password manager already has this type of functionality.

Just wondering if this would be a welcome feature. I'd be willing to work on this but if there's no interest in then it wouldn't be worth it.

**Comment by mymindstorm** [comment]
We do have some issues related to this, I think it is worth overhauling the filter logic. There is already some basic version of filter overriding if you append `::xxx.site.com` to the issuer field.

**Comment by Sneezry** [comment]
I'm closing this thread as there is no further update.
