### ISSUE TITLE
all my data it's shown as encrypted even I type correctly password...

### ISSUE THREAD

**Issue by Meserias** [Authenticator-Extension/Authenticator#529]
![fail](https://user-images.githubusercontent.com/12730634/92224422-77cd0f80-eeaa-11ea-9a3e-c2c6b0f53f5c.jpg)
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 
today I have discovered that I could not login to my favorites sites because Authenticator-Extension fail to provide me necessary code. Please re-test against the latest release of FireFox

- Platform: Window 10 x64 (v1809)
- Browser: Firefox
- Browser Version: 80.0.1 x64

**Comment by mymindstorm** [comment]
Please follow [these steps](https://authenticator.cc/docs/en/debug-info) and run https://firefox-storage-test.glitch.me/

**Comment by Meserias** [comment]
temporary workaround situation was after entering password then go to Settings > Storage & Backup > Storage Location and here....select option: local

Then my items appear but combined with the others, then I choose to delete encrypted entries.
Suggestion: I think "sync" option should not be valid/enabled or default until user make FIRST synchronization successfully.

**Comment by mymindstorm** [comment]
Thank you for the info, but I would appreciate logs from when it was broken. I can't do much about this without any of that information. This is related to a Firefox update that changed how storage works and broke it for some users.
