### ISSUE TITLE
Url Link Match

### ISSUE THREAD

**Issue by h4rdx0** [Authenticator-Extension/Authenticator#532]
Hey Team!

You are doing a great job with this app! Congrats!

Could you create a url matching option? So we can add a URL to match and see only the codes for that site.

Thanks!

**Comment by mymindstorm** [comment]
This already exists based on the issuer/account name. If you add `::website.com` to the end of an account name (E.g. `Google` becomes `Google::google.com`) it will manually override it and automatically filter depending on the tab you have open.

**Comment by h4rdx0** [comment]
Oh! Really?

I didn't know that. Thanks a lot for your job!
