### ISSUE TITLE
Support google QR export/import

### ISSUE THREAD

**Issue by edegraaff** [Authenticator-Extension/Authenticator#536]
Hi, it seems the import function for QR codes is failing. 
Recently i reenabled 2facton on one site, and there i puzzeled why the qr code is not recognised and or the qr code import is failing. It seems somewhere in the import of the qr code of a phone something is causing troubles. 

Coult you verify the import of all codes from android to the app by qr code is still working as expected since i am getting an error.
i also mentioned it in twitter

#AuthenticatorFeedback could you help me with the import function? It seems importing the qr codes from the google authenticator are no longer working. Need to import and it fails. Worked in the past without any issues. Error otpauth-mirgation offline?

**Platform:** <This is required>

Google Chrome Versie 85.0.4183.121 (Officiële build) (64-bits)

**Comment by mymindstorm** [comment]
Hi, could you please clarify what you are trying to import? Is the QR code from a website or the Google Authenticator app?

**Comment by edegraaff** [comment]
a screenshot from the google authenticator app. i tried to show the png withing chrome and then detect. i tried to embed in eebpage  and send it to gmail and read the image ... when the detection of the qr worked i received an error as described... in the past i know for sure it worked without problems. and i want to add a new account...so olt ones work like a charm.. new ones fail...

⁣---
Follow us @ https:/www.fishfreak.orgFly-fish & -tie, Nordics, camp & outdoor​

Op 6 okt. 2020 01:30, om 01:30, mymindstorm <notifications@github.com> schreef:

**Comment by mymindstorm** [comment]
We don't support google authenticator backup QR codes yet, but if you scan directly from a website that will work fine.

**Comment by edegraaff** [comment]
hum, it could be i added them in the past by website. That explains a lot. It would be great to be able to have a way to have your google app and transfer all tokes to your tool. I like the use a lot. Any suggestions to sync them manually?

⁣---
Follow us @ https:/www.fishfreak.orgFly-fish & -tie, Nordics, camp & outdoor​

Op 10 okt. 2020 01:48, om 01:48, mymindstorm <notifications@github.com> schreef:

**Comment by mymindstorm** [comment]
For now, I would add a code from a website to the extension first, and then import to Google Authenticator using QR export (hover over code and click QR icon in top right).

**Comment by edegraaff** [comment]
yp thats the way i solved it now

⁣---
Follow us @ https:/www.fishfreak.orgFly-fish & -tie, Nordics, camp & outdoor​

Op 10 okt. 2020 19:13, om 19:13, mymindstorm <notifications@github.com> schreef:

**Comment by Sneezry** [comment]
Let's discuss with this topic https://github.com/Authenticator-Extension/Authenticator/issues/555

Closing this one.
