### ISSUE TITLE
Google auth hides entries even though there are only two.

### ISSUE THREAD

**Issue by annethereshewent** [Authenticator-Extension/Authenticator#538]
**Describe the bug:**

I only have two authentications set up, but this extension keeps hiding one of them, despite the fact that it's the one I use the most. It's super annoying having to click "Show all entries" when there are literally just two of them. Also I can't even select which one to show by default.

**Platform:** 
 - Browser: Chrome (Mac OS)
 - Browser Version: 85.0.4183.121

**Comment by Sneezry** [comment]
We have a feature to disable the smart filter in recent code, and will be available in the next release.
