### ISSUE TITLE
Not working with me logging in to my Assurance agent account

### ISSUE THREAD

**Issue by TMS1977** [Authenticator-Extension/Authenticator#539]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator>
This is the error message that I am receiving below when I right click the inspection button:

background.js:18 Couldn't find enough finder patterns:0 patterns found
d.callback @ background.js:18
DevTools failed to load SourceMap: Could not load content for chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/dist/background.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Platform:** <This is required> :https://login.assurance.com
 - Browser: [Chrome, Firefox] : Chrome
 - Browser Version: Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by mymindstorm** [comment]
Hi, are you trying to scan a code or enter a code to log in?
