### ISSUE TITLE
When you have invalid keys in storage downloading backup will include them

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#54]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

Downloaded backup:
```json
{
  "b20f962cbf083014474164e0504eb65c": {
    "account": "test@security-totp.appspot.com",
    "hash": "b20f962cbf083014474164e0504eb65c",
    "issuer": "",
    "secret": "QXA5R6AHKYP557S2OMVGQNVPIJYELMQD",
    "type": "totp",
    "encrypted": false,
    "index": 0,
    "counter": 0
  },
  "test": "test"
}
```

`test` key should not be there.

```chrome.storage.sync.set({"test": "test"})``` and download backup to repro

**Comment by mymindstorm** [comment]
It'll still import just fine so this isn't that important.

**Comment by Sneezry** [comment]
`delete _data[hash]` before https://github.com/Authenticator-Extension/Authenticator/blob/d9a754e3815dd79eba2c147e56d9438f4afbfce9/src/models/storage.ts#L99

should fix this issue

**Comment by Sneezry** [comment]
fixed.
