### ISSUE TITLE
Invalid Codes

### ISSUE THREAD

**Issue by LBIDist** [Authenticator-Extension/Authenticator#541]
I use the Authenticator on Google Chrome on my desktop.  I have been using it for several months with no issue.  For the last month it has been generating codes that are invalid in the website I need to use daily.

**Comment by mymindstorm** [comment]
Have you tried Menu -> Sync clock?

**Comment by LBIDist** [comment]
Yes, first thing I tried.  Still doesn’t work.

**Comment by mymindstorm** [comment]
Does this happen to all accounts?

**Comment by LBIDist** [comment]
I currently only have the single account on it that does it.  The other one acts OK.

**Comment by mymindstorm** [comment]
I don't think that this a problem with the extension. To confirm this, try exporting using the QR button at the top left of the affected entry and adding the account to another app. To fix this you should recover the account and re-setup codes.
