### ISSUE TITLE
can't install addon to chrome 

### ISSUE THREAD

**Issue by tai-nguyen-ts** [Authenticator-Extension/Authenticator#544]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 

**Platform:** <This is required>
 - Browser: [Chrome, Firefox]
 - Browser Version:

**Comment by mymindstorm** [comment]
Hi, could you provide more details about how you tried to install the extension and what did not work after you tried to install it?
