### ISSUE TITLE
QR code issues

### ISSUE THREAD

**Issue by i0Z3R0** [Authenticator-Extension/Authenticator#547]
This extension works great, except for one issue. When I go to select a QR code, the area is always a dozen or so pixels to the right of my cursor. Also, it can't detect any QR codes, even black ones on a completely white background. 

Browser: Chrome
Browser Version: 86.0.4240.198 (Official Build) (x86_64)

**Comment by mymindstorm** [comment]
Go to About and click on the QR Debugging link, try and scan a QR code, and then send a screenshot of the debugging page.
