### ISSUE TITLE
Error with Authenticator ! Urgently !

### ISSUE THREAD

**Issue by ghost** [Authenticator-Extension/Authenticator#550]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** The code generated by Authenticator is different than that of Google Authenticator 

**Platform:** <This is required>
 - Browser: Chrome
 - Browser Version: /

**Comment by mymindstorm** [comment]
Do you have encryption enabled? Try Settings -> Sync clock with Google

**Comment by ghost** [comment]
Oh
Thank's ! It is genially !
