### ISSUE TITLE
Import from Google Authenticator official mobile app

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#555]
Both iOS and Android version Google Authenticator official mobile app support export data. The export data uses Google private schema of `otpauth-migration:`. Also, the URI is very different from `otpauth:`. Though it's not a standard way, considering to large amount of users of this app, we should support this backup format.

See: https://github.com/google/google-authenticator-android/issues/118

**Comment by mymindstorm** [comment]
closing, implemented
