### ISSUE TITLE
Problems with google drive sync

### ISSUE THREAD

**Issue by akvilibrium** [Authenticator-Extension/Authenticator#557]
**Describe the bug:** Sync with google drive don't work. Tried "manual sync" - no effect. While backup-restore with file is ok (both, encrypted and raw).

**Platform:** 
 - Browser: Chrome
 - Browser Version: 86.0.4240.198

**Comment by akvilibrium** [comment]
Hmm. As I see, actually, it's pushing dumps to gdrive. Maybe it just don't sync it back? Need to download and import manually?

**Comment by mymindstorm** [comment]
It is just a backup pushed to a folder, it won't automatically import. You need to download the file and import it for that. Sync is handled via Chrome extension data sync.

**Comment by akvilibrium** [comment]
> It is just a backup pushed to a folder, it won't automatically import. You need to download the file and import it for that. Sync is handled via Chrome extension data sync.

Get it. It would be cool to point it somewhere in the extension)

**Comment by akvilibrium** [comment]
Ok. I've tested and found another problem. It's for the same theme - gdrive, so I think it would be ok to just reuse this Issue.

I've tried to import encrypted dump from gdrive and it alerts me for failure during import, like the password is incorrect - while it's 100% correct and a dump with same password saved as file manually imports well.

**Comment by mymindstorm** [comment]
I see the issue, do you need a temporary workaround?

**Comment by akvilibrium** [comment]
No. I've just pointed it here for developing of this cool project. Manual export works fine, it's actually enough for me)

**Comment by mymindstorm** [comment]
Thanks for the report, a fix will be in the next version.
