### ISSUE TITLE
Can not connect to OneDrive

### ISSUE THREAD

**Issue by CrazyBoyFeng** [Authenticator-Extension/Authenticator#563]
**Describe the bug:**
I choose OneDrive to sync my data . After I input my microsoft account in the poped up window and clicked the Next, it occured error:
> invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

**Platform:**
 - Browser: Edge
 - Browser Version: 87.0.664.41

**Comment by mymindstorm** [comment]
I have fixed this, please try again and it will work.
