### ISSUE TITLE
iOS to Chrome export/import

### ISSUE THREAD

**Issue by ch4rl1** [Authenticator-Extension/Authenticator#564]
<You can also suggest feedback by Tweeting with #AuthenticatorFeedback>

**Describe the feature you want:**
I'd like to be able to export my stored keys from the iOS Google Authenticator to the Chrome extension. The iOS app gives you an image with a QR code, the chrome extension only accepts text files.

**Why do you want this feature in Authenticator?**
It's useful.

**Comment by mymindstorm** [comment]
Duplicate of #555
