### ISSUE TITLE
How do I copy/share from my iphone google authentication app to here?

### ISSUE THREAD

**Issue by ndvbd** [Authenticator-Extension/Authenticator#582]
How do I copy/share from my iphone google authentication app to here?

**Comment by mymindstorm** [comment]
We have a feature that allows you to import Google Authenticator QR codes that will be released with the next version.

**Comment by chenglu01** [comment]
> We have a feature that allows you to import Google Authenticator QR codes that will be released with the next version.

 When will the next version be released ？

**Comment by ira-at-work** [comment]
Can't wait :-)
I see the latest version on github is the same 6.2.1 as on the dev branch and no relevant PR is waiting, do you need help getting this feature ready for merging and publishing?

**Comment by mymindstorm** [comment]
It's almost done, I'm just waiting a few days until translations come in for a menu string that was changed.

**Comment by ira-at-work** [comment]
well, I can help with Hebrew if it's missing... that's no reason to delay an important feature like that!

**Comment by Sneezry** [comment]
Hi @ira-bv, thanks for your interests to the contribution. You can help to translate at https://crowdin.com/project/authenticator-firefox

Hebrew has been translated 87%

![image](https://user-images.githubusercontent.com/1621293/110446409-18bab280-80fa-11eb-8279-a8491806168c.png)

**Comment by ira-at-work** [comment]
yup, it was at 64% when I started this morning, I think. all done now.
