### ISSUE TITLE
CWS requires privacy policy

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#585]
> 14. My extension or app handles personal or sensitive user data, but only stores information locally (or only uses Chrome Storage Sync API). Do I still need to post a privacy policy? 
> Yes. This policy requires all Products that handle sensitive user information to post a privacy policy. Users may not easily be able to tell which apps or extensions save information locally or transmit it back to their servers. Your privacy policy, however, may not need to be long or complicated. It just needs to describe how the Product collects, uses, and shares user data.

https://developer.chrome.com/docs/webstore/user_data/

**Comment by mymindstorm** [comment]
You may just want to modify

https://addons.mozilla.org/en-US/firefox/addon/auth-helper/privacy/

or 

https://github.com/Authenticator-Extension/authenticator.cc/blob/master/docs/en/edge-privacy.md
