### ISSUE TITLE
Error check code. Please try again

### ISSUE THREAD

**Issue by miller2311** [Authenticator-Extension/Authenticator#588]
How to fix the error? <<Error check code. Please try again>>

<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 

**Platform:** <This is required>
 - Browser: [Chrome, Firefox]
 - Browser Version:

**Comment by mymindstorm** [comment]
Please provide more details about your issue. If your codes are not working, try going to Menu -> Sync clock
