### ISSUE TITLE
Microsof Sign in fix?

### ISSUE THREAD

**Issue by cardonadon** [Authenticator-Extension/Authenticator#589]
<You can also suggest feedback by Tweeting with #AuthenticatorFeedck>
I'm having trouble resetting my MS 
**Describe the feature you want:**
I'm having trouble getting into Ms account. My Authenticator

**Why do you want this feature in Authenticator?**
i dont know.....get it working again

**Comment by mymindstorm** [comment]
Please provide more details and reproduction steps if possible.
