### ISSUE TITLE
Only partial success scanning a QR code

### ISSUE THREAD

**Issue by bseddon** [Authenticator-Extension/Authenticator#590]
**Describe the bug:** 

Like others I'm trying to access 2FA codes from Google Authenticator on Android and I'm having partial success.  I've taken a picture of the QR Code generated on the phone.  This is saved as a file on the laptop and opened in Chrome using file://...  Authenticator is able to scan the QR Code but only opens an alert box - see screenshot.  The account is not added to Authenticator. Should the account be added?

If I deliberately scan only a portion of the QR code, so it's invalid, I get an alert box telling me this so the code seems to have been scanned correctly.

**Platform:** 
 - Browser: Chrome on Windows 10
 - Browser Version: 88

Content of the alert box:
![Screenshot 2021-02-07 223701](https://user-images.githubusercontent.com/1221824/107161576-7e9a0a00-6995-11eb-9ef5-46217719e43e.png)

**Comment by mymindstorm** [comment]
Unfortunately, the code to import this is pending the next release.

**Comment by bseddon** [comment]
Thanks for letting me know. Looking forward to the feature as it will really round out what is already a good extension.
