### ISSUE TITLE
Add Export/Import and Storage/Backup doc

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#599]
If the user doesn't save a backup in last 30 days, we will popup a notification to ask the user to make a backup.

We don't have a doc to guide users how to Export/Import local data or automatically save data to 3rd party storage services.

We need a doc to clarify the difference among Export/Import, Storage/Backup and sync with browser built-in accounts (Google/Mozilla/Microsoft account), and what action should be taken to avoid losing secrets.

Also, we should reference this doc link when we popup the notification to remind the user to make a backup.

**Comment by mymindstorm** [comment]
> difference among Export/Import, Storage/Backup and

What do you think about combining Export/Import and Backup? It may make things clearer. The storage setting can be on its own or under preferences.

**Comment by Sneezry** [comment]
I agree. Export and Backup do the same thing, save a copy of data somewhere else, either local machine or 3rd party drive service. And Import reverts data saved previous. Combining Export/Import and Backup makes the logic more sense.
