### ISSUE TITLE
Codes stopped working, cannot remove/reinstall

### ISSUE THREAD

**Issue by me0wves** [Authenticator-Extension/Authenticator#600]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 
Seemingly all of a sudden, my authenticator codes have stopped working. I removed the add-on with no issue, but when I attempt to reinstall, it brings me to this page: https://authenticator.cc/docs/en/chrome-issues, where it indicates the following: 

REINSTALLING AUTHENTICATOR WILL CLEAR YOUR DATA. NEVER REINSTALL AUTHENTICATOR TO FIX ANY ISSUES

I don't mind if my data is cleared, as I have access to the QR codes in email, but... curious how to fix this. Thanks for any help.

**Platform:** <This is required>
 - Browser: Chrome
 - Browser Version: Version 88.0.4324.150 (Official Build) (x86_64)

**Comment by Sneezry** [comment]
This is a remind message for all users for first installation.
