### ISSUE TITLE
Correct password and not decrypt

### ISSUE THREAD

**Issue by oumuamuax** [Authenticator-Extension/Authenticator#615]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 
 The copy of my security codes is corrupted. I am putting the correct password and it decrypts the codes.
This happened after formatting windows 10.

**Platform:** <This is required>
 - Browser: [Edge]
 - Browser Version: 89.0.774.57

**Comment by Sneezry** [comment]
Try to sync clock with Google

![image](https://user-images.githubusercontent.com/1621293/112010104-f72de200-8b61-11eb-949a-9495686139ae.png)
