### ISSUE TITLE
Setting non-standard characters in account fields breaks extension

### ISSUE THREAD

**Issue by MihaVector** [Authenticator-Extension/Authenticator#63]
Why when I try to open the program can only see a white window, and the codes do not appear?

**Comment by Sneezry** [comment]
Hi @MihaVector , this is a known issue in 5.0.4, your data is safe, please DON'T reinstall the extension, or your data will be removed, and no one can help you. I will tell you how to fix the issue.

1. open the popup page, right click and select Inspect

<img width="344" alt="screen shot 2018-03-04 at 18 38 44" src="https://user-images.githubusercontent.com/1621293/36944630-9fbf2898-1fdb-11e8-9869-4ad187e1f2b0.png">

2. in the new window, click console, and paste this line into the window, then click enter

<img width="653" alt="screen shot 2018-03-04 at 18 39 46" src="https://user-images.githubusercontent.com/1621293/36944638-bfe546de-1fdb-11e8-9511-3edd38014c1e.png">

3. copy the code carefully

<img width="652" alt="screen shot 2018-03-04 at 18 40 00" src="https://user-images.githubusercontent.com/1621293/36944645-dbd84d1e-1fdb-11e8-8f50-f8baf364305a.png">

4. open popup, and click import / export

<img width="329" alt="screen shot 2018-03-04 at 18 40 16" src="https://user-images.githubusercontent.com/1621293/36944648-ee068866-1fdb-11e8-88cc-8da7279ce09a.png">

5. click import backup

<img width="330" alt="screen shot 2018-03-04 at 18 40 25" src="https://user-images.githubusercontent.com/1621293/36944653-f54f24b6-1fdb-11e8-8c85-2ca229393e1d.png">

6. click import backup text, and paste the code into the box, if you set a password, check encrypted box and enter the password, then click import backup button

<img width="1280" alt="screen shot 2018-03-04 at 18 40 52" src="https://user-images.githubusercontent.com/1621293/36944664-1fa03b10-1fdc-11e8-9e53-09bd7cad7f4c.png">

We have released a new master version, and there're some different between data format of new version and old version. We just released 5.0.5 to handle data migration issue hours ago.

Please feel free to ask me any question if you still have trouble to use the extension.

Again, please never try to reinstall the extension to fix any issue, or your data will be removed.

**Comment by krabiki** [comment]
Hello, I too have this problem "white window". How can I fix it on Firefox ?

**Comment by Sneezry** [comment]
@mymindstorm Could you please help @krabiki for firefox issue?

**Comment by Sneezry** [comment]
@MihaVector Could you please post the console screenshot? It's the window opened after you click inspect on popup

**Comment by Sneezry** [comment]
@MihaVector Also, what can you see when you open

`chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/import.html` in browser? Is it blank as well?

**Comment by mymindstorm** [comment]
@Sneezry a white extension window appears on an exception, likely some form of malformed data we didn't check against.

@krabiki please [follow these steps](https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information) and give us a screenshot of that window.

**Comment by MihaVector** [comment]
@mymindstorm 
![2](https://user-images.githubusercontent.com/22991137/36951038-af4ff718-200f-11e8-9ddc-22f4b82c00a6.png)

**Comment by MihaVector** [comment]
@Sneezry Yes, when I go over this link, I only see the white background

**Comment by mymindstorm** [comment]
@Sneezry reproduce by setting a sting like `✓ à la mode` in the issuer.

Affected lines:
https://github.com/Authenticator-Extension/Authenticator/blob/3b086a9545389d7ac26b12163befcc34179029d6/src/ui/entry.ts#L55-L61

@MihaVector do you use any non-standard characters to name any of your codes?

**Comment by MihaVector** [comment]
@mymindstorm Like no, I used only letters of the Latin alphabet

**Comment by mymindstorm** [comment]
@MihaVector paste this into the bottom of the console window you opened:
```javascript
chrome.storage.sync.get(str => {console.log(btoa(JSON.stringify(str)))})
```
Does it error with `InvalidCharacterError`?

Now enter this into your console:
```javascript
chrome.storage.sync.get(str => {console.log(btoa(encodeURIComponent(JSON.stringify(str)).replace(/%([0-9A-F]{2})/g,function toSolidBytes(match, p1){return String.fromCharCode('0x' + p1);})))});
```
Did it error? (don't paste what it returns if it is successful!)

**Comment by MihaVector** [comment]
Yes, after the first command issued "InvalidCharacterError". And when I introduced second, has now issued:
eyIzN2E3NzE5ZDk3OTExMzIzOTUxNWVhMGI1NWE0NDRmNSI6eyJhY2NvdW50Ijoia2Jpc2Vyb3YtZGVtb24yMDE0QHlhbmRleC5ydSIsImhhc2giOiIzN2E3NzE5ZDk3OTExMzIzOTUxNWVhMGI1NWE0NDRmNSIsImluZGV4IjoxLCJpc3N1ZXIiOiLQntGCJm5ic3A70LDQutC60LDRg9C90YLQsCZuYnNwO9C+0LTQvdC+0LrQu9Cw0YHRgdC90LjQutC+0LIiLCJzZWNyZXQiOiJCR0E0IDdWTzMgRUNRNSBXNlNDIiwidHlwZSI6InRvdHAifSwiODZkOWEyMzlhOTY2OTg1MDMyNmRkZjhlZjYwODg5MGYiOnsiYWNjb3VudCI6ImtiaXNlcm92LWRlbW9uMjAxNEB5YW5kZXgucnUiLCJoYXNoIjoiODZkOWEyMzlhOTY2OTg1MDMyNmRkZjhlZjYwODg5MGYiLCJpbmRleCI6MCwiaXNzdWVyIjoi0J7RgiZuYnNwO9Cw0LrQutCw0YPQvdGC0LAmbmJzcDtHYWlqaW4iLCJzZWNyZXQiOiJBUU5aM0VQNTRGUkNJRTdVIiwidHlwZSI6InRvdHAifX0=

**Comment by mymindstorm** [comment]
I've removed what you pasted, those were your secrets. Next time, please listen to me about not pasting things.

Thanks for the info, we will push an update soon to fix the issue.

**Comment by MihaVector** [comment]
@mymindstorm Sorry, I'm just from Russia, you're hard to understand with an online translator

**Comment by mymindstorm** [comment]
It's ok, I should have been more clear. You should change your secrets since you posted them though.

**Comment by MihaVector** [comment]
@mymindstorm I was kind of messing with secrets.

**Comment by MihaVector** [comment]
@mymindstorm I take it you fixed something, but I still have a white window

**Comment by mymindstorm** [comment]
The update still needs to be reviewed and pushed to users. I'll give you instructions on how to update when it is released.

**Comment by MihaVector** [comment]
@mymindstorm Thank you for the information

**Comment by mymindstorm** [comment]
@MihaVector version 5.0.6 has fix and is available from the web store, follow [these instructions](https://github.com/Authenticator-Extension/Authenticator/issues/64#issuecomment-370291688) to update.

**Comment by MihaVector** [comment]
@mymindstorm Thanks for the update, is no longer an issue, I can see again your code, and not the white box.

**Comment by adsactly** [comment]
Horrible issue it says I have some keys that Encrypted and some that are not how is that possible I only set the one password. But I think the new version had me enter a password and I think I screwed EVERYTHING Up by entering a different one I thought it wanted a different password?

**Comment by adsactly** [comment]
We have tried everything please HELP we are freaking out now :(
