### ISSUE TITLE
Microsoft Azure 2FA

### ISSUE THREAD

**Issue by fporta044** [Authenticator-Extension/Authenticator#632]
**Describe the bug:**
When i scan QR code a message appears, but the account is not registered.
Azure display a code and an URL, but i don't find where i can register these info on the authenticator extension.
Please see the Microsoft document. below the link
https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-setup-auth-app

**Platform:** Microsoft Windows 10
 - Browser: Chrome 
 - Browser Version:  89.0.4389.90
 - App version; 6.3.0

thanks a lot

**Comment by Sneezry** [comment]
You may find a link like this to setup 3rd party authenticator app for Microsoft account

![image](https://user-images.githubusercontent.com/1621293/112202119-fcfff200-8c4b-11eb-99fe-7ab4efa9acbf.png)

And you will see generic setup steps for 2fa

![image](https://user-images.githubusercontent.com/1621293/112202318-35073500-8c4c-11eb-8c35-7960273a77e0.png)

**Comment by Sneezry** [comment]
No further feedback from user. Closing.
