### ISSUE TITLE
Unrecognized QR code

### ISSUE THREAD

**Issue by cookieboyeli** [Authenticator-Extension/Authenticator#634]
Extension version: 6.3.0 

Images are pretty self explanatory.
As you can see scanning results in this error:
![image](https://user-images.githubusercontent.com/5998991/112732317-8eeb5180-8f0f-11eb-9082-3328d529d949.png)
I'm guessing this is some different type of QR code? 
I'd love to use the alternative manual entry method but it's not supported either. That leads me to believe this is some sort of unsupported format. 

![image](https://user-images.githubusercontent.com/5998991/112732372-f99c8d00-8f0f-11eb-997d-0a0d7396a641.png)

Browser version:
![image](https://user-images.githubusercontent.com/5998991/112732330-a32f4e80-8f0f-11eb-9ca2-ea0923578398.png)

Hopefully it's not too much trouble to fix! I hate using an app on my phone if i don't have to. It's connected to too many things to trust. Secure "in theory", but is it really?

**Comment by Sneezry** [comment]
> I'd love to use the alternative manual entry method but it's not supported either. That leads me to believe this is some sort of unsupported format.

What is the error message when you use manual entry

**Comment by cookieboyeli** [comment]
There is no manual entry option available in this app.

If there is please let me know where it is because I cannot see it.

**Comment by mymindstorm** [comment]
https://authenticator.cc/docs/en/quickstart
