### ISSUE TITLE
Codes are not suitable

### ISSUE THREAD

**Issue by BlagoYar** [Authenticator-Extension/Authenticator#639]
Added the scanned code, clicked "synchronize" - success, but the codes are not suitable.
Although the same QR code scanned in the phone - codes work.

Windows 7 x64
Edge for Windows 7
89.0.774.63

**Comment by mymindstorm** [comment]
If you scan the QR code that is in the extension (top right of the account) into your phone, are the codes the same?

**Comment by BlagoYar** [comment]
> If you scan the QR code that is in the extension (top right of the account) into your phone, are the codes the same?

The fact of the matter is that no, they do not coincide.

**Comment by BlagoYar** [comment]
In general, it turned out from the third time (disabled / connected two-factor authorization) and start showing faithful codes.

**Comment by BlagoYar** [comment]
Close the ticket

**Comment by mymindstorm** [comment]
> > If you scan the QR code that is in the extension (top right of the account) into your phone, are the codes the same?
> 
> The fact of the matter is that no, they do not coincide.

Did you have extension data sync enabled? Data corruption should not happen.
