### ISSUE TITLE
White window issue

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#64]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

@krabiki can you follow the steps [here](https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information#firefox) then open the extension and go to the "white window". Copy and paste any console messages here.

Also, when does the "white window" appear? When you open the extension or when you try to import?

**Comment by krabiki** [comment]
Hello again, my "white window" means that i cant authorize in authenticator. It wants  QR code, but I dont have one. 

![123123](https://user-images.githubusercontent.com/37041721/36954499-87f33a94-2033-11e8-8cb2-28bba19cee3a.png)

Here is console info - 

Unchecked lastError value: Error: No matching message handler ExtensionCommon.jsm:407
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Подробнее] ExtensionContent.jsm:357:18
Загрузка <script> с источником «blob:null/cc70fa69-a3a6-4da5-b51f-8517e705505d» не удалась.  blank:1
Загрузка <script> с источником «blob:null/1d608b5a-f5ac-4b31-aa33-0b9af548cd90» не удалась.  blank:1
unreachable code after return statement[Подробнее]  wistia.js:247:3
unreachable code after return statement[Подробнее]  master.js:332:3
Error: Could not establish connection. Receiving end does not exist. undefined
Use of nsIFile in content process is deprecated.  NetUtil.jsm:307:12
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Подробнее]  ExtensionContent.jsm:357:18
Unchecked lastError value: Error: Missing host permission for the tab ExtensionCommon.jsm:407
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
Unchecked lastError value: Error: Missing host permission for the tab ExtensionCommon.jsm:407
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
Загрузка <script> с источником «blob:null/1a14ab3b-6c59-4e5b-bb7e-5cda65c07fb7» не удалась.  blank:1
TypeError: context.contentWindow is null[Подробнее]  ExtensionContent.jsm:342:11
Загрузка <script> с источником «blob:null/0972cdb5-4304-409d-90e3-8101aa085573» не удалась.  blank:1
Error: Could not establish connection. Receiving end does not exist. undefined
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Подробнее]  ExtensionContent.jsm:357:18
Error: ext is not defined  undefined
Error: Could not establish connection. Receiving end does not exist. undefined
Error: ext is not defined  undefined
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Подробнее]  ExtensionContent.jsm:357:18
Error: Could not establish connection. Receiving end does not exist.  undefined
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Подробнее] ExtensionContent.jsm:357:18
Use of nsIFile in content process is deprecated. NetUtil.jsm:307:12
Key "2d0dca4fe984d17a7a10638761bb6387" is not OTPStorage  storage.js:65:17
Key "b0a761362a75086faf6a27082cd3dbc8" is not OTPStorage  storage.js:65:17
Key "2d0dca4fe984d17a7a10638761bb6387" is not OTPStorage  storage.js:65:17
Key "b0a761362a75086faf6a27082cd3dbc8" is not OTPStorage  storage.js:65:17
Key "2d0dca4fe984d17a7a10638761bb6387" is not OTPStorage  storage.js:65:17
Key "b0a761362a75086faf6a27082cd3dbc8" is not OTPStorage  storage.js:65:17
Ошибка карты кода: TypeError: NetworkError when attempting to fetch resource.
URL ресурса: moz-extension://78163b86-e975-49dd-a18f-5b14f638b997/build/models/storage.js
URL карты кода: storage.js.map[Подробнее]

**Comment by mymindstorm** [comment]
Are you on version 5.0.4? If so go to `chrome://extensions`, check "Developer Mode", and then click "Update Extensions Now" and confirm that Authentiactor is 5.0.5
![image](https://user-images.githubusercontent.com/27789806/36954746-9faa38c6-1fe9-11e8-803c-9c31b152b67e.png)

**Comment by mymindstorm** [comment]
For Firefox go to `about:addons`, click the gear, and then "check for updates"
![image](https://user-images.githubusercontent.com/27789806/36954820-29800508-1fea-11e8-98d1-185be49167c9.png)

**Comment by krabiki** [comment]
Ohh ty man, it worked ) I thought if i update aplication all data will be lost.

**Comment by mymindstorm** [comment]
Nope, if you remove in chrome you lose application data, but that dosen't seem to be case for firefox. Usually it updates automatically in the background, so you wouldn't notice most of the time.

**Comment by AMND3110** [comment]
Hi @mymindstorm, I also met the issue "white window". Then, I removed app and re-
 installed new it. But when re-opening pop up, I still get "white window" 
![white window](https://user-images.githubusercontent.com/36392748/36960224-900f7e5a-2078-11e8-9eee-f4a93405d790.PNG)
Do you have any idea to get the lose application data? please help me

**Comment by mymindstorm** [comment]
@AMND3110 what version are you using?

**Comment by AMND3110** [comment]
version 5.0.5
![version](https://user-images.githubusercontent.com/36392748/36960402-758194b4-2079-11e8-88b5-45f6efebe55b.PNG)

**Comment by mymindstorm** [comment]
@AMND3110 [follow these steps](https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information#chrome)

**Comment by Benelux11** [comment]
I have version 5.0.5 Now I have a white window. I press the "update" button, but nothing happens.

**Comment by mymindstorm** [comment]
@Benelux11 are you using Firefox or chrome?

**Comment by Benelux11** [comment]
i'm using chrome

**Comment by mymindstorm** [comment]
@Benelux11 try to use the update menu button again, then reboot and see if you have 5.0.6. If that does not work, then follow these steps:

1. Open the popup page, right click and select "Inspect"

<img width="344" alt="screen shot 2018-03-04 at 18 38 44" src="https://user-images.githubusercontent.com/1621293/36944630-9fbf2898-1fdb-11e8-9869-4ad187e1f2b0.png">

2. In the new window click the console button at the top
3. Paste
 ```javascript
chrome.storage.sync.get(data=>console.log(JSON.stringify(data,null,2)))
```
 into the bottom of the console window and press enter

<img width="653" alt="screen shot 2018-03-04 at 18 39 46" src="https://user-images.githubusercontent.com/1621293/36944638-bfe546de-1fdb-11e8-9511-3edd38014c1e.png">

3. This is a backup of your codes. Copy it, and make sure that you only copy the text starting with `{` and ending with `}`

Example:

```json
{"22e991a1711a51f8aab522081666b5d3":{"account":"test","hash":"22e991a1711a51f8aab522081666b5d3","issuer":"","secret":"A3MUFPMUQTCNVAAODBRONWFL3KLOFPSK","type":"totp","encrypted":false,"index":0,"counter":0}}
``` 

<img width="652" alt="screen shot 2018-03-04 at 18 40 00" src="https://user-images.githubusercontent.com/1621293/36944645-dbd84d1e-1fdb-11e8-8f50-f8baf364305a.png">

4. Save your backup somewhere safe, or you will lose your codes.
5. Uninstall Authenticator from Chrome (**this will clear your data, make sure you save your backup!**)
6. Go to the chrome web store and install Authenticator. After it installs confirm that you have version 5.0.6
7. Use [these instructions](https://github.com/Authenticator-Extension/Authenticator/wiki/Old-Backups) to import your backup

**Comment by Benelux11** [comment]
У меня есть 16-значный ключ. Почему я не могу просто удалить расширение, а
затем переустановить его. И заново установите 16-значный ключ?

2018-03-08 0:23 GMT+02:00 mymindstorm <notifications@github.com>:

**Comment by Benelux11** [comment]
I have a 16-digit key. Why can not I just delete the extension, and then reinstall it. And re-tie the 16-digit key?

**Comment by mymindstorm** [comment]
If you mean "16-digit key" as in the same secret you used to add the codes, then yes you can do it that way. The important part is reinstalling to force an update, you can re-add your codes however you want.

**Comment by adsactly** [comment]
We are already on Version 5.0.6 and our Issue is WORSE now we can unencrypt all our secrets, Secrets are duplicated multiple times, some of our secrets are encrypted some are not, We think we have 2 passphrases but how could this be possible. It should have a error saying you have password already instead of setting 2 this is BIG MESS we hope you guys can help fix this.

**Comment by Sneezry** [comment]
@adsactly What can you see in Console? You can get it by following https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information

**Comment by Sneezry** [comment]
@adsactly Also, what is the output when you run

```
chrome.storage.sync.get(d=>{for(let k in d){delete d[k].secret};console.log(JSON.stringify(d,null,2));})
```

in Console? Your secrets have been removed by the script.

**Comment by adsactly** [comment]
OK That didn't fix the issue. I think when we typed an invalid password once we made things even worse :(

**Comment by adsactly** [comment]
OK We Imported the Old Backup from a few months back which doesn't have all the keys we added recently but it will have to do. It looks like its working now with the latest version none of the entries showed up Encrypted or Invalid.

However this was done on Sandbox Chrome where would we find the Data that we need to copy over to our main installation of Chrome is it in the Appdata Local or Roaming or both?

**Comment by adsactly** [comment]
@sneery did you want us to post the output that we got when we pasted the command in the console that you asked us to do?

**Comment by adsactly** [comment]
OK We were able to fix the issue by removing the app from our main chrome and importing the backup.json file which is a new feature and we have to say we LOVE it!

Only issue is a few codes are missing because this was an older backup I guess we can try manually adding them but it looks like with the new version 5.0 its not as easy to add new codes from old backups.

**Comment by Sneezry** [comment]
@adsactly I'm very sorry for troubles we take to you. v4 was written in 2014 when I was in school, and its code is too dirty to maintain.

I want to refine the extension more than one year ago, and I did it at the beginning of 2018.

I and @mymindstorm do have many tests before release new version, however, this extension has only two developers, but about 300k users.

We pushed v5.0.4, v5.0.5 and v5.0.6 to 1% users, and later we pushed v5.0.6 to 5% users, 10% users, and now 20% users. We really take carefully about new releases, and we know that any error may make a big trouble to our users.

The only thing for us to do is to add more test cases. And I hope you can understand our difficulty.

If your backup cannot import to v5, you can just add it manually. You can find secret field in every entry.

If your backup is encrypted, open popup page, click inspect on context menu, switch to Console tab, copy & paste code below:

```
CryptoJS.AES.decrypt(<encryptedSecret>, <password>).toString(CryptoJS.enc.Utf8)
```

Remember to change `<encryptedSecret>` to the encrypted secret in backup, and `<password>` to your password, then you will see your secret.

**Comment by FirmanTaufik** [comment]
i try to paste 

> chrome.storage.sync.get(data=>console.log(JSON.stringify(data,null,2)))

 but doesnot work... conseole dosnot show anything... i worried what will happen on my bitcoin wallet... i cant login sofar 
![image](https://user-images.githubusercontent.com/25864767/37237511-a75f1a08-2446-11e8-9597-e4fa6f08fade.png)

**Comment by mymindstorm** [comment]
@FirmanTaufik did you reinstall the extension? What version are you using?

Whatever the case, if that command shows nothing your data is gone. Restore from a backup if you have one. If you do not have a backup [follow these instructions](https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes)

**Comment by FirmanTaufik** [comment]
good idea.... maybe i should try it.. but if i wanna use this Google Authenticator is it will work for further?? cause any website asking the code when register..

**Comment by mymindstorm** [comment]
@FirmanTaufik I would really appreciate it if you could give me your extension version.

**Comment by FirmanTaufik** [comment]
i think this is newest  5.0.6 my Google Crome say it...
![image](https://user-images.githubusercontent.com/25864767/37237699-aed06ffa-2449-11e8-8797-72111977c197.png)
