### ISSUE TITLE
macOS Safari Support

### ISSUE THREAD

**Issue by mitchellknight** [Authenticator-Extension/Authenticator#651]
<You can also suggest feedback by Tweeting with #AuthenticatorFeedback>

**Describe the feature you want:**

Safari 14 for macOS now supports [WebExtensions](https://developer.apple.com/safari/extensions/). With some work, Authenticator could add support for us Safari users.

**Issues**

- I'm not sure if the APIs are 1:1 compatible.
- You would likely need a Mac and Apple Developer account ($99/year) to build, sign, and distribute it. Also, Apple's blessing to distribute on the App Store.

**Why do you want this feature in Authenticator?**

I'm a Safari user and this extension is one of the few I miss since switching away from Chrome/Firefox.

**Comment by mymindstorm** [comment]
Unfortunately, this likely won't happen because I don't have any MacOS devices to test on nor am I willing to pay for the developer account. Last time I checked, they still don't have any free open source developer accounts.

**Comment by churnikov** [comment]
Hello!

>  I don't have any MacOS devices to test on nor am I willing to pay for the developer account

You could test and develop in this docker container
https://github.com/sickcodes/Docker-OSX

> Last time I checked, they still don't have any free open source developer accounts.

And you could distribute .dmg file as a binary file on GitHub

**Comment by Sneezry** [comment]
I'm setting `won't fix` for this issue, but still open to discuss.

**Comment by Sneezry** [comment]
Remove `wontfix` label. We are working on investigation of Safari version.

**Comment by rebornix** [comment]
We have published our initial support for Safari to the store https://apps.apple.com/us/app/authen/id1602945200?mt=12 , note that due to the compatibility issues on Safari, this version came with following limitations and tweaks

* Google Drive/Dropbox/Onedrive backup not supported
* Manual down doesn't have pre-defined file 

To make it look natural on Safari, we also introduced a new Flat theme, which is picked by default on Safari.

Feel free to give it a try and let us know how it works.

**Comment by ImprovedTube** [comment]
hi guys! / @mymindstorm  @rebornix   how come nobody uses this? how many % apple users do you see in chrome webstore?

**Comment by patterueldev** [comment]
> We have published our initial support for Safari to the store https://apps.apple.com/us/app/authen/id1602945200?mt=12 , note that due to the compatibility issues on Safari, this version came with following limitations and tweaks
> 
> * Google Drive/Dropbox/Onedrive backup not supported
> * Manual down doesn't have pre-defined file
> 
> To make it look natural on Safari, we also introduced a new Flat theme, which is picked by default on Safari.
> 
> Feel free to give it a try and let us know how it works.

It was kinda hard to find this, but when I was searching at App Store, I recognized the screenshots immediately.
But I wasn't sure if it's the same developer. But I only got to find your comment here regarding this.

Which begs the question. Why isn't this pointed out in authenticator.cc? Wouldn't it be helpful to have a reference of this app through your website?

And I think there's less Apple users using this. Currently I am only using this for development and it's pretty helpful.
