### ISSUE TITLE
Importing data does not work

### ISSUE THREAD

**Issue by viveksh1** [Authenticator-Extension/Authenticator#659]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** When I import my data from the extension, it doesn't work. I tired importing the JSON file and the text file from my previous backup, when I clicked the button nothing happened. No warning, no progress, nothing. I tired reinstalling the extension to no avail.

**Platform:** <This is required>
 - Browser: Edge
 - Browser Version: Version 90.0.818.56 (Official build) (64-bit)

**Comment by mymindstorm** [comment]
What is the extension version?
Could you show the console messages from the import page after trying to import unsuccessfully (F12 -> Console -> then reproduce issue)?

**Comment by viveksh1** [comment]
@mymindstorm 

**I am running version 6.3.0**

When loading the page:
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://ocglkepbibnalbgmbachknglpdipeoio/dist/import.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load SourceMap: Could not load content for chrome-extension://ocglkepbibnalbgmbachknglpdipeoio/css/import.css.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```
When pasting the JSON file as a text backup:
```
import.js:9 TypeError: Cannot read property 'secret' of null
    at F (import.js:33)
    at s.<anonymous> (import.js:33)
    at import.js:33
    at Object.next (import.js:33)
    at import.js:33
    at new Promise (<anonymous>)
    at S (import.js:33)
    at s.importBackupCode (import.js:33)
    at click (import.js:33)
    at Ht (import.js:9)
$t @ import.js:9
Zt @ import.js:9
Ut @ import.js:9
(anonymous) @ import.js:9
Promise.catch (async)
Ht @ import.js:9
r @ import.js:9
o._wrapper @ import.js:9
```
When uploading the JSON file as a file backup:
```
import.js:33 Uncaught (in promise) TypeError: Cannot read property 'encrypted' of null
    at s.<anonymous> (import.js:33)
    at import.js:33
    at Object.next (import.js:33)
    at import.js:33
    at new Promise (<anonymous>)
    at h (import.js:33)
    at FileReader.n.onload (import.js:33)
(anonymous) @ import.js:33
(anonymous) @ import.js:33
(anonymous) @ import.js:33
(anonymous) @ import.js:33
h @ import.js:33
n.onload @ import.js:33
load (async)
importFile @ import.js:33
change @ import.js:33
Ht @ import.js:9
r @ import.js:9
o._wrapper @ import.js:9
```

**Comment by mymindstorm** [comment]
You may have been impacted by a serious bug with encrypted backup. If you are familiar with JSON, could you redact the `secret`, `issuer`, `account`, and all fields on `key`; then post your backup file?

**Comment by Sneezry** [comment]
<del>@mymindstorm it seems we have a bug in this line. It should be `for...of...`</del>

https://github.com/Authenticator-Extension/Authenticator/blob/347ca6e4f78f2ea38e681ab9fb55c09dae02db7a/src/components/Import/FileImport.vue#L88

---

<del>Correct: We should use `for...of Object.keys`. The above code also get `length` in hash.</del>

---

Ignore my above comment.

**Comment by Sneezry** [comment]
@VladPutinEu is your backup encrypted or in plain text?

**Comment by viveksh1** [comment]
@Sneezry I did not encrypt it with a password and encryption is off. It is plain text.

**Comment by viveksh1** [comment]
@mymindstorm 
```
{
  "08cb568c-0274-4d06-b32e-f7142f96d87a": {
    "encrypted": false,
    "hash": "08cb568c-0274-4d06-b32e-f7142f96d87a",
    "index": 8,
    "type": "totp"
  },
  "0a437011-4af8-4782-b9dc-63bd8f8a53d2": {
    "encrypted": false,
    "hash": "0a437011-4af8-4782-b9dc-63bd8f8a53d2",
    "index": 14,
    "type": "totp"
  },
  "1207f0e2-267d-4353-b63f-d0954dea0194": {
    "encrypted": false,
    "hash": "1207f0e2-267d-4353-b63f-d0954dea0194",
    "index": 7,
    "type": "totp"
  },
  "134f1689-7ba7-4ee3-97fe-72487ee28ebd": {
    "encrypted": false,
    "hash": "134f1689-7ba7-4ee3-97fe-72487ee28ebd",
    "index": 4,
    "type": "totp"
  },
  "1c066d19-8109-4385-b70f-e5d3db35c416": {
    "encrypted": false,
    "hash": "1c066d19-8109-4385-b70f-e5d3db35c416",
    "index": 13,
    "type": "totp"
  },
  "244532f3-8081-4e24-8383-c8ec0602a961": {
    "encrypted": false,
    "hash": "244532f3-8081-4e24-8383-c8ec0602a961",
    "index": 2,
    "type": "totp"
  },
  "28abae71-2eba-4c37-a49f-0daa0dbcfe69": {
    "encrypted": false,
    "hash": "28abae71-2eba-4c37-a49f-0daa0dbcfe69",
    "index": 5,
    "type": "totp"
  },
  "67a22658-6fb5-4e92-a7de-d791621697fb": {
    "encrypted": false,
    "hash": "67a22658-6fb5-4e92-a7de-d791621697fb",
    "index": 1,
    "type": "totp"
  },
  "7740b92d-04dd-46cc-ab4b-113d11a21d27": {
    "encrypted": false,
    "hash": "7740b92d-04dd-46cc-ab4b-113d11a21d27",
    "index": 15,
    "type": "totp"
  },
  "b29ea287-b836-46b8-b69a-e2019e4dc0f8": {
    "encrypted": false,
    "hash": "b29ea287-b836-46b8-b69a-e2019e4dc0f8",
    "index": 9,
    "type": "totp"
  },
  "c203cc08-3f92-48a4-b560-3b2e9dd15733": {
    "encrypted": false,
    "hash": "c203cc08-3f92-48a4-b560-3b2e9dd15733",
    "index": 10,
    "type": "totp"
  },
  "c9f4cbd2-2741-49b6-b4b5-d3888cfdd0c8": {
    "encrypted": false,
    "hash": "c9f4cbd2-2741-49b6-b4b5-d3888cfdd0c8",
    "index": 12,
    "type": "totp"
  },
  "d1ad0b9d-2e8e-4ee1-9263-49831647d64a": {
    "encrypted": false,
    "hash": "d1ad0b9d-2e8e-4ee1-9263-49831647d64a",
    "index": 0,
    "type": "totp"
  },
  "d3cb6c43-b940-4725-abcf-df9382b3eef3": {
    "encrypted": false,
    "hash": "d3cb6c43-b940-4725-abcf-df9382b3eef3",
    "index": 3,
    "type": "totp"
  },
  "dcb6b692-a9d6-4349-bae6-1916f0068ddf": {
    "encrypted": false,
    "hash": "dcb6b692-a9d6-4349-bae6-1916f0068ddf",
    "index": 6,
    "type": "totp"
  },
  "fc792d61-89bd-462c-a548-1ccecd30cb13": {
    "encrypted": false,
    "hash": "fc792d61-89bd-462c-a548-1ccecd30cb13",
    "index": 11,
    "type": "totp"
  },
  
}
```

**Comment by Sneezry** [comment]
> @Sneezry I did not encrypt it with a password and encryption is off. It is plain text.

That makes thing simple. You can open the JSON file with Windows Notepad, and you will see your data in the file. If you do not have too many accounts in the file, you can add they manually again for an urgent workaround.

A sample:

```
{
  "ffffffff-ffff-ffff-ffff-ffffffffffff": {
    "encrypted": false,
    "hash": "ffffffff-ffff-ffff-ffff-ffffffffffff",
    "index": 0,
    "type": "totp",
    "secret": "xxxxxxxx",
    "issuer": "AAAAAAAA",
    "account": "BBBBBBBB"
  },
  ...
}
```

`xxxxxxxx` is the secret, `AAAAAAAA` is the issuer and `BBBBBBBB` is the account.

![image](https://user-images.githubusercontent.com/1621293/117578321-551d8580-b120-11eb-924c-c589a2f8f5a9.png)

**Comment by viveksh1** [comment]
@Sneezry Yes, I could do that, but I have many accounts and that would take a while. It would be a lot easier if I could just paste it in or upload the file.

**Comment by Sneezry** [comment]
Sure. That's only for urgent workaround. We may need some time to figure out the root case and release a bugfix for it.

**Comment by Sneezry** [comment]
Can you see any `null` word in your backup file?

**Comment by viveksh1** [comment]
> Can you see any `null` word in your backup file?

@Sneezry Yes my ```key``` value has the ```null``` value.

**Comment by Sneezry** [comment]
Could you remove the `key` section in your backup file and try again? Don't forget to remove the comma in the last section:

Before:

```
{
  ...
  "ffffffff-ffff-ffff-ffff-ffffffffffff": {
    "encrypted": false,
    "hash": "ffffffff-ffff-ffff-ffff-ffffffffffff",
    "index": 0,
    "type": "totp",
    "secret": "xxxxxxxx",
    "issuer": "AAAAAAAA",
    "account": "BBBBBBBB"
  },                   <------- this comma also need remove
  "key": null
}
```

After::

```
{
  ...
  "ffffffff-ffff-ffff-ffff-ffffffffffff": {
    "encrypted": false,
    "hash": "ffffffff-ffff-ffff-ffff-ffffffffffff",
    "index": 0,
    "type": "totp",
    "secret": "xxxxxxxx",
    "issuer": "AAAAAAAA",
    "account": "BBBBBBBB"
  }
}
```

**Comment by mymindstorm** [comment]
This is caused by enabling 3rd party backup with unencrypted secrets, we try to encrypt by default. @VladPutinEu this is highly discouraged, you should put a password on your data.

**Comment by viveksh1** [comment]
@Sneezry It works after removing the ```key``` section.

**Comment by viveksh1** [comment]
@mymindstorm I am aware of this and was planning on setting a password, I now have done so.

**Comment by Sneezry** [comment]
> @Sneezry It not works after removing the `key` section.

Is the console message changed? Is there any other sections have `null` value in the backup file?

**Comment by viveksh1** [comment]
> > @Sneezry It not works after removing the `key` section.
> 
> Is the console message changed? Is there any other sections have `null` value in the backup file?

@Sneezry It worked perfectly after removing the ```key``` section, I just made a typo.

**Comment by Sneezry** [comment]
Cool! Thanks for the update.
