### ISSUE TITLE
Filter is not working

### ISSUE THREAD

**Issue by Tharn** [Authenticator-Extension/Authenticator#667]
**Describe the bug:**

Ever since a certain version, the smart filter stopped working. Whether or not I have the setting enabled, I always get a list of all accounts in my Authenticator window.

**Platform:**
 - Browser: Firefox ESR
 - Browser Version: 78.10.1esr x64

**Comment by mymindstorm** [comment]
Please follow [these steps](https://authenticator.cc/docs/en/debug-info) and try to reproduce the issue. If you if you add `::website.com` to the end of an account name (E.g. `Google` becomes `Google::google.com`) it will override the site that filter will activate on.

**Comment by Tharn** [comment]
```The Components object is deprecated. It will soon be removed. regex.js:12:20
Use of nsIFile in content process is deprecated. NetUtil.jsm:253:8
Add Dragula plugin: 
Object {  }
vue-dragula.js:3079:11
TypeError: PrecompiledScript.executeInGlobal: Argument 1 is not an object. ExtensionContent.jsm:567:25
Add Dragula plugin: 
Object {  }
vue-dragula.js:3079:11

```

I put a ::website behind every entry, but it still gives me all entries for every website.

**Comment by ChrisTiffin** [comment]
I've had the same issue (autofill also stopped working). I fixed it by going to about:addons, Authenticator -> Permissions and and turning on "Access your data for all web sites".

This was on Firefox 89.0 x64, with Authenticator v6.3.2

**Comment by Tharn** [comment]
Interesting. I wanted to try it, but I only get "This extension doesn't require any permissions."
I think there is the issue.. the extension should require *some* permissions, idk why I'm not having any set.

Even when uninstalling and adding the extension again from Mozilla, I am not prompted to grant any permissions.

**Comment by Sneezry** [comment]
It could be the active tab permission issue.

To Chrome, we ask `activeTab` permission, so that the extension is able to get current tab title and URL for smart filter

https://github.com/Authenticator-Extension/Authenticator/blob/dev/manifests/manifest-chrome.json#L53

To Firfox, `activeTab` permission is not supported (not sure if it has already been supported in the latest version), and we require all URL permission (access your data for all web sites) instead. Since a certain version, we changed this permission optional for security reason, and you have to enable that permission manually as @cjtiffin mentioned.

https://github.com/Authenticator-Extension/Authenticator/blob/dev/manifests/manifest-firefox.json#L48

The result is, if you do not grant the extension access all web sites permission in Firefox, the extension will not be able to get the current tab title and URL, and smart filter won't work.

**Comment by Tharn** [comment]
The problem now is that this is all I'm getting, and I don't know how to add any custom permissions that don't show up here on this page. I'm on FF 78 ESR, maybe that has something to do with it?
![Untitled](https://user-images.githubusercontent.com/13466852/120620790-9a9e4b80-c45d-11eb-917e-9c5945719f61.png)

**Comment by mymindstorm** [comment]
It should prompt you for that permission when you try to scan a page's qr code. What version is the extension? Your preferences page is missing things.

**Comment by Tharn** [comment]
Version 6.3.2.

I tried creating a fresh user profile and installing Authenticator there, and still I am getting no permissions prompts, nor can I set any permissions for it.

Hitting the "scan" button does prompt for a permission for data from all websites, but afterwards when I go into the extension settings the permissions field is blank again.

I can also confirm that trying Firefox 89 Portable, I get two optional permissions that I can enable. It seems ESR handles these differently.

**Comment by Shot2** [comment]
It should probably be mentionned somewhere that Firefox ESR is not supported by this add-on.

**Comment by mymindstorm** [comment]
That specifically is a bug in the ESR version, I have filed a report [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1733462). To get it to work for the time being, uninstall and install the extension and the permissions prompts should show up again. Make sure to allow the permissions needed whenever the prompt appears.

**Comment by yermulnik** [comment]
> I've had the same issue (autofill also stopped working). I fixed it by going to about:addons, Authenticator -> Permissions and and turning on "Access your data for all web sites".

@ChrisTiffin Yay, you saved my day dude! Thank you very much! 👍🏻
