### ISSUE TITLE
Strange Wording in "Indonesian" language 

### ISSUE THREAD

**Issue by RawSid** [Authenticator-Extension/Authenticator#669]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:**
We noted that on the _locales/id/messages.json on version 6.3.0 and 6.3.1, the translation of the Indonesian messages is suspicious.
<img width="1046" alt="Screen Shot 2021-05-19 at 23 10 14" src="https://user-images.githubusercontent.com/66819862/118846893-607a6900-b8f7-11eb-8dc2-63addc371b5d.png">

According to the changes on "About", it claims that the "account has been hacked and you can't login using the code".
For "Current_phrase", it claims that the old password is "sur4b4y4"
For "New_phares", it claims that the new password is "ju4nc0k224466"

For the changes, it scared us into thinking that the extension is somewhat compromised with those messages and claims

Could you check if this is intended? 

Can you explain why it was changed this way? Are you aware of this activity?

Thank you

**Platform:**
 - Browser: [Chrome]
 - Browser Version: 90.0.4430.212

**Comment by Sneezry** [comment]
@RawSid  those translations were contributed from community https://crowdin.com/project/authenticator-firefox/invite/public?show_welcome&d=d430fb213d76ee428041d812a1b0efc61133213

![image](https://user-images.githubusercontent.com/1621293/118851057-f7e5b900-b903-11eb-9046-174b4300eff0.png)

It should have already been fixed in the latest code.

**Comment by RawSid** [comment]
Thank you for the fast response!

The last question from me, did you check for any malicious changes other than the Indonesian translation file?

Thank you once again!

**Comment by Sneezry** [comment]
No other malicious files. All code must be reviewed before merged into main dev branch.

**Comment by RawSid** [comment]
Thank you @Sneezry . We will close this ticket

Best regards,
