### ISSUE TITLE
Backup issue (wrong keys)

### ISSUE THREAD

**Issue by YakovAvramenko** [Authenticator-Extension/Authenticator#670]
I was tried to Backup my keys (also File, or Google Drive), but everytime I am importing Backup file to the new laptop - all keys are different(from original laptop), and they are completely useless, since they are wrong (different).

**Platform:** Mac 10.14.6 (18G103)
 - Browser: Chrome
 - Browser Version: Version 80.0.3987.106 (Official Build) (64-bit)

**Comment by Sneezry** [comment]
Try to sync clock with Google in settings menu

**Comment by YakovAvramenko** [comment]
@Sneezry Thank you a lot, my friend =)
It works like a charm!
