### ISSUE TITLE
Auto release with Travis

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#68]

**Comment by mymindstorm** [comment]
I can deploy using web-ext, but is there a way to automatically deploy to the chrome web store?

We will need to [limit deployment to release branch](https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A) and [encrypt deploy keys](https://docs.travis-ci.com/user/encryption-keys/)

**Comment by Sneezry** [comment]
I do not think we should make it auto release to stores. Auto release here means on GitHub.

**Comment by mymindstorm** [comment]
That's easier, I can handle auto tagging.
