### ISSUE TITLE
Allow me to drag to sort the entries

### ISSUE THREAD

**Issue by adelara** [Authenticator-Extension/Authenticator#686]
**Describe the feature you want:**
I want to sort/order the entries in Authenticator by way of dragging them up or down

**Why do you want this feature in Authenticator?**
Because most use two or three of the entries and want them to be in the top

**Comment by mymindstorm** [comment]
This is a feature already, you should be able to drag accounts in edit mode.

**Comment by adelara** [comment]
oh boy, I missed the pencil and tried to drag right away. Thanks !!
