### ISSUE TITLE
I have 2 weeks that I can enter my platforms I always get that all the codes are incorrect

### ISSUE THREAD

**Issue by johan2325** [Authenticator-Extension/Authenticator#692]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 

**Platform:** <This is required>
 - Browser: [Chrome, Firefox]
 - Browser Version:

**Comment by Sneezry** [comment]
Try Settings -> Sync clock with Google
