### ISSUE TITLE
Sync Backup with Google

### ISSUE THREAD

**Issue by pceribelli** [Authenticator-Extension/Authenticator#699]
https://user-images.githubusercontent.com/66589136/124895351-c375ab80-dfdc-11eb-9fc9-36f613492f12.mp4

**Describe the bug:** <when try to backup on google the program stat but don't make backup I have created a video to show you.> 

https://user-images.githubusercontent.com/66589136/124895417-d25c5e00-dfdc-11eb-9958-8185ce0b6af5.mp

 - Browser: [Chrome,
 - Browser Version:Versione 91.0.4472.124 (Build ufficiale) (a 64 bit)

**Comment by Sneezry** [comment]
Should duplicate with https://github.com/Authenticator-Extension/Authenticator/issues/676

**Comment by mymindstorm** [comment]
Closing as duplicate
