### ISSUE TITLE
Base32 padding (=) processed as Invalid

### ISSUE THREAD

**Issue by Rictusempra** [Authenticator-Extension/Authenticator#70]
Actually, a lot of site will generate such tokens with (=), e.g. Amazon, Dropbox, Vultr. I'm pretty sure there will be more.

**Comment by mymindstorm** [comment]
Just regenerated codes for Amazon and Dropbox, they do not format their secrets like that. Can you give us a secret that you couldn't add so we can reporduce?

**Comment by Rictusempra** [comment]
I will give you one tonight as I am out now

**Comment by Rictusempra** [comment]
@mymindstorm @Sneezry 
check this (from Dropbox):
`DKCE3SQPHJRJQGBGI322QA7Z5E======`

Actually those equal symbols will only occur when you scan the QR code but not if you demand a text token.
Although I'm confident enough manually remove them won't cause issue but neither your wiki mention this nor your extension trim them. Users can get really confused when they are trying to import tokens manually from their own backups.

**Comment by Sneezry** [comment]
This would be Base32 bug on our side. I just checked RFC, there 5 cases about padding: no padding, six padding, four padding, three padding and one padding. https://tools.ietf.org/html/rfc4648#section-6

I will fix this issue sooner, thanks @Rictusempra

**Comment by Sneezry** [comment]
This issue should be fixed in the latest code. Next release will be published in the next week.

**Comment by mymindstorm** [comment]
This issue has been fixed via c6d85480d719a9de5bb7d21808e8172b205cfb63. I will notify you when we release the fix.

**Comment by mymindstorm** [comment]
Update has been uploaded. You might have to wait a few days for it to get to you, follow [these steps](https://github.com/Authenticator-Extension/Authenticator/issues/64#issuecomment-370291688) to try and force an update
