### ISSUE TITLE
This plugin does not work with Google App

### ISSUE THREAD

**Issue by yhackup** [Authenticator-Extension/Authenticator#701]
I use it for 2 different systems, but I added a new one today, while 2 of them are correct, the 3th generates incorrect code, the phone application and the code produced by the plugin do not match

![image](https://user-images.githubusercontent.com/15657038/124923693-617c6c80-e003-11eb-8e41-a94277bf7ea4.png)

 - Browser: Chrome
 - Browser Version: 91.0.4472.124

**Comment by yhackup** [comment]
![WhatsApp Image 2021-07-08 at 15 14 50](https://user-images.githubusercontent.com/15657038/124923927-9983af80-e003-11eb-8482-aa3ac94b3919.jpeg)

**Comment by Sneezry** [comment]
Try settings-Sync Clock with Google.

Don't share your secret/QR code in public. You should reset the leaked secrect in the thread.

**Comment by yhackup** [comment]
it doesn't matter unfortunately it's still wrong

**Comment by yhackup** [comment]
Your application is reading an incorrect secret key from within the QR code. When I run the secret key produced by your plugin in my c# application, incorrect code is generated. but when the QR code is read with the Android app, the correct code is generated

**Comment by Sneezry** [comment]
I can confirm this is our code bug. I will try to fix this issue.

**Comment by yhackup** [comment]
Thank you, I will try to support you in everything, regards ,let me post one more thing maybe it will be a clue for you, the secret key of other systems is 40 characters, but this one has 25 characters

**Comment by Sneezry** [comment]
We have a bug to handle base32 encoding when parse google authenticator migration URL. I have create a PR to fix it. Thanks for the feedback.

**Comment by yhackup** [comment]
I think the problem is solved, let's update it
