### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by metonet** [Authenticator-Extension/Authenticator#703]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 

**Platform:** <This is required>
 - Browser: [Chrome, Firefox]
 - Browser Version:

**Comment by metonet** [comment]
Chrome

**Comment by Sneezry** [comment]
Hi @metonet , could you share more details about the issue you met? Do you have a permission issue when you use Authenticator extension? What is the permission that makes problem? What is the impact?

**Comment by Sneezry** [comment]
Closing this issue since no furthur detail.
