### ISSUE TITLE
Fully encrypt backup

### ISSUE THREAD

**Issue by TRPB** [Authenticator-Extension/Authenticator#704]
**Describe the feature you want:**

At the moment, I'm syncing the backup to OneDrive (a very nice feature that saves me a little automation) however the backup file is not particularly secure. The JSON file gives away a lot of information. I don't know what the TOTP secrets look like normally but it's possible these are encrypted. Other information in the file is not. Anyone who accesses the json file can see a list of services I use and my account names. 

**Why do you want this feature in Authenticator?**

It would be better if the JSON file was fully encrypted using a key. I use a key to unlock the addon, can the same key be used to encrypt the entire json file during the  backup process? Obviously you'd need to also ask for the key during backup import.

**Comment by ashutoshsaboo** [comment]
Any update on this @mymindstorm @Sneezry ? Is it on the near term roadmap?

**Comment by mymindstorm** [comment]
Not currently but you are welcome to submit a PR.
