### ISSUE TITLE
Edit secret token after adding code

### ISSUE THREAD

**Issue by Rictusempra** [Authenticator-Extension/Authenticator#71]

**Comment by mymindstorm** [comment]
I don't really understand what this one is about. Do you want to be able to change the secret for a code after you add it?

**Comment by Rictusempra** [comment]
> change the secret for a code after you add it

Exactly

**Comment by Sneezry** [comment]
Why not just add a new one?

**Comment by Rictusempra** [comment]
> Why not just add a new one?

Because I will have to rewrite issuers & account name in that case.
 This save many clicks when you have new tokens or try to import manually

**Comment by Sneezry** [comment]
But what if you change it by mistake? Safe and convenience, I prefer the first.

**Comment by Rictusempra** [comment]
@Sneezry  sure. I manually type a json on my onedrive. But in that case, editable secret token field still give you more convenience.

**Comment by mymindstorm** [comment]
-  I don't think people change secrets so often that we should let them change that directly
- You shouldn't be manually typing out the JSON yourself
-  Letting users edit this directly will definitely cause problems. If we make secrets too accessable then we will have people mistakenly corrupting them or sharing them.

If this goes anywhere it will be a debugging menu or dedicated advanced settings page.
