### ISSUE TITLE
Removal of Edge version

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#710]
The Edge version has been rejected in certification and Microsoft refuses to be specific as to why this is happening.

> Thank you for contacting us. The product, including its listing, does not accurately represent the product and may mislead users. Your product may not use a name or icon that is too similar to that of other products.  Products need to have unique functionality and value in the Store. You may want to review the metadata section of our Product Quality guidelines here: https://msdn.microsoft.com/en-us/library/windows/apps/mt652261.aspx.

I believe that we have probably violated "Your product may not use a name or icon that is too similar to that of other products" because our name is very generic (e.g. "Google Authenticator", "Microsoft Authenticator", etc.). Since this is something that I feel is not worth changing just to keep a version on the Edge store, I will take it down in favor of the Chrome version.

**Comment by mymindstorm** [comment]
rip
![image](https://user-images.githubusercontent.com/27789806/125714799-5ccd3ac5-579a-4959-8126-9ea2af2723ec.png)

**Comment by Sneezry** [comment]
Since the new Edge can install extension from Chrome Web Store, I think we can remove it from Microsoft store.

To long term, we may consider to change a new name of the extension to avoid such an issue in the feature.

**Comment by mymindstorm** [comment]
That is going to be a hard decision to make :(

**Comment by 29039** [comment]
Please either remove the link on your homepage to the Microsoft Webstore version and link to Google instead, or pick out a new name :)
