### ISSUE TITLE
feature request: sync using firefox sync

### ISSUE THREAD

**Issue by nanderer** [Authenticator-Extension/Authenticator#716]
**Describe the feature you want:**
It would be grate if you could add a feature to sync the codes through firefox sync, maybe by creating some special bookmarks or using saved password feature for each code that do not lead to an url but to the codes.

**Why do you want this feature in Authenticator?**
i have firefox and the authentificator addon on a lot of computers and its anoing to always manually export/ import the backup file to get them all in sync, i have them all in my firefox account mostly to sync the passwords, but it would be very grate if you could sync authentificator codes to. I sometimes add some password to the "firefox lockwise" feature to add a passwort that is not for login to a website just by typing in an imaginary url like "local.computername", i guess you could do to like "Authenticator.paypal" or so....

thanks in advance and keep up the good work

**Comment by mymindstorm** [comment]
We already integrate though extension data sync if you are signed in to your browser. Although the extension is unable to control when a sync occurs so it can be finicky.
