### ISSUE TITLE
The code does not appear

### ISSUE THREAD

**Issue by ghost** [Authenticator-Extension/Authenticator#717]
### Describe the issue

![image](https://user-images.githubusercontent.com/87731835/126402412-33f15ebc-c43c-4843-a10e-a31e45ca3c7b.png)

Hi everyone!
The code doesn't appear when I go to the extension.
In the past few weeks, I had to remove my hard disk and replace it with a solid one, and all the OS have had to be reinstalled also. I think this can may be the issue.

### Browser

Chrome

### Browser Version

Versión 91.0.4472.124 (Build oficial) (64 bits)

### Extension Version

6.3.2

**Comment by mymindstorm** [comment]
> In the past few weeks, I had to remove my hard disk and replace it with a solid one, and all the OS have had to be reinstalled also. I think this can may be the issue.

That is the cause of the issue. You need to boot with the old hard drive, export to a flash drive or similar, and re-import on the new hard drive.
