### ISSUE TITLE
Missing from Microsoft Edge store

### ISSUE THREAD

**Issue by 29039** [Authenticator-Extension/Authenticator#719]
### Describe the issue

I go to https://authenticator.cc/ and click "Add to Edge" and it redirects me to https://microsoftedge.microsoft.com/addons/detail/ocglkepbibnalbgmbachknglpdipeoio and get the error: "We are sorry, the page you requested cannot be found"

I can install from the Chrome store (using Edge) fine.

### Browser

Edge

### Browser Version

Version 92.0.902.55 (Official build) (64-bit)

### Extension Version

N/A

**Comment by 29039** [comment]
Not found when searching the store either

**Comment by Sneezry** [comment]
See https://github.com/Authenticator-Extension/Authenticator/issues/710 & https://github.com/Authenticator-Extension/authenticator.cc/issues/20
