### ISSUE TITLE
Add issuer field to manual add screen

### ISSUE THREAD

**Issue by Rictusempra** [Authenticator-Extension/Authenticator#72]
![image](https://user-images.githubusercontent.com/16912240/37239576-4ddfb5cc-2479-11e8-83ee-1a4fab3947ab.png)

Here, there shall be fields for both issuer & account name

**Comment by mymindstorm** [comment]
I think this one is intentional since it would be a bit confusing for new users. "Account" and "Issuer" are a bit ambiguous.

**Comment by Rictusempra** [comment]
> "Account" and "Issuer" are a bit ambiguous.

Why not change it to `Account name` just like Yubioath Authenticator

**Comment by mymindstorm** [comment]
Now that I think about it we should have used that or `Username`.

**Comment by mymindstorm** [comment]
We actually already have a string for `accountName` with translations, will change that from account later.

**Comment by Sneezry** [comment]
This is as design, as @mymindstorm said, user may confuse with issuer and account.
