### ISSUE TITLE
Fill via Context Menu

### ISSUE THREAD

**Issue by Rictusempra** [Authenticator-Extension/Authenticator#73]
I'm sure WebExt can add a costumed context menu in Firefox but I'm not sure about Chrome/Chromiums

**Comment by mymindstorm** [comment]
This is possible in Chrome and Firefox. I'm not sure about the overhead though. To do this we would need to inject a script into every webpage, not just when we need to have the qr scanned. This means that it would have to be loaded in memory 24/7 making using event pages pointless. How should it handle site conflicts if this were implemented? I think we would end up with close to the same amount of clicks than what we currently do (it auto filters codes by issuer which is nice).

This last part is just my opinion, but I think extension context menu options just clutter the menu. At most users tend to authenticate on one or two pages per domain, and now we have an insert code button on every page for every site for that account.

**Comment by nnc55** [comment]
@

**Comment by Sneezry** [comment]
The latest version has auto fill feature, close this.
