### ISSUE TITLE
Google drive manual backup fails

### ISSUE THREAD

**Issue by innocent-velociraptor** [Authenticator-Extension/Authenticator#735]
### Describe the issue

Hello,

Steps to reproduce the issue:
Go to: Settings => Backup => Google Drive => Manual Backup
Settings used for the G drive backup: Account: xxxxx@gmail.com / Encrypted: Yes

Issue description: Nothing happens when I click on the 'Manual Backup' button (and the backuped file doesn't appear on my Google Drive either).

I attached the console log.

Thanks.

[bhghoamapcdpbohphigoooaddinpkbai-1630786644380.log](https://github.com/Authenticator-Extension/Authenticator/files/7110469/bhghoamapcdpbohphigoooaddinpkbai-1630786644380.log)

### Browser

Chrome

### Browser Version

Version 93.0.4577.63 (Official Build) (64-bit)

### Extension Version

6.3.2

**Comment by mymindstorm** [comment]
This is already fixed (70fb304a44c1288ca74c6a47893a15c6f55fa317) pending a new release.

**Comment by innocent-velociraptor** [comment]
Ok, thanks.
Any idea when the fixed version will be released?
