### ISSUE TITLE
Something extraneous in the message line

### ISSUE THREAD

**Issue by uap4** [Authenticator-Extension/Authenticator#738]
https://github.com/Authenticator-Extension/Authenticator/blob/a0c57943cda44f428a19c5fe0e6e62f1d8f1c18f/_locales/ru/messages.json#L145
It seems to me that `как решь проблему.` in this line is extraneous.

**Comment by Sneezry** [comment]
Thanks for the feedback. The translation has been fixed in the recent code, and will be released in the next version.
