### ISSUE TITLE
Bug: Bittrex authenticator not work

### ISSUE THREAD

**Issue by richardyusan** [Authenticator-Extension/Authenticator#74]
code generated for bittrex is 000000

**Comment by nnc55** [comment]
000000

**Comment by Sneezry** [comment]
It seems Bittrex doesn't accept new users, could you please provide a sample secret?

**Comment by richardyusan** [comment]
here: DYRLWKBD7WTQYMV5s

after re apply 2fa using new secret it's work now lol

**Comment by Sneezry** [comment]
Is there a small s at the end of the secret? Also, if the secret you post above is your current secret, you should change it as it is public to anybody now.

**Comment by richardyusan** [comment]
yes there is s at the end, surely done

**Comment by Sneezry** [comment]
`s` is not a valid char in Base32, I believe this is Bittrex's bug
