### ISSUE TITLE
Recuperacion de mis datos

### ISSUE THREAD

**Issue by LUCASFX** [Authenticator-Extension/Authenticator#743]
### Describe the issue

Hola muy buenas tardes,he formateado mi celular y con eso he perdido mis codigos..no puedo acceder a ningun lugar ya que los necesito y no encuentro manera de recuperarlos.Que deberia hacer?

### Browser

Other

### Browser Version

Samsung Galaxy a10s

### Extension Version

?

**Comment by mymindstorm** [comment]
This project is unrelated to phone authenticator apps.
