### ISSUE TITLE
Resubmit the extension to Edge store

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#747]
Edge team had reached out to invite us to publish the extension to Edge store.

After talked with Edge team, they think the extension name is not an issue, and suggest us to resubmit the extension. 

Edge team will expedite the review after we resubmit the extension.

**Comment by mymindstorm** [comment]
Thanks for the help! I'll resubmit with the next version. Did they mention anything that we could do to help prevent this from happening again?

Also, they recently added analytics to the portal, it seems that this caused us to lose _a lot_ of Edge users:

![Screenshot from 2021-09-30 12-53-32](https://user-images.githubusercontent.com/27789806/135506381-43225736-04c4-46df-ae07-c5115a2cbf1a.png)

**Comment by mymindstorm** [comment]
Approved in partner center; I've reverted commits removing Edge documentation.

**Comment by Sneezry** [comment]
Edge team said we can reach out them directly if we have any questions in the future. Let me add you in the email thread. Does your email address end with evermiss.net?

**Comment by mymindstorm** [comment]
Yes is is my GitHub username and that domain. Thanks.
