### ISSUE TITLE
QR code not scanning properly

### ISSUE THREAD

**Issue by nt1m** [Authenticator-Extension/Authenticator#77]
Here's a sample barcode from the process:

![index-gauth](https://user-images.githubusercontent.com/1795135/37259903-85b962ac-2584-11e8-86d3-f5d0943b3c54.png)

**Comment by mymindstorm** [comment]
I'm able to add this, what is wrong with how it handles this currently?

**Comment by nt1m** [comment]
@mymindstorm It doesn't read the qr code in at all, which is a problem.

**Comment by Sneezry** [comment]
@nt1m nothing happens when you scan the code or popup Unrecognized QR code? Can you see the gray layer on web page when you scan the code?

**Comment by nt1m** [comment]
@Sneezry It says the QR code is unrecognized.

**Comment by mymindstorm** [comment]
@nt1m does this affect all QRs you try to scan or just this one? Try to add [this one](https://chart.googleapis.com/chart?chs=400x400&chld=M|0&cht=qr&chl=otpauth://totp/mymindstorm-test?secret=UJD5WBIAPV6C2UJKRPNUN3XRYUR4M7J4), make sure to get everything with a white background inside the scan area.

**Comment by nt1m** [comment]
@mymindstorm hmm, doesn't work on the one you give me either.

Could be related to the fact that I have a retina screen, which might upscale your canvas by 2 (window.devicePixelRatio).

**Comment by mymindstorm** [comment]
Was going to ask about that next, beat me to it. Looks like this was an issue at one point in old extension too https://github.com/Sneezry/authenticator/commit/5d298ff3cc493021e9682ce8765ac4c99c9dcef2

**Comment by mymindstorm** [comment]
Nevermind, it looks like we are already scaling.
https://github.com/Authenticator-Extension/Authenticator/blob/a6651908fc8b23998462c39aaadd72ecbed0d4d2/src/content.ts#L125-L128

**Comment by Sneezry** [comment]
We will add a QR debug console page in the next version for QR debug.

We need more info to fix issue, but it's hard to ask user to provide information we need, such as the captured image.

**Comment by mymindstorm** [comment]
@nt1m after you update to the latest version click the about button in the menu and scroll to the bottom. Click the link that says "QR Debugging". When the page opens go back to this tab and try to scan the code again. Then go to the debugging tab, copy and paste all the text that appears, and upload the picture that appears under "Captured Screenshot"

**Comment by nt1m** [comment]
@mymindstorm @Sneezry Thanks, I submitted #92 which fixes the problem on my side.

**Comment by Sneezry** [comment]
It seems Firefox capture screenshot as non-HiDPI image.

**Comment by Sneezry** [comment]
Code ready: https://github.com/Authenticator-Extension/Authenticator/pull/97
