### ISSUE TITLE
Cannot Decrypt Account Data

### ISSUE THREAD

**Issue by pravinxor** [Authenticator-Extension/Authenticator#779]
### Describe the issue

When trying to decrypt synced account data, the 'Ok' button or Enter key don't do anything after filling in the text field with a valid password

### Browser

Firefox

### Browser Version

95.0a1 (2021-10-26)

### Extension Version

5.3.2

**Comment by mymindstorm** [comment]
This is due to Mozilla disabling all of the 6.x versions that have a newer encryption scheme. It will be fixed when Mozilla reviews the latest version. See #774

**Comment by mymindstorm** [comment]
It has been approved, you should be able to go to `about:addons` and check for updates:
![Screenshot from 2021-10-27 09-45-39](https://user-images.githubusercontent.com/27789806/139089533-75aeafb7-643d-45e9-b88e-9d7b2a184e15.png)

**Comment by pravinxor** [comment]
Sounds good, looks like everything works again!
