### ISSUE TITLE
background going black everytime i try to scrolling the pop window

### ISSUE THREAD

**Issue by TimWei** [Authenticator-Extension/Authenticator#78]
firefox version 57.0.4(64bit)

![image](https://user-images.githubusercontent.com/13130496/37277417-80a781cc-261f-11e8-8c01-b6c91042b2aa.png)

**Comment by mymindstorm** [comment]
This looks like a problem with how the browser renders the extension.

Try setting `layers.offmainthreadcomposition.enabled` in about:config to false and restarting firefox. If that doesn't work try following [these steps](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_checking-extension-settings). If none of these work then look for updates for your graphics driver and reboot your computer.

**Comment by TimWei** [comment]
layers.offmainthreadcomposition.enabled not found in about:config
![image](https://user-images.githubusercontent.com/13130496/37319574-a9f29cca-26aa-11e8-85bf-0f44efcc2d1b.png)

other suggestions above was tried including upgrade Firefox version to 58.0.2,  none of those work though.

and found that there is another rendering problem while closing QR code scanning screen.
![image](https://user-images.githubusercontent.com/13130496/37319691-2739deaa-26ab-11e8-92e5-64441e1eaaf7.png)

these problems does not affect the usage of application anyway, just report it.

**Comment by mymindstorm** [comment]
This is a rendering issue with how Firefox renders things in the toolbar in Windows. You should open a ticket on their bug tracker. I'm not aware of anything we can do to prevent this.

If you open it directly (go to `about:debugging` and click manifest url, then change `/manifest.json` to `/popup.html`) you shouldn't see artifacts.
