### ISSUE TITLE
Blank popup on first use with Heroku/Salesforce

### ISSUE THREAD

**Issue by wvengen** [Authenticator-Extension/Authenticator#788]
### Describe the issue

When trying to use this app the first time setting up for a Heroku (=Salesforce) account, the popup shown is completely empty:

![image](https://user-images.githubusercontent.com/503804/140711254-dca8e33c-14ca-4b76-ac66-addbfb8d75b5.png)

The browser error console shows:

![image](https://user-images.githubusercontent.com/503804/140710548-f4afbb01-7715-4f6a-9aee-e12809bc1153.png)

I have given the necessary permissions in the extension config.

### Browser

Firefox

### Browser Version

94.0 (64-bit)

### Extension Version

v6.3.4

**Comment by mymindstorm** [comment]
This is because your Firefox is configured to disable the `storage.sync` APIs, which is nonstandard.  Set the configuration value in `about:config` that the error logs reference to fix this.
