### ISSUE TITLE
Unable to export to create a backup

### ISSUE THREAD

**Issue by mtompkins** [Authenticator-Extension/Authenticator#80]
No response when clicking the Export / Download Backup button.
v5.0.6 in Chrome

**Comment by mymindstorm** [comment]
Have you encrypted your secrets at any point in time?

Follow [these steps](https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information) and try to click the download button again, then paste anything in the console.

**Comment by mtompkins** [comment]
To my memory, I have never encrypted my secrets but I could not sware to it.
Everything else works properly to my knowledge
Nothing produced in the console output window when clicking the export button.

Thanks for trying to have a look at this. Happy to provide whatever more I can.

**Comment by mymindstorm** [comment]
Go to `chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/import.html` and give me a screenshot of that page

**Comment by mtompkins** [comment]
![screenshot from 2018-03-13 17-25-08](https://user-images.githubusercontent.com/4105910/37370760-900cbc8a-26e3-11e8-8d3f-ac36330f8f3d.png)

**Comment by mymindstorm** [comment]
And when you click the button it doesn't show anything? Or can you get to this screen?
![image](https://user-images.githubusercontent.com/27789806/37371019-3bc36006-26cb-11e8-8d81-5c73900338b5.png)

**Comment by mtompkins** [comment]
I get to the screen you last posted, but when clicking Download Backup File there is no response. Apologies for not being more clear at what point I was having difficulty.

**Comment by mymindstorm** [comment]
That makes more sense. If you check your downloads folder, do you see a file called `authenticator.json`?

**Comment by mtompkins** [comment]
Nothing in my downloads folder (I'm on linux if that helps).

**Comment by mymindstorm** [comment]
At least in firefox you should be able to right click the download backup link and use "Save File As..." to download the backup file

**Comment by mtompkins** [comment]
Sweet mercy that's it!!!   
I was so focused on (left) clicking the button I didn't realize it's really a link I could right click on.   
Thanks so much.

**Comment by mymindstorm** [comment]
Normally it will just start a download. I use Fedora and don't have any problems, maybe you have some sort of security policy preventing the download?

**Comment by mtompkins** [comment]
I'll try and see if I can narrow it down. I'm on `Arch` and do have ABP & Privacy Badger in Chrome but I don't think they interfere. If I stumble across it I'll be sure to share.
