### ISSUE TITLE
6.3.3 in Chrome stuck on "Loading"

### ISSUE THREAD

**Issue by wmertens** [Authenticator-Extension/Authenticator#802]
### Describe the issue

When I try to unlock the extension, it shows "Loading" but nothing else. The background page doesn't show an error.

Version is 6.3.3, the latest in the Chrome web store.

How can I extract a backup in this state?

### Browser

Chrome

### Browser Version

96

### Extension Version

6.3.3

**Comment by mymindstorm** [comment]
Please follow [these steps](https://authenticator.cc/docs/en/debug-info) and reproduce the issue.
