### ISSUE TITLE
Not Sure How To Bring Over Existing 2FA entries from Google Authenticator

### ISSUE THREAD

**Issue by jameshfischer** [Authenticator-Extension/Authenticator#808]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>
<You can also open an issue by Tweeting @AuthExtension>

Perhaps I am just dense, but I was looking for a way to add the existing entries from Google Authenticator (on an Android phone) to this new set up for Edge and Firefox.  When using phones, one creates a QR code to "export accounts", and reads that QR code with the new authenicator app on the new phone, and the two are now "synched", with identical 2FA access abilities to the same logons.

How to accomplish this with this app?

**Comment by mymindstorm** [comment]
Settings -> Backup -> Import -> Import QR Image Backup
