### ISSUE TITLE
google auth not show 

### ISSUE THREAD

**Issue by badshah55** [Authenticator-Extension/Authenticator#82]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes> 
when i click extension only empty show

**Comment by Sneezry** [comment]
We need more detail to help you to solve the issue:

* Which browser do you user, Firefox or Chrome?
* What is the extension version?
* What is the latest time it worked?

**Comment by Sneezry** [comment]
@badshah55 I will close this issue because we haven't received your response in a week.

Please feel free to open a new issue if you have any question.
