### ISSUE TITLE
Release v5.0.7

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#83]
Is there any other changes we need to merge before release v5.0.7? Is it okay for us to release v5.0.7 on March 17th?

**Comment by mymindstorm** [comment]
Nothing planned, I've added the French translations. I'm going to be traveling all day on the 17th, so instead let's release tomorrow (around 24h from now) if that's ok.

**Comment by Sneezry** [comment]
It's okay for me. Then I will merge v5.0.7 into release branch around 10:00 AM March 17th in Beijing time (9:00 PM March 16th in Houston, Texas).

**Comment by mymindstorm** [comment]
Thanks
