### ISSUE TITLE
Invaild Authenticator code

### ISSUE THREAD

**Issue by DORISB22** [Authenticator-Extension/Authenticator#846]
### Describe the issue

I am trying to authenticate a website with the correct code provided by the authenticator and it keeps saying the code is invalid no matter what i do. 

### Browser

Chrome

### Browser Version

 97.0.4692.99

### Extension Version

6.3.3

**Comment by Sneezry** [comment]
Try **Sync clock with Google** in settings menu

**Comment by Sneezry** [comment]
Closing this issue because of no further comments.
