### ISSUE TITLE
Lost Authenticator phone 

### ISSUE THREAD

**Issue by gilolinux** [Authenticator-Extension/Authenticator#854]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>
<You can also open an issue by Tweeting @AuthExtension>
I need to disable Authenticator for my Facebook account, I lost the phone and can’t even login to my Facebook account again, and can’t have access to the bar code on the account but I have all other details

**Comment by mymindstorm** [comment]
If you lost your codes, you must recover through Facebook support. This project is unrelated to any phone apps.
