### ISSUE TITLE
Authenticator requires the 'Access your data for all websites' permission on Firefox but not Chrome?

### ISSUE THREAD

**Issue by ala-ebi** [Authenticator-Extension/Authenticator#868]
### Describe the issue

On Firefox, when you try to download the extension from Mozilla Addons, in the Permissions sections you can see that the extension requires 'Access your data for all websites'.

This is not the case for Chrome and I don't really see a need for it to have that access anyway, it could be something that was overlooked. But something like this is a turn off for many privacy concerned users.

### Browser

Firefox

### Browser Version

97.0.1 (64-bit)

### Extension Version

6.3.4

**Comment by mymindstorm** [comment]
Firefox unfortunately requires more permissions than chrome. You can read more [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureVisibleTab).
