### ISSUE TITLE
Firefox oauth token flow does not work

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#87]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

Error from Dropbox:

```
Invalid redirect_uri. It must exactly match one of the redirect URIs you've pre-configured for your app (including the path).
```

Extension UUIDs are random for every installation. Is this even possible on Firefox?

**Comment by mymindstorm** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/identity
https://developer.chrome.com/extensions/identity

**Comment by Sneezry** [comment]
I will add firefox redirect URL to dropbox

**Comment by Sneezry** [comment]
Ennn, it seems we really need switch oauth flow to native way. I just commited a workaround for firefox, but I'm not sure extension domain not changes in firefox (on my side, it's `moz-extension://1375455d-9177-e24d-96ea-9174e0619c0a`).

**Comment by mymindstorm** [comment]
@Sneezry uninstall it and install again (not the undo button), check `about:debugging` and uuid will be diffrent. I'm `    13b0bba6-84db-4796-940c-acbd1fb1e649` currently.

**Comment by Sneezry** [comment]
Then I suggest firefox rollback to 5.0.6 currently. We need to find a way to handle redirect URL for firefox.

We need to set specific redirect URL in dropbox:

<img width="848" alt="screen shot 2018-03-17 at 13 51 34" src="https://user-images.githubusercontent.com/1621293/37552156-58eb3880-29ea-11e8-9cd8-d54ff4299634.png">

**Comment by mymindstorm** [comment]
Already done. I would try to fix this myself, but I'm a bit busy, sorry.

**Comment by Sneezry** [comment]
Take it easy, this extension is not our full time work, right? Just do it when you have time and you want.

I will try to find the correct way to handle OAuth as well.

Have a good trip tomorrow ;-)

**Comment by Sneezry** [comment]
Code ready: https://github.com/Authenticator-Extension/Authenticator/pull/91
