### ISSUE TITLE
Invalid codes for Teamviewer

### ISSUE THREAD

**Issue by rkalitta** [Authenticator-Extension/Authenticator#872]
### Describe the issue

Can't make it work with Teamviewer (manually entered). Generates invalid codes. While it works with Google and Microsoft's authenticator apps. 

Works great anywhere else. And yes, it's synced with Google clock.

### Browser

Chrome

### Browser Version

98.0.4758.102

### Extension Version

6.3.3

**Comment by Sneezry** [comment]
Could you share a sample QR code of Teamviewer 2FA?

**Comment by rkalitta** [comment]
That would not be very wise of me. And I'm actually surprised that you even ask the question. You should know better. Why don't you create an account with Teamwiever yourself, if you do not already have one, and try to use the Authenticator-Extension with the Teamwiever's 2FA. It would be great if you could reproduce the issue.

**Comment by Sneezry** [comment]
Hi @rkalitta , I'm not asking QR code for your Teamviewer account. I mean you can see the QR code that the extension cannot work when you try to enable 2FA, and you can share it for investigation, but DONOT bind it to your account. When you refresh the 2FA page of Teamviewer, I believe they will give you a new QR code to bind.

As far as I know, Teamviewer is a paid software installed locally. If they provide a free account for trial, I'm glad to test with my own account.

**Comment by Sneezry** [comment]
You can easily use the QR code to share and click the Back button to deprecate it and generate a new one.

Teamviewer provides free accounts is news to me. Now I have my own account to test, but it seems to work nicely. If you have a sample QR code that the extension doesn't work, please consider sharing it without binding it to your real account.

![Snipaste_2022-03-15_18-58-14](https://user-images.githubusercontent.com/1621293/158364014-e7419242-334a-4258-b0d1-7e57000caa8f.png)
![Snipaste_2022-03-15_18-58-26](https://user-images.githubusercontent.com/1621293/158364022-b4a4bbd9-5fc0-45e1-8514-9528040e2f72.png)
![Snipaste_2022-03-15_19-00-00](https://user-images.githubusercontent.com/1621293/158364670-b640bfca-46a2-448c-8a5d-6ce7216c3e87.png)

**Comment by rkalitta** [comment]
I'm confused. After some further testing I can't reproduce the issue. It seem that I had Murphy over for a coffe that day. I see no reason to keep this open at this point.
