### ISSUE TITLE
Remove master branch

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#88]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

When developing the bulk of the extension using that branch was useful, but now it seems a bit redundant. Thoughts?

**Comment by Sneezry** [comment]
Emm, I agree. `master` branch seems useless now... I will remove it.

**Comment by Sneezry** [comment]
Done.
