### ISSUE TITLE
Urgent - Lost access to Authentication 

### ISSUE THREAD

**Issue by jotamazos** [Authenticator-Extension/Authenticator#882]
### Describe the issue

Hi there, 

I have a new iphone and I sold the last one. I am unable to access to my Authentication account where I have all my log-in codes.

I had set up the authentication on Instagram and I cannot log in since I have the new phone.

What would be the best way to get my recovery codes for Instagram?  

Thanks in advance,
Juanma

### Browser

Other

### Browser Version

Instagram & Google 

### Extension Version

Instagram & Google

**Comment by illisiumshopofficial** [comment]
как можно поменять на сайте 2fa code?

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
