### ISSUE TITLE
Google Authenticator 

### ISSUE THREAD

**Issue by Kashif9601** [Authenticator-Extension/Authenticator#888]
### Describe the issue

Hi google team,

please be request i had reset my device mobile huwaie y9.
Google authenticator was inside i did not take backup due to issue in mobile.

now i am trying to login but i do not have key. so please help me out to get rid off from this issues.

### Browser

Firefox

### Browser Version

latest 

### Extension Version

latest

**Comment by Sneezry** [comment]
This project has no relationship with Google's mobile app
