### ISSUE TITLE
backup from 4.20 fail

### ISSUE THREAD

**Issue by horeograf** [Authenticator-Extension/Authenticator#90]
Hi, I had version 4.20, there is a backup of the text, but importing the text does not work.
At me such format of record:

> REMOVED

On the page of the old backups shows this line:

> REMOVED

How do I import my data? Can you have the opportunity to give me version 4.20?

**Comment by mymindstorm** [comment]
First of all, do not ever paste your secrets anywhere. I've removed them for you, be more careful next time please.

Did you make sure to check the box that said encrypted and enter your password? You need to have the right password, or it won't work.

**Comment by Sneezry** [comment]
@mymindstorm  Let me handle this issue, and go to bed for trip tomorrow.

**Comment by mymindstorm** [comment]
You can get an older version for Firefox from [here](https://addons.mozilla.org/en-US/firefox/addon/auth-helper/versions/?page=1#version-4.21), you can't get an older version on chrome.

**Comment by Sneezry** [comment]
Hi @horeograf , I need some more information to help you to solve the problem.

Is the backup encrypted from 4.20? If the answer is yes, do you remember the password?

**Comment by mymindstorm** [comment]
@Sneerzy backup was encrypted. Time really flies when you work on something you enjoy, though that's not good for me right now ;-;

**Comment by horeograf** [comment]
Sneezry, hello, i dont have pasword, on 4.20 pasword not enable or i forget it (

**Comment by Sneezry** [comment]
It's easy to verify if you have set a password for the backup. What is the word after `encrypted`? Is it `true` or `false`?

For example, it is `false` as shown below:

<img width="365" alt="screen shot 2018-03-17 at 14 15 00" src="https://user-images.githubusercontent.com/1621293/37552315-a69a79ee-29ed-11e8-8879-1989a954d9c2.png">

**Comment by horeograf** [comment]
encrypted- true all lines ( f

**Comment by horeograf** [comment]
and i have all bacup from dir AppData\Local\Google\Chrome\User Data\Default\Extensions\bhghoamapcdpbohphigoooaddinpkbai\4.20_0
can mount to new browser?

**Comment by Sneezry** [comment]
Okay, then you have set a password for the backup. You need that password to import it into the extension. If you do not provide the password, the extension will just ignore the encrypted secret. If you remember the password, open import page (settings -> export/import -> import backup -> import text backup), paste the backup and check `Encrypted`, input the password, then click `Import Text Backup` button.

<img width="617" alt="screen shot 2018-03-17 at 14 29 04" src="https://user-images.githubusercontent.com/1621293/37552407-92047424-29ef-11e8-8a5c-bc0a68f4581b.png">

**Comment by Sneezry** [comment]
I do not think rollback the extension to old version will solve your problem, because your data is not stored in the extension. Even though you get an older version extension, your will not get back your data together.

**Comment by horeograf** [comment]
I remembered the password, but instead of code everywhere Invalid (((

**Comment by Sneezry** [comment]
Download backup file, and open it with notepad or other editor. What is the length of the secret?

**Comment by horeograf** [comment]
length 64

**Comment by Sneezry** [comment]
@horeograf what is the first 5 char?

**Comment by horeograf** [comment]
U2Fsd , and all secrets  the first identical 10 characters

**Comment by Sneezry** [comment]
Then it is encrypted, you must provide correct password to decrypt.

**Comment by horeograf** [comment]
Restored from the backup localdata chrome and the version of chrome in the program files, everything was exported well. But If I go, as a user of the browser, then rewrites
  settings and everything becomes encrypted. How fix that? Now all lines encrypted=false and working good.

**Comment by Sneezry** [comment]
If all secrets are decrypted, you can just import it from chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/import.html

**Comment by horeograf** [comment]
i do that, all working, but if i autorize as user chome all rewrites settings and everything lines becomes encrypted.

**Comment by Sneezry** [comment]
If I understand correctly, you can import backup and it works when you not sign in on Chrome, but after you signed in, all entry change to encrypted.

After you signed in, your data synced with Google will be synced to you browser, and the synced data is encrypted.

If you have all your data backup, and all backup is decrypted, or you know the password for encrypted data, you can safely reinstall the extension after signed in, and import the backup again.

**Comment by Sneezry** [comment]
@horeograf I will close this issue because we haven't received your response in a week.

Please feel free to open a new issue if you have any question.
