### ISSUE TITLE
AutoFill also copies to clipboard

### ISSUE THREAD

**Issue by Kief5555** [Authenticator-Extension/Authenticator#908]
### Describe the issue

When you enable autofill then press the code, first it already pastes it in the box and copies it. 

I think it should just search for a box to put the code in the web. If there isnt, then it copies. 

### Browser

Chrome

### Browser Version

Chromium@latest

### Extension Version

Latest

**Comment by kolAflash** [comment]
Maybe related with #878: _Prompt for <all_sites> permission in Firefox when enabling autofill_

**Comment by kolAflash** [comment]
Maybe related with #878: _Prompt for <all_sites> permission in Firefox when enabling autofill_
