### ISSUE TITLE
REINSTALLING AUTHENTICATOR WILL CLEAR YOUR DATA. NEVER REINSTALL AUTHENTICATOR TO FIX ANY ISSUES

### ISSUE THREAD

**Issue by junaidbinsarfraz** [Authenticator-Extension/Authenticator#933]
### Describe the issue

I just switched to new windows where I am trying to sync my previous Chrome profile. Everything else is synced, but the Google Authenticator is causing issues. Not authenticating my 2FA for sites like Bitfinix and Hotbit. 

Below is the error is given by Chrome

![image](https://user-images.githubusercontent.com/18396574/181918352-7dcbeda4-ddf9-4d2d-aa50-e28a7526e4d7.png)

### Browser

Chrome

### Browser Version

103.0.5060.134 (Official Build) (64-bit)

### Extension Version

6.3.3

**Comment by Sneezry** [comment]
This is as designed when first install the extension on a machine. Make sure browser sync has been enabled.
