### ISSUE TITLE
sync with google account

### ISSUE THREAD

**Issue by lang100** [Authenticator-Extension/Authenticator#941]
### Describe the issue

I have the extension installed on my chrome browser in which i am logged into my google account.    
when i try to open the extension on another pc , which is synced with the same google account.  
I get a message that there are "no accounts to display",
how can i get the authenticator to work also in the new PC ?

### Browser

Chrome

### Browser Version

104.0.5112.79

### Extension Version

6.3.3

**Comment by lzrpssy** [comment]
That's the whole idea of 2FA.  

Thanks for clearing up that the plugin actually works.

**Comment by Sneezry** [comment]
Please ensure that browser sync has been enabled
