### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by xmha97** [Authenticator-Extension/Authenticator#948]
### Describe the issue

# ❌ Actual Behavior
![image](https://user-images.githubusercontent.com/23485114/190449088-c12967a7-ce66-46d3-b635-9154eade999f.png)

# ✔️ Expected Behavior
![image](https://user-images.githubusercontent.com/23485114/190450327-0f362d6e-2482-4b29-b1c0-c9c18df6a050.png)

### Browser

Firefox

### Browser Version

104.0.2

### Extension Version

6.3.4

**Comment by TriMoon** [comment]
WFM on  Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0 ID:20221028093551 :woman_shrugging:

**Comment by Sneezry** [comment]
Duplicate with https://github.com/Authenticator-Extension/Authenticator/issues/722.

PR is welcomed.

**Comment by Sneezry** [comment]
Dark theme has been supported, but need to manually switch.
