### ISSUE TITLE
Cannot Import from Google Authenticator

### ISSUE THREAD

**Issue by jameshfischer** [Authenticator-Extension/Authenticator#953]
### Describe the issue

I used Google Authenticator to generate QR codes, and took a photo of those 2 QR codes with ANOTHER phone, as the Google Authenticator app does not permit one to screenshot the QR codes. Those well-focused, hi-rez images of the QR codes were fed into the "import" process as described by @mymindstorm in the forums, and the app gave the error "Unrecognized QR code". So, this a bug - this app is simply unable to read a Google Authenticator Generated QR code, and cannot be used with phones running Google Authenticator.

Same problem with both edge and Firefox, as this is not browser-related, of course.

### Browser

Edge

### Browser Version

104.0.1293.70

### Extension Version

6.3.4

**Comment by semeion** [comment]
Yeah, i have same issue. I need transfer my account from Google Authenticator to here and i have no idea how to do this.

Can someone tell me if it is possible? And how to transfer? Thanks

**Comment by Sneezry** [comment]
How many entries are in the QR code? Have you tried exporting 5 once a time?

**Comment by semeion** [comment]
The problem is how to read the QR code in firefox installed in the PC/Desktop if the QR Code is on Google Authenticator (in cellphone). I need tobuy a web cam for the PC or something like that?

**Comment by Sneezry** [comment]
If you are using iPhone you can take a screenshot directly. Otherwise, you
need to take a picture of your cellphone screen first by using another
device or webcam.

Alexandre Bolelli ***@***.***>于2023年3月22日 周三09:20写道：

**Comment by semeion** [comment]
yeah it is hard, i need two cellphones, one to make screenshot of another one, to send the pic to desktop with firefox, incredible

**Comment by semeion** [comment]
Because Google Authenticator don´t permit make a screenshoot of the QR Code

**Comment by thekendog** [comment]
So is there an easy way to import all my stuff from Google Authenticator on my iPhone to this extension in Chrome?  I can't figure it out.

**Comment by Sneezry** [comment]
> So is there an easy way to import all my stuff from Google Authenticator on my iPhone to this extension in Chrome? I can't figure it out.

See https://authenticator.cc/docs/en/export-and-import

**Comment by thekendog** [comment]
That doesn't work though.  Google Authenticator doesn't have a file export.  Only a QR code.  And I've tried doing a screenshot and importing that, but it doesn't work.  Throws an error.

**Comment by jameshfischer** [comment]
Because you cannot screenshot the QR code on the screen of the phone, you need to take a photo of the QR code on the phone screen with another camera, and then use THAT image as input to the other 2FA program.  While this seems insane, it works.

**Comment by mymindstorm** [comment]
Yeah, we acknowledge that but have too many options to make this easier.

On Feb 2, 2024, at 9:09 AM, jameshfischer ***@***.***> wrote:

﻿

Because you cannot screenshot the QR code on the screen of the phone, you need to take a photo of the QR code on the phone screen with another camera, and then use THAT image as input to the other 2FA program. While this seems insane, it works.

**Comment by thekendog** [comment]
> Because you cannot screenshot the QR code on the screen of the phone, you need to take a photo of the QR code on the phone screen with another camera, and then use THAT image as input to the other 2FA program. While this seems insane, it works.

Just tried that.  Still getting unrecognized QR code error.  Oh well.

**Comment by Sneezry** [comment]
> > Because you cannot screenshot the QR code on the screen of the phone, you need to take a photo of the QR code on the phone screen with another camera, and then use THAT image as input to the other 2FA program. While this seems insane, it works.
> 
> Just tried that. Still getting unrecognized QR code error. Oh well.

> Google Authenticator supports exporting up to 10 accounts at one time. However, when importing to Authenticator Extension it is recommended to export five accounts at one time to prevent errors.

Have you tried to export 5 accounts instead of 10 accounts?
