### ISSUE TITLE
POLONIEX

### ISSUE THREAD

**Issue by odecioreis** [Authenticator-Extension/Authenticator#96]
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

**Comment by odecioreis** [comment]
[download.pdf](https://github.com/Authenticator-Extension/Authenticator/files/1827928/download.pdf)

**Comment by Sneezry** [comment]
@odecioreis The pdf you post contains your POLONIEX account secret, if the secret is what you are using, you should change it immediately - this form is public, and everybody can see your secret.

The QR in pdf is not totp, it is just string of your secret and account address. A valid otp QR should start with `totp:` or `hotp:`.

If you have no idea how to enable 2FA for POLONIEX, you can seek help from <https://poloniex.freshdesk.com/support/home>
