### ISSUE TITLE
some/all(?) preferences are not synced, e.g. lock timeout (version 6.3.4)

### ISSUE THREAD

**Issue by it-1313** [Authenticator-Extension/Authenticator#965]
### Describe the issue

Hello,

thank you so much for this addon, it is really brilliant! However I think that some(?) preferences are not synced/stored in the Firefox account.

1. setup authenticator and some TOTPs on computer A, and set a lock after "X" minutes (I've tried 420 minutes, which is a day's work), and e.g. enable autofill. Let it sync with your firefox account
2. add computer B to sync your Firefox account. let is populate addons, and wait until all TOTP entries are visible on new device.
3. on computer B, go to preferences: timeout/autofill is not updated according to preferences on computer A.
4. go to computer A, and set preferences again (e.g. lock timeout, or auto-sync), and also change the description of a TOTP entry to verify successful sync. Then click to sync firefox account.
5. go to computer B, wait some minutes, then click sync Firefox account. Go the TOTP entries, verify the updated description shows up (so a sync has happened). Go to the preferences: still no changes.

I've tested Autofill, and Lock-timeout preferences. Neither of them syncs.

Would it be possible to add those/all(?) preferences to the firefox account/sync as well?

I think security-wise both autofill, and lock-timeout would be important to be synced, so e.g. if somebody steals my computer, somehow can unlock it, still my TOTP passwords are secured because of the timeout.

### Browser

Firefox

### Browser Version

106.2

### Extension Version

6.3.4

**Comment by Sneezry** [comment]
Hi @it-1313 this is as expected because preferences are not stored in sync scope. 

Considering a user may apply different preference settings on other devices, we don't enforce the same setting on all devices.

To secure concerns, there's Advisor tool in the menu that can provide suggestions for the security settings.

**Comment by it-1313** [comment]
Hi Sneezry,

thanks, I understand, and this makes sense in many circumstances.

But would it be possible to add an option in the preferences to also sync the preferences? I'm responsible for many non-IT users and was looking for a very simple way to have them use TOTP, and this addon is just perfect. However, when somebody forgets their windows password (or their computer stopped working and needs a complete reinstallation), it would be great if also the lockout period/auto-fill/other preferences could be synced, so I don't have to reconfig this again (or ask them for their preference). Most of those users only have one device, and we use Firefox syncfor backup of passwords, settings, etc.

**Comment by Sneezry** [comment]
Thanks for the explanation. Are you asking for this feature as a corporation IT team or an individual user? We also support policy configuration for enterprise users, and there's `enforceAutolock` [setting](https://github.com/Authenticator-Extension/Authenticator/blob/c0b42a68a6d64d61bb03ad8e5dad6278301cf33a/manifests/schema-chrome.json#L34-L38).

**Comment by it-1313** [comment]
Hi, 

oh my, I haven't seen this. Yes, its an organizational environment.

I tried to find a wiki/explanation here, but couldn't. Could you maybe share a link where I find information how I can deploy policies for addons? We cannot deploy group policies, but we could deploy a policy file similar to the Firefox policies.json file.

**Comment by Sneezry** [comment]
Does this doc work for you? https://authenticator.cc/docs/en/policy-config
